<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Country::insert([
            ['code_country' => 'AU', 'country_name' => 'Australia'],
            ['code_country' => 'CN', 'country_name' => 'China'],
            ['code_country' => 'JP', 'country_name' => 'Japan'],
            ['code_country' => 'TH', 'country_name' => 'Thailand'],
            ['code_country' => 'IN', 'country_name' => 'India'],
            ['code_country' => 'MY', 'country_name' => 'Malaysia'],
            ['code_country' => 'KR', 'country_name' => 'Kore'],
            ['code_country' => 'HK', 'country_name' => 'Hong Kong'],
            ['code_country' => 'TW', 'country_name' => 'Taiwan'],
            ['code_country' => 'PH', 'country_name' => 'Philippines'],
            ['code_country' => 'VN', 'country_name' => 'Vietnam'],
            ['code_country' => 'FR', 'country_name' => 'France'],
            ['code_country' => 'EU', 'country_name' => 'Europe'],
            ['code_country' => 'DE', 'country_name' => 'Germany'],
            ['code_country' => 'SE', 'country_name' => 'Sweden'],
            ['code_country' => 'IT', 'country_name' => 'Italy'],
            ['code_country' => 'GR', 'country_name' => 'Greece'],
            ['code_country' => 'ES', 'country_name' => 'Spain'],
            ['code_country' => 'AT', 'country_name' => 'Austria'],
            ['code_country' => 'GB', 'country_name' => 'United Kingdom'],
            ['code_country' => 'NL', 'country_name' => 'Netherlands'],
            ['code_country' => 'BE', 'country_name' => 'Belgium'],
            ['code_country' => 'CH', 'country_name' => 'Switzerland'],
            ['code_country' => 'AE', 'country_name' => 'United Arab Emirates'],
            ['code_country' => 'IL', 'country_name' => 'Israel'],
            ['code_country' => 'UA', 'country_name' => 'Ukraine'],
            ['code_country' => 'RU', 'country_name' => 'Russian Federation'],
            ['code_country' => 'KZ', 'country_name' => 'Kazakhstan'],
            ['code_country' => 'PT', 'country_name' => 'Portugal'],
            ['code_country' => 'SA', 'country_name' => 'Saudi Arabia'],
            ['code_country' => 'DK', 'country_name' => 'Denmark'],
            ['code_country' => 'IR', 'country_name' => 'Ira'],
            ['code_country' => 'NO', 'country_name' => 'Norway'],
            ['code_country' => 'US', 'country_name' => 'United States'],
            ['code_country' => 'MX', 'country_name' => 'Mexico'],
            ['code_country' => 'CA', 'country_name' => 'Canada'],
            ['code_country' => 'A1', 'country_name' => 'Anonymous Proxy'],
            ['code_country' => 'SY', 'country_name' => 'Syrian Arab Republic'],
            ['code_country' => 'CY', 'country_name' => 'Cyprus'],
            ['code_country' => 'CZ', 'country_name' => 'Czech Republic'],
            ['code_country' => 'IQ', 'country_name' => 'Iraq'],
            ['code_country' => 'TR', 'country_name' => 'Turkey'],
            ['code_country' => 'RO', 'country_name' => 'Romania'],
            ['code_country' => 'LB', 'country_name' => 'Lebanon'],
            ['code_country' => 'HU', 'country_name' => 'Hungary'],
            ['code_country' => 'GE', 'country_name' => 'Georgia'],
            ['code_country' => 'BR', 'country_name' => 'Brazil'],
            ['code_country' => 'AZ', 'country_name' => 'Azerbaijan'],
            ['code_country' => 'A2', 'country_name' => 'Satellite Provider'],
            ['code_country' => 'PS', 'country_name' => 'Palestinian Territory'],
            ['code_country' => 'LT', 'country_name' => 'Lithuania'],
            ['code_country' => 'OM', 'country_name' => 'Oman'],
            ['code_country' => 'SK', 'country_name' => 'Slovakia'],
            ['code_country' => 'RS', 'country_name' => 'Serbia'],
            ['code_country' => 'FI', 'country_name' => 'Finland'],
            ['code_country' => 'IS', 'country_name' => 'Iceland'],
            ['code_country' => 'BG', 'country_name' => 'Bulgaria'],
            ['code_country' => 'SI', 'country_name' => 'Slovenia'],
            ['code_country' => 'MD', 'country_name' => 'Moldov'],
            ['code_country' => 'MK', 'country_name' => 'Macedonia'],
            ['code_country' => 'LI', 'country_name' => 'Liechtenstein'],
            ['code_country' => 'JE', 'country_name' => 'Jersey'],
            ['code_country' => 'PL', 'country_name' => 'Poland'],
            ['code_country' => 'HR', 'country_name' => 'Croatia'],
            ['code_country' => 'BA', 'country_name' => 'Bosnia and Herzegovina'],
            ['code_country' => 'EE', 'country_name' => 'Estonia'],
            ['code_country' => 'LV', 'country_name' => 'Latvia'],
            ['code_country' => 'JO', 'country_name' => 'Jordan'],
            ['code_country' => 'KG', 'country_name' => 'Kyrgyzstan'],
            ['code_country' => 'RE', 'country_name' => 'Reunion'],
            ['code_country' => 'IE', 'country_name' => 'Ireland'],
            ['code_country' => 'LY', 'country_name' => 'Libya'],
            ['code_country' => 'LU', 'country_name' => 'Luxembourg'],
            ['code_country' => 'AM', 'country_name' => 'Armenia'],
            ['code_country' => 'VG', 'country_name' => 'Virgin Island'],
            ['code_country' => 'YE', 'country_name' => 'Yemen'],
            ['code_country' => 'BY', 'country_name' => 'Belarus'],
            ['code_country' => 'GI', 'country_name' => 'Gibraltar'],
            ['code_country' => 'MQ', 'country_name' => 'Martinique'],
            ['code_country' => 'PA', 'country_name' => 'Panama'],
            ['code_country' => 'DO', 'country_name' => 'Dominican Republic'],
            ['code_country' => 'GU', 'country_name' => 'Guam'],
            ['code_country' => 'PR', 'country_name' => 'Puerto Rico'],
            ['code_country' => 'VI', 'country_name' => 'Virgin Island'],
            ['code_country' => 'MN', 'country_name' => 'Mongolia'],
            ['code_country' => 'NZ', 'country_name' => 'New Zealand'],
            ['code_country' => 'SG', 'country_name' => 'Singapore'],
            ['code_country' => 'ID', 'country_name' => 'Indonesia'],
            ['code_country' => 'NP', 'country_name' => 'Nepal'],
            ['code_country' => 'PG', 'country_name' => 'Papua New Guinea'],
            ['code_country' => 'PK', 'country_name' => 'Pakistan'],
            ['code_country' => 'AP', 'country_name' => 'Asia/Pacific Region'],
            ['code_country' => 'BS', 'country_name' => 'Bahamas'],
            ['code_country' => 'LC', 'country_name' => 'Saint Lucia'],
            ['code_country' => 'AR', 'country_name' => 'Argentina'],
            ['code_country' => 'BD', 'country_name' => 'Bangladesh'],
            ['code_country' => 'TK', 'country_name' => 'Tokelau'],
            ['code_country' => 'KH', 'country_name' => 'Cambodia'],
            ['code_country' => 'MO', 'country_name' => 'Macau'],
            ['code_country' => 'MV', 'country_name' => 'Maldives'],
            ['code_country' => 'AF', 'country_name' => 'Afghanistan'],
            ['code_country' => 'NC', 'country_name' => 'New Caledonia'],
            ['code_country' => 'FJ', 'country_name' => 'Fiji'],
            ['code_country' => 'WF', 'country_name' => 'Wallis and Futuna'],
            ['code_country' => 'QA', 'country_name' => 'Qatar'],
            ['code_country' => 'AL', 'country_name' => 'Albania'],
            ['code_country' => 'BZ', 'country_name' => 'Belize'],
            ['code_country' => 'UZ', 'country_name' => 'Uzbekistan'],
            ['code_country' => 'KW', 'country_name' => 'Kuwait'],
            ['code_country' => 'ME', 'country_name' => 'Montenegro'],
            ['code_country' => 'PE', 'country_name' => 'Peru'],
            ['code_country' => 'BM', 'country_name' => 'Bermuda'],
            ['code_country' => 'CW', 'country_name' => 'Curacao'],
            ['code_country' => 'CO', 'country_name' => 'Colombia'],
            ['code_country' => 'VE', 'country_name' => 'Venezuela'],
            ['code_country' => 'CL', 'country_name' => 'Chile'],
            ['code_country' => 'EC', 'country_name' => 'Ecuador'],
            ['code_country' => 'ZA', 'country_name' => 'South Africa'],
            ['code_country' => 'IM', 'country_name' => 'Isle of Man'],
            ['code_country' => 'BO', 'country_name' => 'Bolivia'],
            ['code_country' => 'GG', 'country_name' => 'Guernsey'],
            ['code_country' => 'MT', 'country_name' => 'Malta'],
            ['code_country' => 'TJ', 'country_name' => 'Tajikistan'],
            ['code_country' => 'SC', 'country_name' => 'Seychelles'],
            ['code_country' => 'BH', 'country_name' => 'Bahrain'],
            ['code_country' => 'EG', 'country_name' => 'Egypt'],
            ['code_country' => 'ZW', 'country_name' => 'Zimbabwe'],
            ['code_country' => 'LR', 'country_name' => 'Liberia'],
            ['code_country' => 'KE', 'country_name' => 'Kenya'],
            ['code_country' => 'GH', 'country_name' => 'Ghana'],
            ['code_country' => 'NG', 'country_name' => 'Nigeria'],
            ['code_country' => 'TZ', 'country_name' => 'Tanzani'],
            ['code_country' => 'ZM', 'country_name' => 'Zambia'],
            ['code_country' => 'MG', 'country_name' => 'Madagascar'],
            ['code_country' => 'AO', 'country_name' => 'Angola'],
            ['code_country' => 'NA', 'country_name' => 'Namibia'],
            ['code_country' => 'CI', 'country_name' => 'Cote DIvoire'],
            ['code_country' => 'SD', 'country_name' => 'Sudan'],
            ['code_country' => 'CM', 'country_name' => 'Cameroon'],
            ['code_country' => 'MW', 'country_name' => 'Malawi'],
            ['code_country' => 'GA', 'country_name' => 'Gabon'],
            ['code_country' => 'ML', 'country_name' => 'Mali'],
            ['code_country' => 'BJ', 'country_name' => 'Benin'],
            ['code_country' => 'TD', 'country_name' => 'Chad'],
            ['code_country' => 'BW', 'country_name' => 'Botswana'],
            ['code_country' => 'CV', 'country_name' => 'Cape Verde'],
            ['code_country' => 'RW', 'country_name' => 'Rwanda'],
            ['code_country' => 'CG', 'country_name' => 'Congo'],
            ['code_country' => 'UG', 'country_name' => 'Uganda'],
            ['code_country' => 'MZ', 'country_name' => 'Mozambique'],
            ['code_country' => 'GM', 'country_name' => 'Gambia'],
            ['code_country' => 'LS', 'country_name' => 'Lesotho'],
            ['code_country' => 'MU', 'country_name' => 'Mauritius'],
            ['code_country' => 'MA', 'country_name' => 'Morocco'],
            ['code_country' => 'DZ', 'country_name' => 'Algeria'],
            ['code_country' => 'GN', 'country_name' => 'Guinea'],
            ['code_country' => 'CD', 'country_name' => 'Cong'],
            ['code_country' => 'SZ', 'country_name' => 'Swaziland'],
            ['code_country' => 'BF', 'country_name' => 'Burkina Faso'],
            ['code_country' => 'SL', 'country_name' => 'Sierra Leone'],
            ['code_country' => 'SO', 'country_name' => 'Somalia'],
            ['code_country' => 'NE', 'country_name' => 'Niger'],
            ['code_country' => 'CF', 'country_name' => 'Central African Republic'],
            ['code_country' => 'TG', 'country_name' => 'Togo'],
            ['code_country' => 'BI', 'country_name' => 'Burundi'],
            ['code_country' => 'GQ', 'country_name' => 'Equatorial Guinea'],
            ['code_country' => 'SS', 'country_name' => 'South Sudan'],
            ['code_country' => 'SN', 'country_name' => 'Senegal'],
            ['code_country' => 'MR', 'country_name' => 'Mauritania'],
            ['code_country' => 'DJ', 'country_name' => 'Djibouti'],
            ['code_country' => 'KM', 'country_name' => 'Comoros'],
            ['code_country' => 'IO', 'country_name' => 'British Indian Ocean Territory'],
            ['code_country' => 'TN', 'country_name' => 'Tunisia'],
            ['code_country' => 'GL', 'country_name' => 'Greenland'],
            ['code_country' => 'VA', 'country_name' => 'Holy See (Vatican City State)'],
            ['code_country' => 'CR', 'country_name' => 'Costa Rica'],
            ['code_country' => 'KY', 'country_name' => 'Cayman Islands'],
            ['code_country' => 'JM', 'country_name' => 'Jamaica'],
            ['code_country' => 'GT', 'country_name' => 'Guatemala'],
            ['code_country' => 'MH', 'country_name' => 'Marshall Islands'],
            ['code_country' => 'AQ', 'country_name' => 'Antarctica'],
            ['code_country' => 'BB', 'country_name' => 'Barbados'],
            ['code_country' => 'AW', 'country_name' => 'Aruba'],
            ['code_country' => 'MC', 'country_name' => 'Monaco'],
            ['code_country' => 'AI', 'country_name' => 'Anguilla'],
            ['code_country' => 'KN', 'country_name' => 'Saint Kitts and Nevis'],
            ['code_country' => 'GD', 'country_name' => 'Grenada'],
            ['code_country' => 'PY', 'country_name' => 'Paraguay'],
            ['code_country' => 'MS', 'country_name' => 'Montserrat'],
            ['code_country' => 'TC', 'country_name' => 'Turks and Caicos Islands'],
            ['code_country' => 'AG', 'country_name' => 'Antigua and Barbuda'],
            ['code_country' => 'TV', 'country_name' => 'Tuvalu'],
            ['code_country' => 'PF', 'country_name' => 'French Polynesia'],
            ['code_country' => 'SB', 'country_name' => 'Solomon Islands'],
            ['code_country' => 'VU', 'country_name' => 'Vanuatu'],
            ['code_country' => 'ER', 'country_name' => 'Eritrea'],
            ['code_country' => 'TT', 'country_name' => 'Trinidad and Tobago'],
            ['code_country' => 'AD', 'country_name' => 'Andorra'],
            ['code_country' => 'HT', 'country_name' => 'Haiti'],
            ['code_country' => 'SH', 'country_name' => 'Saint Helena'],
            ['code_country' => 'FM', 'country_name' => 'Micronesi'],
            ['code_country' => 'SV', 'country_name' => 'El Salvador'],
            ['code_country' => 'HN', 'country_name' => 'Honduras'],
            ['code_country' => 'UY', 'country_name' => 'Uruguay'],
            ['code_country' => 'LK', 'country_name' => 'Sri Lanka'],
            ['code_country' => 'EH', 'country_name' => 'Western Sahara'],
            ['code_country' => 'CX', 'country_name' => 'Christmas Island'],
            ['code_country' => 'WS', 'country_name' => 'Samoa'],
            ['code_country' => 'SR', 'country_name' => 'Suriname'],
            ['code_country' => 'CK', 'country_name' => 'Cook Islands'],
            ['code_country' => 'KI', 'country_name' => 'Kiribati'],
            ['code_country' => 'NU', 'country_name' => 'Niue'],
            ['code_country' => 'TO', 'country_name' => 'Tonga'],
            ['code_country' => 'TF', 'country_name' => 'French Southern Territories'],
            ['code_country' => 'YT', 'country_name' => 'Mayotte'],
            ['code_country' => 'NF', 'country_name' => 'Norfolk Island'],
            ['code_country' => 'BN', 'country_name' => 'Brunei Darussalam'],
            ['code_country' => 'TM', 'country_name' => 'Turkmenistan'],
            ['code_country' => 'PN', 'country_name' => 'Pitcairn Islands'],
            ['code_country' => 'SM', 'country_name' => 'San Marino'],
            ['code_country' => 'AX', 'country_name' => 'Aland Islands'],
            ['code_country' => 'FO', 'country_name' => 'Faroe Islands'],
            ['code_country' => 'SJ', 'country_name' => 'Svalbard and Jan Mayen'],
            ['code_country' => 'CC', 'country_name' => 'Cocos (Keeling) Islands'],
            ['code_country' => 'NR', 'country_name' => 'Nauru'],
            ['code_country' => 'GS', 'country_name' => 'South Georgia and the South Sandwich Islands'],
            ['code_country' => 'UM', 'country_name' => 'United States Minor Outlying Islands'],
            ['code_country' => 'GW', 'country_name' => 'Guinea-Bissau'],
            ['code_country' => 'PW', 'country_name' => 'Palau'],
            ['code_country' => 'AS', 'country_name' => 'American Samoa'],
            ['code_country' => 'BT', 'country_name' => 'Bhutan'],
            ['code_country' => 'GF', 'country_name' => 'French Guiana'],
            ['code_country' => 'GP', 'country_name' => 'Guadeloupe'],
            ['code_country' => 'MF', 'country_name' => 'Saint Martin'],
            ['code_country' => 'VC', 'country_name' => 'Saint Vincent and the Grenadines'],
            ['code_country' => 'PM', 'country_name' => 'Saint Pierre and Miquelon'],
            ['code_country' => 'BL', 'country_name' => 'Saint Barthelemy'],
            ['code_country' => 'DM', 'country_name' => 'Dominica'],
            ['code_country' => 'ST', 'country_name' => 'Sao Tome and Principe'],
            ['code_country' => 'KP', 'country_name' => 'Kore'],
            ['code_country' => 'FK', 'country_name' => 'Falkland Islands (Malvinas)'],
            ['code_country' => 'MP', 'country_name' => 'Northern Mariana Islands'],
            ['code_country' => 'TL', 'country_name' => 'Timor-Leste'],
            ['code_country' => 'BQ', 'country_name' => 'Bonair'],
            ['code_country' => 'MM', 'country_name' => 'Myanmar'],
            ['code_country' => 'NI', 'country_name' => 'Nicaragua'],
            ['code_country' => 'SX', 'country_name' => 'Sint Maarten (Dutch part)'],
            ['code_country' => 'GY', 'country_name' => 'Guyana'],
            ['code_country' => 'LA', 'country_name' => 'Lao Peoples Democratic Republic'],
            ['code_country' => 'CU', 'country_name' => 'Cuba'],
            ['code_country' => 'ET', 'country_name' => 'Ethiopia'],
        ]);
    }
}
