<?php

namespace Database\Seeders;

use App\Models\EconomicActivity;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EconomicActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        EconomicActivity::insert([
            ['EconomicActivity_number' => 10, 'description_EconomicActivity' => 'Asalariados.'],
            ['EconomicActivity_number' => 11, 'description_EconomicActivity' => 'Cultivos agrícolas transitorios.'],
            ['EconomicActivity_number' => 12, 'description_EconomicActivity' => 'Cultivos agrícolas permanentes.'],
            ['EconomicActivity_number' => 13, 'description_EconomicActivity' => 'Propagación de plantas (actividades de los viveros, excepto viveros forestales)'],
            ['EconomicActivity_number' => 14, 'description_EconomicActivity' => 'Ganadería.'],
            ['EconomicActivity_number' => 15, 'description_EconomicActivity' => 'Explotación mixta (agrícola y pecuaria).'],
            ['EconomicActivity_number' => 16, 'description_EconomicActivity' => 'Actividades de apoyo a la agricultura y la ganadería, y actividades posteriores a la cosecha.'],
            ['EconomicActivity_number' => 17, 'description_EconomicActivity' => 'Caza ordinaria y mediante trampas y actividades de servicios conexas.'],
            ['EconomicActivity_number' => 20, 'description_EconomicActivity' => 'Pensionados.'],
            ['EconomicActivity_number' => 21, 'description_EconomicActivity' => 'Silvicultura y otras actividades forestales.'],
            ['EconomicActivity_number' => 22, 'description_EconomicActivity' => 'Extracción de madera.'],
            ['EconomicActivity_number' => 23, 'description_EconomicActivity' => 'Recolección de productos forestales diferentes a la madera.'],
            ['EconomicActivity_number' => 24, 'description_EconomicActivity' => 'Servicios de apoyo a la silvicultura.'],
            ['EconomicActivity_number' => 31, 'description_EconomicActivity' => 'Pesca.'],
            ['EconomicActivity_number' => 32, 'description_EconomicActivity' => 'Acuicultura.'],
            ['EconomicActivity_number' => 46, 'description_EconomicActivity' => 'Comercio al por mayor y en comisión o por contrata, excepto el comercio de vehículos automotores y motocicletas.'],
            ['EconomicActivity_number' => 51, 'description_EconomicActivity' => 'Extracción de hulla (carbón de piedra).'],
            ['EconomicActivity_number' => 52, 'description_EconomicActivity' => 'Extracción de carbón lignito.'],
            ['EconomicActivity_number' => 61, 'description_EconomicActivity' => 'Extracción de petróleo crudo.'],
            ['EconomicActivity_number' => 62, 'description_EconomicActivity' => 'Extracción de gas natural.'],
            ['EconomicActivity_number' => 71, 'description_EconomicActivity' => 'Extracción de minerales de hierro.'],
            ['EconomicActivity_number' => 72, 'description_EconomicActivity' => 'Extracción de minerales metalíferos no ferrosos.'],
            ['EconomicActivity_number' => 81, 'description_EconomicActivity' => 'Extracción de piedra, arena, arcillas, cal, yeso, caolín, bentonitas y similares'],
            ['EconomicActivity_number' => 81, 'description_EconomicActivity' => 'Personas Naturales sin Actividad Económica'],
            ['EconomicActivity_number' => 82, 'description_EconomicActivity' => 'Extracción de esmeraldas, piedras preciosas y semipreciosas.'],
            ['EconomicActivity_number' => 82, 'description_EconomicActivity' => 'Personas Naturales Subsidiadas por Terceros'],
            ['EconomicActivity_number' => 89, 'description_EconomicActivity' => 'Extracción de otros minerales no metálicos n.c.p.'],
            ['EconomicActivity_number' => 90, 'description_EconomicActivity' => 'Rentistas de Capital, solo para personas naturales.'],
            ['EconomicActivity_number' => 91, 'description_EconomicActivity' => 'Actividades de apoyo para la extracción de petróleo y de gas natural.'],
            ['EconomicActivity_number' => 99, 'description_EconomicActivity' => 'Actividades de apoyo para otras actividades de explotación de minas y canteras'],
            ['EconomicActivity_number' => 101, 'description_EconomicActivity' => 'Procesamiento y conservación de carne, pescado, crustáceos y moluscos.'],
            ['EconomicActivity_number' => 102, 'description_EconomicActivity' => 'Procesamiento y conservación de frutas, legumbres, hortalizas y turbérculo'],
            ['EconomicActivity_number' => 103, 'description_EconomicActivity' => 'Elaboración de aceites y grasas de origen vegetal y animal.'],
            ['EconomicActivity_number' => 104, 'description_EconomicActivity' => 'Elaboración de productos lácteos.'],
            ['EconomicActivity_number' => 105, 'description_EconomicActivity' => 'Elaboración de productos de molinería, almidones y productos derivados del almidón.'],
            ['EconomicActivity_number' => 106, 'description_EconomicActivity' => 'Elaboración de productos de café.'],
            ['EconomicActivity_number' => 107, 'description_EconomicActivity' => 'Elaboración de azúcar y panela.'],
            ['EconomicActivity_number' => 108, 'description_EconomicActivity' => 'Elaboración de otros productos alimenticios.'],
            ['EconomicActivity_number' => 109, 'description_EconomicActivity' => 'Elaboración de alimentos preparados para animales.'],
            ['EconomicActivity_number' => 110, 'description_EconomicActivity' => 'Elaboración de bebidas.'],
            ['EconomicActivity_number' => 111, 'description_EconomicActivity' => 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas.'],
            ['EconomicActivity_number' => 112, 'description_EconomicActivity' => 'Cultivo de arroz.'],
            ['EconomicActivity_number' => 113, 'description_EconomicActivity' => 'Cultivo de hortalizas, raíces y tubérculos.'],
            ['EconomicActivity_number' => 114, 'description_EconomicActivity' => 'Cultivo de tabaco.'],
            ['EconomicActivity_number' => 115, 'description_EconomicActivity' => 'Cultivo de plantas textiles.'],
            ['EconomicActivity_number' => 119, 'description_EconomicActivity' => 'Otros cultivos transitorios n.c.p.'],
            ['EconomicActivity_number' => 120, 'description_EconomicActivity' => 'Elaboración de productos de tabaco.'],
            ['EconomicActivity_number' => 121, 'description_EconomicActivity' => 'Cultivo de frutas tropicales y subtropicales.'],
            ['EconomicActivity_number' => 122, 'description_EconomicActivity' => 'Cultivo de plátano y banano.'],
            ['EconomicActivity_number' => 123, 'description_EconomicActivity' => 'Cultivo de café.'],
            ['EconomicActivity_number' => 124, 'description_EconomicActivity' => 'Cultivo de caña de azúcar.'],
            ['EconomicActivity_number' => 125, 'description_EconomicActivity' => 'Cultivo de flor de corte.'],
            ['EconomicActivity_number' => 126, 'description_EconomicActivity' => 'Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos.'],
            ['EconomicActivity_number' => 127, 'description_EconomicActivity' => 'Cultivo de plantas con las que se preparan bebidas.'],
            ['EconomicActivity_number' => 128, 'description_EconomicActivity' => 'Cultivo de especias y de plantas aromáticas y medicinales.'],
            ['EconomicActivity_number' => 129, 'description_EconomicActivity' => 'Otros cultivos permanentes n.c.p.'],
            ['EconomicActivity_number' => 130, 'description_EconomicActivity' => 'Propagación de plantas (actividades de los viveros, excepto viveros forestales).'],
            ['EconomicActivity_number' => 131, 'description_EconomicActivity' => 'Preparación, hilatura, tejeduría y acabado de productos textiles.'],
            ['EconomicActivity_number' => 139, 'description_EconomicActivity' => 'Fabricación de otros productos textiles.'],
            ['EconomicActivity_number' => 141, 'description_EconomicActivity' => 'Cría de ganado bovino y bufalino.'],
            ['EconomicActivity_number' => 141, 'description_EconomicActivity' => 'Confección de prendas de vestir, excepto prendas de piel.'],
            ['EconomicActivity_number' => 142, 'description_EconomicActivity' => 'Cría de caballos y otros equinos.'],
            ['EconomicActivity_number' => 142, 'description_EconomicActivity' => 'Fabricación de artículos de piel.'],
            ['EconomicActivity_number' => 143, 'description_EconomicActivity' => 'Cría de ovejas y cabras.'],
            ['EconomicActivity_number' => 143, 'description_EconomicActivity' => 'Fabricación de artículos de punto y ganchillo.'],
            ['EconomicActivity_number' => 144, 'description_EconomicActivity' => 'Cría de ganado porcino.'],
            ['EconomicActivity_number' => 145, 'description_EconomicActivity' => 'Cría de aves de corral.'],
            ['EconomicActivity_number' => 149, 'description_EconomicActivity' => 'Cría de otros animales n.c.p.'],
            ['EconomicActivity_number' => 151, 'description_EconomicActivity' => 'Curtido y recurtido de cueros; fabricación de artículos de viaje, bolsos de mano y artículos similares, y fabricación de artículos de talabartería y guarnicionería, adobo y teñido de pieles.'],
            ['EconomicActivity_number' => 152, 'description_EconomicActivity' => 'Fabricación de calzado.'],
            ['EconomicActivity_number' => 161, 'description_EconomicActivity' => 'Actividades de apoyo a la agricultura.'],
            ['EconomicActivity_number' => 161, 'description_EconomicActivity' => 'Aserrado, acepillado e impregnación de la madera.'],
            ['EconomicActivity_number' => 162, 'description_EconomicActivity' => 'Actividades de apoyo a la ganadería.'],
            ['EconomicActivity_number' => 162, 'description_EconomicActivity' => 'Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles.'],
            ['EconomicActivity_number' => 163, 'description_EconomicActivity' => 'Actividades posteriores a la cosecha.'],
            ['EconomicActivity_number' => 163, 'description_EconomicActivity' => 'Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción.'],
            ['EconomicActivity_number' => 164, 'description_EconomicActivity' => 'Tratamiento de semillas para propagación.'],
            ['EconomicActivity_number' => 164, 'description_EconomicActivity' => 'Fabricación de recipientes de madera.'],
            ['EconomicActivity_number' => 169, 'description_EconomicActivity' => 'Fabricación de otros productos de madera; fabricación de artículos de cestería y espartería.'],
            ['EconomicActivity_number' => 170, 'description_EconomicActivity' => 'Fabricación de papel, cartón y productos de papel y cartón.'],
            ['EconomicActivity_number' => 181, 'description_EconomicActivity' => 'Actividades de impresión y actividades de servicios relacionados con la impresión'],
            ['EconomicActivity_number' => 182, 'description_EconomicActivity' => 'Producción de copias a partir de grabaciones originales.'],
            ['EconomicActivity_number' => 191, 'description_EconomicActivity' => 'Fabricación de productos de hornos de coque.'],
            ['EconomicActivity_number' => 192, 'description_EconomicActivity' => 'Fabricación de productos de la refinación del petróleo.'],
            ['EconomicActivity_number' => 201, 'description_EconomicActivity' => 'Fabricación de sustancias químicas básicas, abonos y compuestos inorgánicos nitrogenados, plásticos y caucho sintético en formas primarias.'],
            ['EconomicActivity_number' => 202, 'description_EconomicActivity' => 'Fabricación de otros productos químicos.'],
            ['EconomicActivity_number' => 203, 'description_EconomicActivity' => 'Fabricación de fibras sintéticas y artificiales.'],
            ['EconomicActivity_number' => 210, 'description_EconomicActivity' => 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico.'],
            ['EconomicActivity_number' => 221, 'description_EconomicActivity' => 'Fabricación de productos de caucho.'],
            ['EconomicActivity_number' => 222, 'description_EconomicActivity' => 'Fabricación de productos de plástico.'],
            ['EconomicActivity_number' => 231, 'description_EconomicActivity' => 'Fabricación de vidrio y productos de vidrio.'],
            ['EconomicActivity_number' => 239, 'description_EconomicActivity' => 'Fabricación de productos minerales no metálicos n.c.p.'],
            ['EconomicActivity_number' => 241, 'description_EconomicActivity' => 'Industrias básicas de hierro y de acero.'],
            ['EconomicActivity_number' => 242, 'description_EconomicActivity' => 'Industrias básicas de metales preciosos y de metales no ferrosos.'],
            ['EconomicActivity_number' => 243, 'description_EconomicActivity' => 'Fundición de metales.'],
            ['EconomicActivity_number' => 251, 'description_EconomicActivity' => 'Fabricación de productos metálicos para uso estructural, tanques, depósitos y generadores de vapor.'],
            ['EconomicActivity_number' => 252, 'description_EconomicActivity' => 'Fabricación de armas y municiones.'],
            ['EconomicActivity_number' => 259, 'description_EconomicActivity' => 'Fabricación de otros productos elaborados de metal y actividades de servicios relacionadas con el trabajo de metales.'],
            ['EconomicActivity_number' => 261, 'description_EconomicActivity' => 'Fabricación de componentes y tableros electrónicos.'],
            ['EconomicActivity_number' => 262, 'description_EconomicActivity' => 'Fabricación de computadoras y de equipo periférico.'],
            ['EconomicActivity_number' => 263, 'description_EconomicActivity' => 'Fabricación de equipos de comunicación.'],
            ['EconomicActivity_number' => 264, 'description_EconomicActivity' => 'Fabricación de aparatos electrónicos de consumo.'],
            ['EconomicActivity_number' => 265, 'description_EconomicActivity' => 'Fabricación de equipo de medición, prueba, navegación y control; fabricación de relojes.'],
            ['EconomicActivity_number' => 266, 'description_EconomicActivity' => 'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico.'],
            ['EconomicActivity_number' => 267, 'description_EconomicActivity' => 'Fabricación de instrumentos ópticos y equipo fotográfico.'],
            ['EconomicActivity_number' => 268, 'description_EconomicActivity' => 'Fabricación de medios magnéticos y ópticos para almacenamiento de datos'],
            ['EconomicActivity_number' => 271, 'description_EconomicActivity' => 'Fabricación de motores, generadores y transformadores eléctricos y de aparatos de distribución y control de la energía eléctrica.'],
            ['EconomicActivity_number' => 272, 'description_EconomicActivity' => 'Fabricación de pilas, baterías y acumuladores eléctricos.'],
            ['EconomicActivity_number' => 273, 'description_EconomicActivity' => 'Fabricación de hilos y cables aislados y sus dispositivos.'],
            ['EconomicActivity_number' => 274, 'description_EconomicActivity' => 'Fabricación de equipos eléctricos de iluminación.'],
            ['EconomicActivity_number' => 275, 'description_EconomicActivity' => 'Fabricación de aparatos de uso doméstico.'],
            ['EconomicActivity_number' => 279, 'description_EconomicActivity' => 'Fabricación de otros tipos de equipo eléctrico n.c.p.'],
            ['EconomicActivity_number' => 281, 'description_EconomicActivity' => 'Fabricación de maquinaria y equipo de uso general.'],
            ['EconomicActivity_number' => 282, 'description_EconomicActivity' => 'Fabricación de maquinaria y equipo de uso especial.'],
            ['EconomicActivity_number' => 291, 'description_EconomicActivity' => 'Fabricación de vehículos automotores y sus motores.'],
            ['EconomicActivity_number' => 292, 'description_EconomicActivity' => 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques.'],
            ['EconomicActivity_number' => 293, 'description_EconomicActivity' => 'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores.'],
            ['EconomicActivity_number' => 301, 'description_EconomicActivity' => 'Construcción de barcos y otras embarcaciones.'],
            ['EconomicActivity_number' => 302, 'description_EconomicActivity' => 'Fabricación de locomotoras y de material rodante para ferrocarriles.'],
            ['EconomicActivity_number' => 303, 'description_EconomicActivity' => 'Fabricación de aeronaves, naves espaciales y de maquinaria conexa.'],
            ['EconomicActivity_number' => 304, 'description_EconomicActivity' => 'Fabricación de vehículos militares de combate.'],
            ['EconomicActivity_number' => 309, 'description_EconomicActivity' => 'Fabricación de otros tipos de equipo de transporte n.c.p.'],
            ['EconomicActivity_number' => 311, 'description_EconomicActivity' => 'Pesca marítima.'],
            ['EconomicActivity_number' => 311, 'description_EconomicActivity' => 'Fabricación de muebles.'],
            ['EconomicActivity_number' => 312, 'description_EconomicActivity' => 'Pesca de agua dulce.'],
            ['EconomicActivity_number' => 312, 'description_EconomicActivity' => 'Fabricación de colchones y somieres.'],
            ['EconomicActivity_number' => 321, 'description_EconomicActivity' => 'Acuicultura marítima.'],
            ['EconomicActivity_number' => 321, 'description_EconomicActivity' => 'Fabricación de joyas, bisutería y artículos conexos.'],
            ['EconomicActivity_number' => 322, 'description_EconomicActivity' => 'Acuicultura de agua dulce.'],
            ['EconomicActivity_number' => 322, 'description_EconomicActivity' => 'Fabricación de instrumentos musicales.'],
            ['EconomicActivity_number' => 323, 'description_EconomicActivity' => 'Fabricación de artículos y equipo para la práctica del deporte.'],
            ['EconomicActivity_number' => 324, 'description_EconomicActivity' => 'Fabricación de juegos, juguetes y rompecabezas.'],
            ['EconomicActivity_number' => 325, 'description_EconomicActivity' => 'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario).'],
            ['EconomicActivity_number' => 329, 'description_EconomicActivity' => 'Otras industrias manufactureras n.c.p.'],
            ['EconomicActivity_number' => 331, 'description_EconomicActivity' => 'Mantenimiento y reparación especializado de productos elaborados en metal y de maquinaria y equipo.'],
            ['EconomicActivity_number' => 332, 'description_EconomicActivity' => 'Instalación especializada de maquinaria y equipo industrial.'],
            ['EconomicActivity_number' => 351, 'description_EconomicActivity' => 'Generación, transmisión, distribución y comercialización de energía eléctrica'],
            ['EconomicActivity_number' => 352, 'description_EconomicActivity' => 'Producción de gas; distribución de combustibles gaseosos por tuberías.'],
            ['EconomicActivity_number' => 353, 'description_EconomicActivity' => 'Suministro de vapor y aire acondicionado.'],
            ['EconomicActivity_number' => 360, 'description_EconomicActivity' => 'Captación, tratamiento y distribución de agua.'],
            ['EconomicActivity_number' => 381, 'description_EconomicActivity' => 'Recolección de desechos.'],
            ['EconomicActivity_number' => 382, 'description_EconomicActivity' => 'Tratamiento y disposición de desechos.'],
            ['EconomicActivity_number' => 383, 'description_EconomicActivity' => 'Recuperación de materiales.'],
            ['EconomicActivity_number' => 411, 'description_EconomicActivity' => 'Construcción de edificios.'],
            ['EconomicActivity_number' => 421, 'description_EconomicActivity' => 'Construcción de carreteras y vías de ferrocarril.'],
            ['EconomicActivity_number' => 422, 'description_EconomicActivity' => 'Construcción de proyectos de servicio público.'],
            ['EconomicActivity_number' => 429, 'description_EconomicActivity' => 'Construcción de otras obras de ingeniería civil.'],
            ['EconomicActivity_number' => 431, 'description_EconomicActivity' => 'Demolición y preparación del terreno.'],
            ['EconomicActivity_number' => 432, 'description_EconomicActivity' => 'Instalaciones eléctricas, de fontanería y otras instalaciones especializadas.'],
            ['EconomicActivity_number' => 433, 'description_EconomicActivity' => 'Terminación y acabado de edificios y obras de ingeniería civil.'],
            ['EconomicActivity_number' => 439, 'description_EconomicActivity' => 'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil.'],
            ['EconomicActivity_number' => 451, 'description_EconomicActivity' => 'Comercio de vehículos automotores.'],
            ['EconomicActivity_number' => 452, 'description_EconomicActivity' => 'Mantenimiento y reparación de vehículos automotores.'],
            ['EconomicActivity_number' => 453, 'description_EconomicActivity' => 'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores.'],
            ['EconomicActivity_number' => 454, 'description_EconomicActivity' => 'Comercio, mantenimiento y reparación de motocicletas y de sus partes, piezas y accesorios.'],
            ['EconomicActivity_number' => 461, 'description_EconomicActivity' => 'Comercio al por mayor a cambio de una retribución o por contrata.'],
            ['EconomicActivity_number' => 462, 'description_EconomicActivity' => 'Comercio al por mayor de materias primas agropecuarias; animales vivos'],
            ['EconomicActivity_number' => 463, 'description_EconomicActivity' => 'Comercio al por mayor de alimentos, bebidas y tabaco.'],
            ['EconomicActivity_number' => 464, 'description_EconomicActivity' => 'Comercio al por mayor de artículos y enseres domésticos (incluidas prendas de vestir).'],
            ['EconomicActivity_number' => 465, 'description_EconomicActivity' => 'Comercio al por mayor de maquinaria y equipo.'],
            ['EconomicActivity_number' => 466, 'description_EconomicActivity' => 'Comercio al por mayor especializado de otros productos.'],
            ['EconomicActivity_number' => 469, 'description_EconomicActivity' => 'Comercio al por mayor no especializado.'],
            ['EconomicActivity_number' => 471, 'description_EconomicActivity' => 'Comercio al por menor en establecimientos no especializados.'],
            ['EconomicActivity_number' => 472, 'description_EconomicActivity' => 'Comercio al por menor de alimentos (víveres en general), bebidas y tabaco, en establecimientos especializados.'],
            ['EconomicActivity_number' => 473, 'description_EconomicActivity' => 'Comercio al por menor de combustible, lubricantes, aditivos y productos de limpieza para automotores, en establecimientos especializados.'],
            ['EconomicActivity_number' => 474, 'description_EconomicActivity' => 'Comercio al por menor de equipos de informática y de comunicaciones, en establecimientos especializados.'],
            ['EconomicActivity_number' => 475, 'description_EconomicActivity' => 'Comercio al por menor de otros enseres domésticos en establecimientos especializados.'],
            ['EconomicActivity_number' => 476, 'description_EconomicActivity' => 'Comercio al por menor de artículos culturales y de entretenimiento, en establecimientos especializados.'],
            ['EconomicActivity_number' => 477, 'description_EconomicActivity' => 'Comercio al por menor de otros productos en establecimientos especializados.'],
            ['EconomicActivity_number' => 478, 'description_EconomicActivity' => 'Comercio al por menor en puestos de venta móviles.'],
            ['EconomicActivity_number' => 479, 'description_EconomicActivity' => 'Comercio al por menor no realizado en establecimientos, puestos de venta o mercados.'],
            ['EconomicActivity_number' => 491, 'description_EconomicActivity' => 'Transporte férreo.'],
            ['EconomicActivity_number' => 492, 'description_EconomicActivity' => 'Transporte terrestre público automotor.'],
            ['EconomicActivity_number' => 493, 'description_EconomicActivity' => 'Transporte por tuberías.'],
            ['EconomicActivity_number' => 501, 'description_EconomicActivity' => 'Transporte marítimo y de cabotaje.'],
            ['EconomicActivity_number' => 502, 'description_EconomicActivity' => 'Transporte fluvial.'],
            ['EconomicActivity_number' => 511, 'description_EconomicActivity' => 'Transporte aéreo de pasajeros.'],
            ['EconomicActivity_number' => 512, 'description_EconomicActivity' => 'Transporte aéreo de carga.'],
            ['EconomicActivity_number' => 521, 'description_EconomicActivity' => 'Almacenamiento y depósito.'],
            ['EconomicActivity_number' => 522, 'description_EconomicActivity' => 'Actividades de las estaciones, vías y servicios complementarios para el transporte.'],
            ['EconomicActivity_number' => 531, 'description_EconomicActivity' => 'Actividades postales nacionales.'],
            ['EconomicActivity_number' => 532, 'description_EconomicActivity' => 'Actividades de mensajería.'],
            ['EconomicActivity_number' => 551, 'description_EconomicActivity' => 'Actividades de alojamiento de estancias cortas.'],
            ['EconomicActivity_number' => 553, 'description_EconomicActivity' => 'Servicio por horas.'],
            ['EconomicActivity_number' => 559, 'description_EconomicActivity' => 'Otros tipos de alojamiento n.c.p.'],
            ['EconomicActivity_number' => 561, 'description_EconomicActivity' => 'Actividades de restaurantes, cafeterías y servicio móvil de comidas.'],
            ['EconomicActivity_number' => 562, 'description_EconomicActivity' => 'ctividades de catering para eventos y otros servicios de comidas.'],
            ['EconomicActivity_number' => 563, 'description_EconomicActivity' => 'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento.'],
            ['EconomicActivity_number' => 581, 'description_EconomicActivity' => 'Edición de libros, publicaciones periódicas y otras actividades de edición.'],
            ['EconomicActivity_number' => 582, 'description_EconomicActivity' => 'dición de programas de informática (software).'],
            ['EconomicActivity_number' => 591, 'description_EconomicActivity' => 'ctividades de producción de películas cinematográficas, video y producción de programas, anuncios y comerciales de televisión.'],
            ['EconomicActivity_number' => 592, 'description_EconomicActivity' => 'Actividades de grabación de sonido y edición de música.'],
            ['EconomicActivity_number' => 601, 'description_EconomicActivity' => 'Actividades de programación y transmisión en el servicio de radiodifusión sonora.'],
            ['EconomicActivity_number' => 602, 'description_EconomicActivity' => 'Actividades de programación y transmisión de televisión.'],
            ['EconomicActivity_number' => 611, 'description_EconomicActivity' => 'Actividades de telecomunicaciones alámbricas.'],
            ['EconomicActivity_number' => 612, 'description_EconomicActivity' => 'Actividades de telecomunicaciones inalámbricas.'],
            ['EconomicActivity_number' => 613, 'description_EconomicActivity' => 'Actividades de telecomunicación satelital.'],
            ['EconomicActivity_number' => 619, 'description_EconomicActivity' => 'Otras actividades de telecomunicaciones.'],
            ['EconomicActivity_number' => 620, 'description_EconomicActivity' => 'Desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas), consultoría informática y actividades relacionadas.'],
            ['EconomicActivity_number' => 639, 'description_EconomicActivity' => 'Otras actividades de servicio de información.'],
            ['EconomicActivity_number' => 641, 'description_EconomicActivity' => 'Intermediación monetaria.'],
            ['EconomicActivity_number' => 642, 'description_EconomicActivity' => 'Otros tipos de intermediación monetaria.'],
            ['EconomicActivity_number' => 643, 'description_EconomicActivity' => 'Fideicomisos, fondos (incluye fondos de cesantías) y entidades financieras similares.'],
            ['EconomicActivity_number' => 649, 'description_EconomicActivity' => 'Otras actividades de servicio financiero, excepto las de seguros y pensiones'],
            ['EconomicActivity_number' => 651, 'description_EconomicActivity' => 'Seguros y capitalización.'],
            ['EconomicActivity_number' => 652, 'description_EconomicActivity' => 'Servicios de seguros sociales de salud y riesgos profesionales.'],
            ['EconomicActivity_number' => 653, 'description_EconomicActivity' => 'Servicios de seguros sociales de pensiones.'],
            ['EconomicActivity_number' => 661, 'description_EconomicActivity' => 'Actividades auxiliares de las actividades de servicios financieros, excepto las de seguros y pensiones.'],
            ['EconomicActivity_number' => 662, 'description_EconomicActivity' => 'Actividades de servicios auxiliares de los servicios de seguros y pensiones.'],
            ['EconomicActivity_number' => 663, 'description_EconomicActivity' => 'Actividades de administración de fondos.'],
            ['EconomicActivity_number' => 681, 'description_EconomicActivity' => 'Actividades inmobiliarias realizadas con bienes propios o arrendados.'],
            ['EconomicActivity_number' => 682, 'description_EconomicActivity' => 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata.'],
            ['EconomicActivity_number' => 691, 'description_EconomicActivity' => 'Actividades jurídicas.'],
            ['EconomicActivity_number' => 692, 'description_EconomicActivity' => 'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria.'],
            ['EconomicActivity_number' => 711, 'description_EconomicActivity' => 'Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica.'],
            ['EconomicActivity_number' => 712, 'description_EconomicActivity' => 'Ensayos y análisis técnicos.'],
            ['EconomicActivity_number' => 721, 'description_EconomicActivity' => 'Extracción de minerales de uranio y de torio.'],
            ['EconomicActivity_number' => 721, 'description_EconomicActivity' => 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería.'],
            ['EconomicActivity_number' => 722, 'description_EconomicActivity' => 'Extracción de oro y otros metales preciosos.'],
            ['EconomicActivity_number' => 722, 'description_EconomicActivity' => 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades.'],
            ['EconomicActivity_number' => 723, 'description_EconomicActivity' => 'Extracción de minerales de níquel.'],
            ['EconomicActivity_number' => 729, 'description_EconomicActivity' => 'Extracción de otros minerales metalíferos no ferrosos n.c.p.'],
            ['EconomicActivity_number' => 731, 'description_EconomicActivity' => 'Publicidad.'],
            ['EconomicActivity_number' => 732, 'description_EconomicActivity' => 'Estudios de mercado y realización de encuestas de opinión pública.'],
            ['EconomicActivity_number' => 741, 'description_EconomicActivity' => 'Actividades especializadas de diseño.'],
            ['EconomicActivity_number' => 742, 'description_EconomicActivity' => 'Actividades de fotografía.'],
            ['EconomicActivity_number' => 749, 'description_EconomicActivity' => 'Otras actividades profesionales, científicas y técnicas n.c.p.'],
            ['EconomicActivity_number' => 750, 'description_EconomicActivity' => 'Actividades veterinarias.'],
            ['EconomicActivity_number' => 771, 'description_EconomicActivity' => 'Alquiler y arrendamiento de vehículos automotores.'],
            ['EconomicActivity_number' => 772, 'description_EconomicActivity' => 'Alquiler y arrendamiento de efectos personales y enseres domésticos.'],
            ['EconomicActivity_number' => 773, 'description_EconomicActivity' => 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.'],
            ['EconomicActivity_number' => 774, 'description_EconomicActivity' => 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor.'],
            ['EconomicActivity_number' => 781, 'description_EconomicActivity' => 'Actividades de agencias de empleo.'],
            ['EconomicActivity_number' => 782, 'description_EconomicActivity' => 'Actividades de agencias de empleo temporal.'],
            ['EconomicActivity_number' => 783, 'description_EconomicActivity' => 'Otras actividades de suministro de recurso humano.'],
            ['EconomicActivity_number' => 791, 'description_EconomicActivity' => 'Actividades de las agencias de viajes y operadores turísticos.'],
            ['EconomicActivity_number' => 799, 'description_EconomicActivity' => 'Otros servicios de reserva y actividades relacionadas.'],
            ['EconomicActivity_number' => 801, 'description_EconomicActivity' => 'Actividades de seguridad privada.'],
            ['EconomicActivity_number' => 802, 'description_EconomicActivity' => 'Actividades de servicios de sistemas de seguridad.'],
            ['EconomicActivity_number' => 803, 'description_EconomicActivity' => 'Actividades de detectives e investigadores privados.'],
            ['EconomicActivity_number' => 811, 'description_EconomicActivity' => 'Extracción de piedra, arena, arcillas comunes, yeso y anhidrita.'],
            ['EconomicActivity_number' => 811, 'description_EconomicActivity' => 'Actividades combinadas de apoyo a instalaciones.'],
            ['EconomicActivity_number' => 812, 'description_EconomicActivity' => 'Extracción de arcillas de uso industrial, caliza, caolín y bentonitas.'],
            ['EconomicActivity_number' => 812, 'description_EconomicActivity' => 'Actividades de limpieza.'],
            ['EconomicActivity_number' => 813, 'description_EconomicActivity' => 'Actividades de paisajismo y servicios de mantenimiento conexos.'],
            ['EconomicActivity_number' => 821, 'description_EconomicActivity' => 'Actividades administrativas y de apoyo de oficina.'],
            ['EconomicActivity_number' => 822, 'description_EconomicActivity' => 'Actividades de centros de llamadas (Call center).'],
            ['EconomicActivity_number' => 823, 'description_EconomicActivity' => 'Organización de convenciones y eventos comerciales.'],
            ['EconomicActivity_number' => 829, 'description_EconomicActivity' => 'Actividades de servicios de apoyo a las empresas n.c.p.'],
            ['EconomicActivity_number' => 841, 'description_EconomicActivity' => 'Administración del Estado y aplicación de la política económica y social de la comunidad.'],
            ['EconomicActivity_number' => 842, 'description_EconomicActivity' => 'Prestación de servicios a la comunidad en general.'],
            ['EconomicActivity_number' => 843, 'description_EconomicActivity' => 'Actividades de planes de seguridad social de afiliación obligatoria.'],
            ['EconomicActivity_number' => 851, 'description_EconomicActivity' => 'Educación de la primera infancia, preescolar y básica primaria.'],
            ['EconomicActivity_number' => 852, 'description_EconomicActivity' => 'Educación secundaria y de formación laboral.'],
            ['EconomicActivity_number' => 853, 'description_EconomicActivity' => 'Establecimientos que combinan diferentes niveles de educación.'],
            ['EconomicActivity_number' => 854, 'description_EconomicActivity' => 'Educación superior.'],
            ['EconomicActivity_number' => 855, 'description_EconomicActivity' => 'Otros tipos de educación.'],
            ['EconomicActivity_number' => 856, 'description_EconomicActivity' => 'Actividades de apoyo a la educación.'],
            ['EconomicActivity_number' => 861, 'description_EconomicActivity' => 'Actividades de hospitales y clínicas, con internación.'],
            ['EconomicActivity_number' => 862, 'description_EconomicActivity' => 'Actividades de práctica médica y odontológica, sin internación.'],
            ['EconomicActivity_number' => 869, 'description_EconomicActivity' => 'Otras actividades de atención relacionadas con la salud humana.'],
            ['EconomicActivity_number' => 871, 'description_EconomicActivity' => 'Actividades de atención residencial medicalizada de tipo general.'],
            ['EconomicActivity_number' => 872, 'description_EconomicActivity' => 'Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas.'],
            ['EconomicActivity_number' => 873, 'description_EconomicActivity' => 'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas.'],
            ['EconomicActivity_number' => 879, 'description_EconomicActivity' => 'Otras actividades de atención en instituciones con alojamiento.'],
            ['EconomicActivity_number' => 881, 'description_EconomicActivity' => 'Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas.'],
            ['EconomicActivity_number' => 889, 'description_EconomicActivity' => 'Otras actividades de asistencia social sin alojamiento.'],
            ['EconomicActivity_number' => 891, 'description_EconomicActivity' => 'Extracción de minerales para la fabricación de abonos y productos químicos.'],
            ['EconomicActivity_number' => 892, 'description_EconomicActivity' => 'Extracción de halita (sal).'],
            ['EconomicActivity_number' => 900, 'description_EconomicActivity' => 'Actividades creativas, artísticas y de entretenimiento.'],
            ['EconomicActivity_number' => 910, 'description_EconomicActivity' => 'Actividades de bibliotecas, archivos, museos y otras actividades culturales.'],
            ['EconomicActivity_number' => 920, 'description_EconomicActivity' => 'Actividades de juegos de azar y apuestas.'],
            ['EconomicActivity_number' => 931, 'description_EconomicActivity' => 'Actividades deportivas.'],
            ['EconomicActivity_number' => 932, 'description_EconomicActivity' => 'Otras actividades recreativas y de esparcimiento.'],
            ['EconomicActivity_number' => 941, 'description_EconomicActivity' => 'Actividades de asociaciones empresariales y de empleadores, y asociaciones profesionales.'],
            ['EconomicActivity_number' => 942, 'description_EconomicActivity' => 'Actividades de sindicatos de empleados.'],
            ['EconomicActivity_number' => 949, 'description_EconomicActivity' => 'Actividades de otras asociaciones.'],
            ['EconomicActivity_number' => 951, 'description_EconomicActivity' => 'Mantenimiento y reparación de computadores y equipo de comunicaciones.'],
            ['EconomicActivity_number' => 960, 'description_EconomicActivity' => 'Otras actividades de servicios personales.'],
            ['EconomicActivity_number' => 970, 'description_EconomicActivity' => 'Actividades de los hogares individuales como empleadores de personal doméstico.'],
            ['EconomicActivity_number' => 981, 'description_EconomicActivity' => 'Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio.'],
            ['EconomicActivity_number' => 982, 'description_EconomicActivity' => 'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio.'],
            ['EconomicActivity_number' => 990, 'description_EconomicActivity' => 'Actividades de apoyo para otras actividades de explotación de minas y canteras.'],
            ['EconomicActivity_number' => 1011, 'description_EconomicActivity' => 'Procesamiento y conservación de carne y productos cárnicos.'],
            ['EconomicActivity_number' => 1012, 'description_EconomicActivity' => 'Procesamiento y conservación de pescados, crustáceos y moluscos.'],
            ['EconomicActivity_number' => 1020, 'description_EconomicActivity' => 'Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos.'],
            ['EconomicActivity_number' => 1051, 'description_EconomicActivity' => 'Elaboración de productos de molinería.'],
            ['EconomicActivity_number' => 1052, 'description_EconomicActivity' => 'Elaboración de almidones y productos derivados del almidón.'],
            ['EconomicActivity_number' => 1061, 'description_EconomicActivity' => 'Trilla de café.'],
            ['EconomicActivity_number' => 1062, 'description_EconomicActivity' => 'Descafeinado, tostión y molienda del café.'],
            ['EconomicActivity_number' => 1063, 'description_EconomicActivity' => 'Otros derivados del café.'],
            ['EconomicActivity_number' => 1071, 'description_EconomicActivity' => 'Elaboración y refinación de azúcar.'],
            ['EconomicActivity_number' => 1072, 'description_EconomicActivity' => 'Elaboración de panela.'],
            ['EconomicActivity_number' => 1081, 'description_EconomicActivity' => 'Elaboración de productos de panadería.'],
            ['EconomicActivity_number' => 1082, 'description_EconomicActivity' => 'Elaboración de cacao, chocolate y productos de confitería.'],
            ['EconomicActivity_number' => 1083, 'description_EconomicActivity' => 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares.'],
            ['EconomicActivity_number' => 1084, 'description_EconomicActivity' => 'Elaboración de comidas y platos preparados.'],
            ['EconomicActivity_number' => 1089, 'description_EconomicActivity' => 'Elaboración de otros productos alimenticios n.c.p.'],
            ['EconomicActivity_number' => 1101, 'description_EconomicActivity' => 'Destilación, rectificación y mezcla de bebidas alcohólicas.'],
            ['EconomicActivity_number' => 1102, 'description_EconomicActivity' => 'Elaboración de bebidas fermentadas no destiladas.'],
            ['EconomicActivity_number' => 1103, 'description_EconomicActivity' => 'Producción de malta, elaboración de cervezas y otras bebidas malteadas.'],
            ['EconomicActivity_number' => 1104, 'description_EconomicActivity' => 'Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas.'],
            ['EconomicActivity_number' => 1311, 'description_EconomicActivity' => 'Preparación e hilatura de fibras textiles.'],
            ['EconomicActivity_number' => 1312, 'description_EconomicActivity' => 'Tejeduría de productos textiles.'],
            ['EconomicActivity_number' => 1313, 'description_EconomicActivity' => 'Acabado de productos textiles.'],
            ['EconomicActivity_number' => 1391, 'description_EconomicActivity' => 'Fabricación de tejidos de punto y ganchillo.'],
            ['EconomicActivity_number' => 1392, 'description_EconomicActivity' => 'Confección de artículos con materiales textiles, excepto prendas de vestir.'],
            ['EconomicActivity_number' => 1393, 'description_EconomicActivity' => 'Fabricación de tapetes y alfombras para pisos.'],
            ['EconomicActivity_number' => 1394, 'description_EconomicActivity' => 'Fabricación de cuerdas, cordeles, cables, bramantes y redes.'],
            ['EconomicActivity_number' => 1399, 'description_EconomicActivity' => 'Fabricación de otros artículos textiles n.c.p.'],
            ['EconomicActivity_number' => 1511, 'description_EconomicActivity' => 'Curtido y recurtido de cueros; recurtido y teñido de pieles.'],
            ['EconomicActivity_number' => 1512, 'description_EconomicActivity' => 'Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería.'],
            ['EconomicActivity_number' => 1521, 'description_EconomicActivity' => 'Fabricación de calzado de cuero y piel, con cualquier tipo de suela.'],
            ['EconomicActivity_number' => 1522, 'description_EconomicActivity' => 'Fabricación de otros tipos de calzado, excepto calzado de cuero y piel.'],
            ['EconomicActivity_number' => 1523, 'description_EconomicActivity' => 'Fabricación de partes del calzado.'],
            ['EconomicActivity_number' => 1701, 'description_EconomicActivity' => 'Fabricación de pulpas (pastas) celulósicas; papel y cartón.'],
            ['EconomicActivity_number' => 1702, 'description_EconomicActivity' => 'Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón.'],
            ['EconomicActivity_number' => 1709, 'description_EconomicActivity' => 'Fabricación de otros artículos de papel y cartón.'],
            ['EconomicActivity_number' => 1811, 'description_EconomicActivity' => 'Actividades de impresión.'],
            ['EconomicActivity_number' => 1812, 'description_EconomicActivity' => 'Actividades de servicios relacionados con la impresión.'],
            ['EconomicActivity_number' => 1922, 'description_EconomicActivity' => 'Actividad de mezcla de combustibles.'],
            ['EconomicActivity_number' => 2011, 'description_EconomicActivity' => 'Fabricación de sustancias y productos químicos básicos.'],
            ['EconomicActivity_number' => 2012, 'description_EconomicActivity' => 'Fabricación de abonos y compuestos inorgánicos nitrogenados.'],
            ['EconomicActivity_number' => 2013, 'description_EconomicActivity' => 'Fabricación de plásticos en formas primarias.'],
            ['EconomicActivity_number' => 2014, 'description_EconomicActivity' => 'Fabricación de caucho sintético en formas primarias.'],
            ['EconomicActivity_number' => 2021, 'description_EconomicActivity' => 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario.'],
            ['EconomicActivity_number' => 2022, 'description_EconomicActivity' => 'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas.'],
            ['EconomicActivity_number' => 2023, 'description_EconomicActivity' => 'Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador.'],
            ['EconomicActivity_number' => 2029, 'description_EconomicActivity' => 'perfumes y preparados de tocador. Fabricación de otros productos químicos n.c.p.'],
            ['EconomicActivity_number' => 2211, 'description_EconomicActivity' => 'Fabricación de llantas y neumáticos de caucho'],
            ['EconomicActivity_number' => 2212, 'description_EconomicActivity' => 'Reencauche de llantas usadas'],
            ['EconomicActivity_number' => 2219, 'description_EconomicActivity' => 'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.'],
            ['EconomicActivity_number' => 2221, 'description_EconomicActivity' => 'Fabricación de formas básicas de plástico.'],
            ['EconomicActivity_number' => 2229, 'description_EconomicActivity' => 'Fabricación de artículos de plástico n.c.p.'],
            ['EconomicActivity_number' => 2391, 'description_EconomicActivity' => 'Fabricación de productos refractarios.'],
            ['EconomicActivity_number' => 2392, 'description_EconomicActivity' => 'Fabricación de materiales de arcilla para la construcción.'],
            ['EconomicActivity_number' => 2393, 'description_EconomicActivity' => 'Fabricación de otros productos de cerámica y porcelana.'],
            ['EconomicActivity_number' => 2394, 'description_EconomicActivity' => 'Fabricación de cemento, cal y yeso.'],
            ['EconomicActivity_number' => 2395, 'description_EconomicActivity' => 'Fabricación de artículos de hormigón, cemento y yeso.'],
            ['EconomicActivity_number' => 2396, 'description_EconomicActivity' => 'Corte, tallado y acabado de la piedra.'],
            ['EconomicActivity_number' => 2399, 'description_EconomicActivity' => 'Fabricación de otros productos minerales no metálicos n.c.p.'],
            ['EconomicActivity_number' => 2421, 'description_EconomicActivity' => 'Industrias básicas de metales preciosos.'],
            ['EconomicActivity_number' => 2429, 'description_EconomicActivity' => 'Industrias básicas de otros metales no ferrosos.'],
            ['EconomicActivity_number' => 2431, 'description_EconomicActivity' => 'Fundición de hierro y de acero.'],
            ['EconomicActivity_number' => 2432, 'description_EconomicActivity' => 'Fundición de metales no ferrosos.'],
            ['EconomicActivity_number' => 2511, 'description_EconomicActivity' => 'Fabricación de productos metálicos para uso estructural.'],
            ['EconomicActivity_number' => 2512, 'description_EconomicActivity' => 'Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías.'],
            ['EconomicActivity_number' => 2513, 'description_EconomicActivity' => 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central,'],
            ['EconomicActivity_number' => 2591, 'description_EconomicActivity' => 'Forja, prensado, estampado y laminado de metal; pulvimetalurgia.'],
            ['EconomicActivity_number' => 2592, 'description_EconomicActivity' => 'Tratamiento y revestimiento de metales; mecanizado.'],
            ['EconomicActivity_number' => 2593, 'description_EconomicActivity' => 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería.'],
            ['EconomicActivity_number' => 2599, 'description_EconomicActivity' => 'Fabricación de otros productos laborados de metal n.c.p.'],
            ['EconomicActivity_number' => 2651, 'description_EconomicActivity' => 'abricación de equipo de medición, prueba, navegación y control'],
            ['EconomicActivity_number' => 2652, 'description_EconomicActivity' => 'Fabricación de relojes.'],
            ['EconomicActivity_number' => 2680, 'description_EconomicActivity' => 'Fabricación de medios magnéticos y ópticos para almacenamiento de datos.'],
            ['EconomicActivity_number' => 2711, 'description_EconomicActivity' => 'Fabricación de motores, generadores y transformadores eléctricos.'],
            ['EconomicActivity_number' => 2712, 'description_EconomicActivity' => 'Fabricación de aparatos de distribución y control de la energía eléctrica.'],
            ['EconomicActivity_number' => 2731, 'description_EconomicActivity' => 'Fabricación de hilos y cables eléctricos y de fibra óptica.'],
            ['EconomicActivity_number' => 2732, 'description_EconomicActivity' => 'Fabricación de dispositivos de cableado.'],
            ['EconomicActivity_number' => 2811, 'description_EconomicActivity' => 'Fabricación de motores, turbinas, y partes para motores de combustión interna.'],
            ['EconomicActivity_number' => 2812, 'description_EconomicActivity' => 'Fabricación de equipos de potencia hidráulica y neumática.'],
            ['EconomicActivity_number' => 2813, 'description_EconomicActivity' => 'Fabricación de otras bombas, compresores, grifos y válvulas.'],
            ['EconomicActivity_number' => 2814, 'description_EconomicActivity' => 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión'],
            ['EconomicActivity_number' => 2815, 'description_EconomicActivity' => 'Fabricación de hornos, hogares y quemadores industriales.'],
            ['EconomicActivity_number' => 2816, 'description_EconomicActivity' => 'Fabricación de equipo de elevación y manipulación.'],
            ['EconomicActivity_number' => 2817, 'description_EconomicActivity' => 'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico).'],
            ['EconomicActivity_number' => 2818, 'description_EconomicActivity' => 'Fabricación de herramientas manuales con motor.'],
            ['EconomicActivity_number' => 2819, 'description_EconomicActivity' => 'Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.'],
            ['EconomicActivity_number' => 2821, 'description_EconomicActivity' => 'Fabricación de maquinaria agropecuaria y forestal.'],
            ['EconomicActivity_number' => 2822, 'description_EconomicActivity' => 'Fabricación de máquinas formadoras de metal y de máquinas herramienta.'],
            ['EconomicActivity_number' => 2823, 'description_EconomicActivity' => 'Fabricación de maquinaria para la metalurgia.'],
            ['EconomicActivity_number' => 2824, 'description_EconomicActivity' => 'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción.'],
            ['EconomicActivity_number' => 2825, 'description_EconomicActivity' => 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco'],
            ['EconomicActivity_number' => 2826, 'description_EconomicActivity' => 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros.'],
            ['EconomicActivity_number' => 2829, 'description_EconomicActivity' => 'Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.'],
            ['EconomicActivity_number' => 3011, 'description_EconomicActivity' => 'Construcción de barcos y de estructuras flotantes.'],
            ['EconomicActivity_number' => 3012, 'description_EconomicActivity' => 'Construcción de embarcaciones de recreo y deporte.'],
            ['EconomicActivity_number' => 3091, 'description_EconomicActivity' => 'Fabricación de motocicletas.'],
            ['EconomicActivity_number' => 3092, 'description_EconomicActivity' => 'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad.'],
            ['EconomicActivity_number' => 3311, 'description_EconomicActivity' => 'Mantenimiento y reparación especializado de productos elaborados en metal.'],
            ['EconomicActivity_number' => 3312, 'description_EconomicActivity' => 'Mantenimiento y reparación especializado de maquinaria y equipo.'],
            ['EconomicActivity_number' => 3313, 'description_EconomicActivity' => 'Mantenimiento y reparación especializado de equipo electrónico y óptico.'],
            ['EconomicActivity_number' => 3314, 'description_EconomicActivity' => 'Mantenimiento y reparación especializado de equipo eléctrico.'],
            ['EconomicActivity_number' => 3315, 'description_EconomicActivity' => 'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas.'],
            ['EconomicActivity_number' => 3319, 'description_EconomicActivity' => 'Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.'],
            ['EconomicActivity_number' => 3511, 'description_EconomicActivity' => 'Generación de energía eléctrica.'],
            ['EconomicActivity_number' => 3512, 'description_EconomicActivity' => 'Transmisión de energía eléctrica.'],
            ['EconomicActivity_number' => 3513, 'description_EconomicActivity' => 'Distribución de energía eléctrica.'],
            ['EconomicActivity_number' => 3514, 'description_EconomicActivity' => 'Comercialización de energía eléctrica.'],
            ['EconomicActivity_number' => 3811, 'description_EconomicActivity' => 'Recolección de desechos no peligrosos.'],
            ['EconomicActivity_number' => 3812, 'description_EconomicActivity' => 'Recolección de desechos peligrosos.'],
            ['EconomicActivity_number' => 3821, 'description_EconomicActivity' => 'Tratamiento y disposición de desechos no peligrosos.'],
            ['EconomicActivity_number' => 3822, 'description_EconomicActivity' => 'Tratamiento y disposición de desechos peligrosos.'],
            ['EconomicActivity_number' => 3900, 'description_EconomicActivity' => 'Actividades de saneamiento ambiental y otros servicios de gestión de desechos.'],
            ['EconomicActivity_number' => 4111, 'description_EconomicActivity' => 'Construcción de edificios residenciales.'],
            ['EconomicActivity_number' => 4112, 'description_EconomicActivity' => 'Construcción de edificios no residenciales.'],
            ['EconomicActivity_number' => 4311, 'description_EconomicActivity' => 'Demolición.'],
            ['EconomicActivity_number' => 4312, 'description_EconomicActivity' => 'Preparación del terreno.'],
            ['EconomicActivity_number' => 4321, 'description_EconomicActivity' => 'Instalaciones eléctricas.'],
            ['EconomicActivity_number' => 4322, 'description_EconomicActivity' => 'Instalaciones de fontanería, calefacción y aire acondicionado.'],
            ['EconomicActivity_number' => 4329, 'description_EconomicActivity' => 'Otras instalaciones especializadas.'],
            ['EconomicActivity_number' => 4511, 'description_EconomicActivity' => 'Comercio de vehículos automotores nuevos.'],
            ['EconomicActivity_number' => 4512, 'description_EconomicActivity' => 'Comercio de vehículos automotores usados.'],
            ['EconomicActivity_number' => 4530, 'description_EconomicActivity' => 'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores'],
            ['EconomicActivity_number' => 4541, 'description_EconomicActivity' => 'Comercio de motocicletas y de sus partes, piezas y accesorios.'],
            ['EconomicActivity_number' => 4542, 'description_EconomicActivity' => 'Mantenimiento y reparación de motocicletas y de sus partes y piezas.'],
            ['EconomicActivity_number' => 4620, 'description_EconomicActivity' => 'Comercio al por mayor de materias primas agropecuarias; animales vivos.'],
            ['EconomicActivity_number' => 4631, 'description_EconomicActivity' => 'Comercio al por mayor de productos alimenticios.'],
            ['EconomicActivity_number' => 4632, 'description_EconomicActivity' => 'Comercio al por mayor de bebidas y tabaco.'],
            ['EconomicActivity_number' => 4641, 'description_EconomicActivity' => 'Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico.'],
            ['EconomicActivity_number' => 4642, 'description_EconomicActivity' => 'Comercio al por mayor de prendas de vestir.'],
            ['EconomicActivity_number' => 4643, 'description_EconomicActivity' => 'Comercio al por mayor de calzado.'],
            ['EconomicActivity_number' => 4644, 'description_EconomicActivity' => 'Comercio al por mayor de aparatos y equipo de uso doméstico.'],
            ['EconomicActivity_number' => 4645, 'description_EconomicActivity' => 'Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador.'],
            ['EconomicActivity_number' => 4649, 'description_EconomicActivity' => 'Comercio al por mayor de otros utensilios domésticos n.c.p.'],
            ['EconomicActivity_number' => 4651, 'description_EconomicActivity' => 'Comercio al por mayor de computadores, equipo periférico y programas de informática.'],
            ['EconomicActivity_number' => 4652, 'description_EconomicActivity' => 'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones.'],
            ['EconomicActivity_number' => 4653, 'description_EconomicActivity' => 'Comercio al por mayor de maquinaria y equipo agropecuarios.'],
            ['EconomicActivity_number' => 4659, 'description_EconomicActivity' => 'Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.'],
            ['EconomicActivity_number' => 4661, 'description_EconomicActivity' => 'Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos.'],
            ['EconomicActivity_number' => 4662, 'description_EconomicActivity' => 'Comercio al por mayor de metales y productos metalíferos.'],
            ['EconomicActivity_number' => 4663, 'description_EconomicActivity' => 'Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción.'],
            ['EconomicActivity_number' => 4664, 'description_EconomicActivity' => 'Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario.'],
            ['EconomicActivity_number' => 4665, 'description_EconomicActivity' => 'Comercio al por mayor de desperdicios, desechos y chatarra.'],
            ['EconomicActivity_number' => 4669, 'description_EconomicActivity' => 'Comercio al por mayor de otros productos n.c.p.'],
            ['EconomicActivity_number' => 4711, 'description_EconomicActivity' => 'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco.'],
            ['EconomicActivity_number' => 4719, 'description_EconomicActivity' => 'Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco.'],
            ['EconomicActivity_number' => 4721, 'description_EconomicActivity' => 'abaco, en establecimientos especializados. 4721 Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados.'],
            ['EconomicActivity_number' => 4722, 'description_EconomicActivity' => 'Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados.'],
            ['EconomicActivity_number' => 4723, 'description_EconomicActivity' => 'Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados.'],
            ['EconomicActivity_number' => 4724, 'description_EconomicActivity' => 'Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados.'],
            ['EconomicActivity_number' => 4729, 'description_EconomicActivity' => 'Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados.'],
            ['EconomicActivity_number' => 4731, 'description_EconomicActivity' => 'Comercio al por menor de combustible para automotores.'],
            ['EconomicActivity_number' => 4732, 'description_EconomicActivity' => 'Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores.'],
            ['EconomicActivity_number' => 4741, 'description_EconomicActivity' => 'Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados.'],
            ['EconomicActivity_number' => 4742, 'description_EconomicActivity' => 'Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados.'],
            ['EconomicActivity_number' => 4751, 'description_EconomicActivity' => 'Comercio al por menor de productos textiles en establecimientos especializados.'],
            ['EconomicActivity_number' => 4752, 'description_EconomicActivity' => 'Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados.'],
            ['EconomicActivity_number' => 4753, 'description_EconomicActivity' => 'Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados.'],
            ['EconomicActivity_number' => 4754, 'description_EconomicActivity' => 'Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación.'],
            ['EconomicActivity_number' => 4755, 'description_EconomicActivity' => 'Comercio al por menor de artículos y utensilios de uso doméstico.'],
            ['EconomicActivity_number' => 4759, 'description_EconomicActivity' => 'Comercio al por menor de otros artículos domésticos en establecimientos especializados.'],
            ['EconomicActivity_number' => 4761, 'description_EconomicActivity' => 'Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados.'],
            ['EconomicActivity_number' => 4762, 'description_EconomicActivity' => 'Comercio al por menor de artículos deportivos, en establecimientos especializados.'],
            ['EconomicActivity_number' => 4769, 'description_EconomicActivity' => 'Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados.'],
            ['EconomicActivity_number' => 4771, 'description_EconomicActivity' => 'Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados.'],
            ['EconomicActivity_number' => 4772, 'description_EconomicActivity' => 'Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.'],
            ['EconomicActivity_number' => 4773, 'description_EconomicActivity' => 'Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados.'],
            ['EconomicActivity_number' => 4774, 'description_EconomicActivity' => 'Comercio al por menor de otros productos nuevos en establecimientos especializados.'],
            ['EconomicActivity_number' => 4775, 'description_EconomicActivity' => 'Comercio al por menor de artículos de segunda mano.'],
            ['EconomicActivity_number' => 4781, 'description_EconomicActivity' => 'Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles.'],
            ['EconomicActivity_number' => 4789, 'description_EconomicActivity' => 'Comercio al por menor de otros productos en puestos de venta móviles.'],
            ['EconomicActivity_number' => 4791, 'description_EconomicActivity' => 'Comercio al por menor realizado a través de internet.'],
            ['EconomicActivity_number' => 4792, 'description_EconomicActivity' => 'Comercio al por menor realizado a través de casas de venta o por correo.'],
            ['EconomicActivity_number' => 4799, 'description_EconomicActivity' => 'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados.'],
            ['EconomicActivity_number' => 4911, 'description_EconomicActivity' => 'Transporte férreo de pasajeros.'],
            ['EconomicActivity_number' => 4912, 'description_EconomicActivity' => 'Transporte férreo de carga.'],
            ['EconomicActivity_number' => 4921, 'description_EconomicActivity' => 'Transporte de pasajeros.'],
            ['EconomicActivity_number' => 4922, 'description_EconomicActivity' => 'Transporte mixto.'],
            ['EconomicActivity_number' => 4923, 'description_EconomicActivity' => 'Transporte de carga por carretera.'],
            ['EconomicActivity_number' => 5011, 'description_EconomicActivity' => 'Transporte de pasajeros marítimo y de cabotaje.'],
            ['EconomicActivity_number' => 5012, 'description_EconomicActivity' => 'Transporte de carga marítimo y de cabotaje.'],
            ['EconomicActivity_number' => 5021, 'description_EconomicActivity' => 'Transporte fluvial de pasajeros.'],
            ['EconomicActivity_number' => 5022, 'description_EconomicActivity' => 'Transporte fluvial de carga.'],
            ['EconomicActivity_number' => 5111, 'description_EconomicActivity' => 'Transporte aéreo nacional de pasajeros.'],
            ['EconomicActivity_number' => 5112, 'description_EconomicActivity' => 'Transporte aéreo internacional de pasajeros.'],
            ['EconomicActivity_number' => 5121, 'description_EconomicActivity' => 'Transporte aéreo nacional de carga.'],
            ['EconomicActivity_number' => 5122, 'description_EconomicActivity' => 'Transporte aéreo internacional de carga.'],
            ['EconomicActivity_number' => 5221, 'description_EconomicActivity' => 'Actividades de estaciones, vías y servicios complementarios para el transporte terrestre.'],
            ['EconomicActivity_number' => 5222, 'description_EconomicActivity' => 'Actividades de puertos y servicios complementarios para el transporte acuático.'],
            ['EconomicActivity_number' => 5223, 'description_EconomicActivity' => 'Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo.'],
            ['EconomicActivity_number' => 5224, 'description_EconomicActivity' => 'Manipulación de carga.'],
            ['EconomicActivity_number' => 5229, 'description_EconomicActivity' => 'Otras actividades complementarias al transporte.'],
            ['EconomicActivity_number' => 5511, 'description_EconomicActivity' => 'Alojamiento en hoteles.'],
            ['EconomicActivity_number' => 5512, 'description_EconomicActivity' => 'Alojamiento en apartahoteles.'],
            ['EconomicActivity_number' => 5513, 'description_EconomicActivity' => 'Alojamiento en centros vacacionales.'],
            ['EconomicActivity_number' => 5514, 'description_EconomicActivity' => 'Alojamiento rural.'],
            ['EconomicActivity_number' => 5519, 'description_EconomicActivity' => 'Otros tipos de alojamientos para visitantes.'],
            ['EconomicActivity_number' => 5520, 'description_EconomicActivity' => 'Actividades de zonas de camping y parques para vehículos recreacionales.'],
            ['EconomicActivity_number' => 5530, 'description_EconomicActivity' => 'Servicio por horas'],
            ['EconomicActivity_number' => 5611, 'description_EconomicActivity' => 'Expendio a la mesa de comidas preparadas.'],
            ['EconomicActivity_number' => 5612, 'description_EconomicActivity' => 'Expendio por autoservicio de comidas preparadas.'],
            ['EconomicActivity_number' => 5613, 'description_EconomicActivity' => 'Expendio de comidas preparadas en cafeterías.'],
            ['EconomicActivity_number' => 5619, 'description_EconomicActivity' => 'Otros tipos de expendio de comidas preparadas n.c.p.'],
            ['EconomicActivity_number' => 5621, 'description_EconomicActivity' => 'Catering para eventos.'],
            ['EconomicActivity_number' => 5629, 'description_EconomicActivity' => 'Actividades de otros servicios de comidas.'],
            ['EconomicActivity_number' => 5811, 'description_EconomicActivity' => 'Edición de libros.'],
            ['EconomicActivity_number' => 5812, 'description_EconomicActivity' => 'Edición de directorios y listas de correo.'],
            ['EconomicActivity_number' => 5813, 'description_EconomicActivity' => 'Edición de periódicos, revistas y otras publicaciones periódicas.'],
            ['EconomicActivity_number' => 5819, 'description_EconomicActivity' => 'Otros trabajos de edición.'],
            ['EconomicActivity_number' => 5820, 'description_EconomicActivity' => 'Edición de programas de informática (software).'],
            ['EconomicActivity_number' => 5911, 'description_EconomicActivity' => 'Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.'],
            ['EconomicActivity_number' => 5912, 'description_EconomicActivity' => 'Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.'],
            ['EconomicActivity_number' => 5913, 'description_EconomicActivity' => 'Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión.'],
            ['EconomicActivity_number' => 5914, 'description_EconomicActivity' => 'ctividades de exhibición de películas cinematográficas y videos.'],
            ['EconomicActivity_number' => 6201, 'description_EconomicActivity' => 'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas).'],
            ['EconomicActivity_number' => 6202, 'description_EconomicActivity' => 'Actividades de consultoría informática y actividades de administración de instalaciones informáticas.'],
            ['EconomicActivity_number' => 6209, 'description_EconomicActivity' => 'Otras actividades de tecnologías de información y actividades de servicios informáticos.'],
            ['EconomicActivity_number' => 6311, 'description_EconomicActivity' => 'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas; portales web.'],
            ['EconomicActivity_number' => 6312, 'description_EconomicActivity' => 'Portales web.'],
            ['EconomicActivity_number' => 6391, 'description_EconomicActivity' => 'Actividades de agencias de noticias.'],
            ['EconomicActivity_number' => 6399, 'description_EconomicActivity' => 'Otras actividades de servicio de información n.c.p.'],
            ['EconomicActivity_number' => 6411, 'description_EconomicActivity' => 'Banco Central.'],
            ['EconomicActivity_number' => 6412, 'description_EconomicActivity' => 'Bancos comerciales.'],
            ['EconomicActivity_number' => 6421, 'description_EconomicActivity' => 'Actividades de las corporaciones financieras.'],
            ['EconomicActivity_number' => 6422, 'description_EconomicActivity' => 'Actividades de las compañías de financiamiento.'],
            ['EconomicActivity_number' => 6423, 'description_EconomicActivity' => 'Banca de segundo piso.'],
            ['EconomicActivity_number' => 6424, 'description_EconomicActivity' => 'Actividades de las cooperativas financieras.'],
            ['EconomicActivity_number' => 6431, 'description_EconomicActivity' => 'Fideicomisos, fondos y entidades financieras similares.'],
            ['EconomicActivity_number' => 6432, 'description_EconomicActivity' => 'Fondos de cesantías.'],
            ['EconomicActivity_number' => 6491, 'description_EconomicActivity' => 'Leasing financiero (arrendamiento financiero).'],
            ['EconomicActivity_number' => 6492, 'description_EconomicActivity' => 'Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario.'],
            ['EconomicActivity_number' => 6493, 'description_EconomicActivity' => 'Actividades de compra de cartera o factoring.'],
            ['EconomicActivity_number' => 6494, 'description_EconomicActivity' => 'Otras actividades de distribución de fondos.'],
            ['EconomicActivity_number' => 6495, 'description_EconomicActivity' => 'Instituciones especiales oficiales.'],
            ['EconomicActivity_number' => 6499, 'description_EconomicActivity' => 'Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.'],
            ['EconomicActivity_number' => 6511, 'description_EconomicActivity' => 'Seguros generales.'],
            ['EconomicActivity_number' => 6512, 'description_EconomicActivity' => 'Seguros de vida.'],
            ['EconomicActivity_number' => 6513, 'description_EconomicActivity' => 'Reaseguros.'],
            ['EconomicActivity_number' => 6514, 'description_EconomicActivity' => 'Capitalización.'],
            ['EconomicActivity_number' => 6521, 'description_EconomicActivity' => 'Servicios de seguros sociales de salud.'],
            ['EconomicActivity_number' => 6522, 'description_EconomicActivity' => 'Servicios de seguros sociales de riesgos profesionales.'],
            ['EconomicActivity_number' => 6531, 'description_EconomicActivity' => 'Régimen de prima media con prestación definida (RPM).'],
            ['EconomicActivity_number' => 6532, 'description_EconomicActivity' => 'Régimen de ahorro individual (RAI).'],
            ['EconomicActivity_number' => 6611, 'description_EconomicActivity' => 'Administración de mercados financieros.'],
            ['EconomicActivity_number' => 6612, 'description_EconomicActivity' => 'Corretaje de valores y de contratos de productos básicos.'],
            ['EconomicActivity_number' => 6613, 'description_EconomicActivity' => 'Otras actividades relacionadas con el mercado de valores.'],
            ['EconomicActivity_number' => 6614, 'description_EconomicActivity' => 'Actividades de las casas de cambio.'],
            ['EconomicActivity_number' => 6615, 'description_EconomicActivity' => 'Actividades de los profesionales de compra y venta de divisas.'],
            ['EconomicActivity_number' => 6619, 'description_EconomicActivity' => 'Otras actividades auxiliares de las actividades de servicios financieros n.c.p.'],
            ['EconomicActivity_number' => 6621, 'description_EconomicActivity' => 'Actividades de agentes y corredores de seguros'],
            ['EconomicActivity_number' => 6629, 'description_EconomicActivity' => 'Evaluación de riesgos y daños, y otras actividades de servicios auxiliares'],
            ['EconomicActivity_number' => 7220, 'description_EconomicActivity' => 'Investigaciones y desarrollo experimental en el campo de las  ciencias  sociales y las humanidades.'],
            ['EconomicActivity_number' => 7721, 'description_EconomicActivity' => 'Alquiler y arrendamiento de equipo recreativo y deportivo.'],
            ['EconomicActivity_number' => 7722, 'description_EconomicActivity' => 'Alquiler de videos y discos.'],
            ['EconomicActivity_number' => 7729, 'description_EconomicActivity' => 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.'],
            ['EconomicActivity_number' => 7911, 'description_EconomicActivity' => 'Actividades de las agencias de viaje.'],
            ['EconomicActivity_number' => 7912, 'description_EconomicActivity' => 'Actividades de operadores turísticos.'],
            ['EconomicActivity_number' => 8121, 'description_EconomicActivity' => 'Limpieza general interior de edificios.'],
            ['EconomicActivity_number' => 8129, 'description_EconomicActivity' => 'Otras actividades de limpieza de edificios e instalaciones industriales.'],
            ['EconomicActivity_number' => 8211, 'description_EconomicActivity' => 'Actividades combinadas de servicios administrativos de oficina'],
            ['EconomicActivity_number' => 8219, 'description_EconomicActivity' => 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina.'],
            ['EconomicActivity_number' => 8291, 'description_EconomicActivity' => 'Actividades de agencias de cobranza y oficinas de calificación crediticia.'],
            ['EconomicActivity_number' => 8292, 'description_EconomicActivity' => 'Actividades de envase y empaque.'],
            ['EconomicActivity_number' => 8299, 'description_EconomicActivity' => 'Otras actividades de servicio de apoyo a las empresas n.c.p.'],
            ['EconomicActivity_number' => 8411, 'description_EconomicActivity' => 'Actividades legislativas de la administración pública.'],
            ['EconomicActivity_number' => 8412, 'description_EconomicActivity' => 'Actividades ejecutivas de la administración pública.'],
            ['EconomicActivity_number' => 8413, 'description_EconomicActivity' => 'Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales.y otros servicios sociales, excepto servicios de seguridad social.'],
            ['EconomicActivity_number' => 8414, 'description_EconomicActivity' => 'Actividades reguladoras y facilitadoras de la actividad económica.'],
            ['EconomicActivity_number' => 8415, 'description_EconomicActivity' => 'Actividades de los otros órganos de control.'],
            ['EconomicActivity_number' => 8421, 'description_EconomicActivity' => 'Relaciones exteriores.'],
            ['EconomicActivity_number' => 8422, 'description_EconomicActivity' => 'Actividades de defensa.'],
            ['EconomicActivity_number' => 8423, 'description_EconomicActivity' => 'Orden público y actividades de seguridad.'],
            ['EconomicActivity_number' => 8424, 'description_EconomicActivity' => 'Administración de justicia.'],
            ['EconomicActivity_number' => 8511, 'description_EconomicActivity' => 'Educación de la primera infancia.'],
            ['EconomicActivity_number' => 8512, 'description_EconomicActivity' => 'Educación preescolar.'],
            ['EconomicActivity_number' => 8513, 'description_EconomicActivity' => 'Educación básica primaria.'],
            ['EconomicActivity_number' => 8521, 'description_EconomicActivity' => 'Educación básica secundaria.'],
            ['EconomicActivity_number' => 8522, 'description_EconomicActivity' => 'Educación media académica.'],
            ['EconomicActivity_number' => 8523, 'description_EconomicActivity' => 'Educación media técnica y de formación laboral.'],
            ['EconomicActivity_number' => 8541, 'description_EconomicActivity' => 'Educación técnica profesional.'],
            ['EconomicActivity_number' => 8542, 'description_EconomicActivity' => 'Educación tecnológica.'],
            ['EconomicActivity_number' => 8543, 'description_EconomicActivity' => 'Educación de instituciones universitarias o de escuelas tecnológicas.'],
            ['EconomicActivity_number' => 8544, 'description_EconomicActivity' => 'Educación de universidades.'],
            ['EconomicActivity_number' => 8551, 'description_EconomicActivity' => 'Formación académica no formal.'],
            ['EconomicActivity_number' => 8552, 'description_EconomicActivity' => 'Enseñanza deportiva y recreativa.'],
            ['EconomicActivity_number' => 8553, 'description_EconomicActivity' => 'Enseñanza cultural.'],
            ['EconomicActivity_number' => 8559, 'description_EconomicActivity' => 'Otros tipos de educación n.c.p.'],
            ['EconomicActivity_number' => 8621, 'description_EconomicActivity' => 'Actividades de la práctica médica, sin internación.'],
            ['EconomicActivity_number' => 8622, 'description_EconomicActivity' => 'Actividades de la práctica odontológica.'],
            ['EconomicActivity_number' => 8691, 'description_EconomicActivity' => 'Actividades de apoyo diagnóstico.'],
            ['EconomicActivity_number' => 8692, 'description_EconomicActivity' => 'Actividades de apoyo terapéutico.'],
            ['EconomicActivity_number' => 8699, 'description_EconomicActivity' => 'Otras actividades de atención de la salud humana.'],
            ['EconomicActivity_number' => 8790, 'description_EconomicActivity' => 'Otras actividades de atención en instituciones con alojamiento'],
            ['EconomicActivity_number' => 9001, 'description_EconomicActivity' => 'Creación literaria.'],
            ['EconomicActivity_number' => 9002, 'description_EconomicActivity' => 'Creación musical.'],
            ['EconomicActivity_number' => 9003, 'description_EconomicActivity' => 'Creación teatral.'],
            ['EconomicActivity_number' => 9004, 'description_EconomicActivity' => 'Creación audiovisual.'],
            ['EconomicActivity_number' => 9005, 'description_EconomicActivity' => 'Artes plásticas y visuales.'],
            ['EconomicActivity_number' => 9006, 'description_EconomicActivity' => 'Actividades teatrales.'],
            ['EconomicActivity_number' => 9007, 'description_EconomicActivity' => 'Actividades de espectáculos musicales en vivo.'],
            ['EconomicActivity_number' => 9008, 'description_EconomicActivity' => 'Otras actividades de espectáculos en vivo.'],
            ['EconomicActivity_number' => 9101, 'description_EconomicActivity' => 'Actividades de bibliotecas y archivos.'],
            ['EconomicActivity_number' => 9102, 'description_EconomicActivity' => 'Actividades y funcionamiento de museos, conservación de edificios y sitios históricos.'],
            ['EconomicActivity_number' => 9103, 'description_EconomicActivity' => 'Actividades de jardines botánicos, zoológicos y reservas naturales.'],
            ['EconomicActivity_number' => 9311, 'description_EconomicActivity' => 'Gestión de instalaciones deportivas.'],
            ['EconomicActivity_number' => 9312, 'description_EconomicActivity' => 'Actividades de clubes deportivos.'],
            ['EconomicActivity_number' => 9319, 'description_EconomicActivity' => 'Otras actividades deportivas.'],
            ['EconomicActivity_number' => 9321, 'description_EconomicActivity' => 'Actividades de parques de atracciones y parques temáticos.'],
            ['EconomicActivity_number' => 9329, 'description_EconomicActivity' => 'Otras actividades recreativas y de esparcimiento n.c.p.'],
            ['EconomicActivity_number' => 9411, 'description_EconomicActivity' => 'Actividades de asociaciones empresariales y de empleadores'],
            ['EconomicActivity_number' => 9412, 'description_EconomicActivity' => 'Actividades de asociaciones profesionales'],
            ['EconomicActivity_number' => 9491, 'description_EconomicActivity' => 'Actividades de asociaciones religiosas.'],
            ['EconomicActivity_number' => 9492, 'description_EconomicActivity' => 'Actividades de asociaciones políticas.'],
            ['EconomicActivity_number' => 9499, 'description_EconomicActivity' => 'Actividades de otras asociaciones n.c.p.'],
            ['EconomicActivity_number' => 9511, 'description_EconomicActivity' => 'Mantenimiento y reparación de computadores y de equipo periférico.'],
            ['EconomicActivity_number' => 9512, 'description_EconomicActivity' => 'Mantenimiento y reparación de equipos de comunicación.'],
            ['EconomicActivity_number' => 9521, 'description_EconomicActivity' => 'Mantenimiento y reparación de aparatos electrónicos de consumo.'],
            ['EconomicActivity_number' => 9522, 'description_EconomicActivity' => 'Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería.'],
            ['EconomicActivity_number' => 9523, 'description_EconomicActivity' => 'Reparación de calzado y artículos de cuero.'],
            ['EconomicActivity_number' => 9524, 'description_EconomicActivity' => 'Reparación de muebles y accesorios para el hogar.'],
            ['EconomicActivity_number' => 9529, 'description_EconomicActivity' => 'Mantenimiento y reparación de otros efectos personales y enseres domésticos.'],
            ['EconomicActivity_number' => 9601, 'description_EconomicActivity' => 'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel.'],
            ['EconomicActivity_number' => 9602, 'description_EconomicActivity' => 'Peluquería y otros tratamientos de belleza.'],
            ['EconomicActivity_number' => 9603, 'description_EconomicActivity' => 'Pompas fúnebres y actividades relacionadas.'],
            ['EconomicActivity_number' => 9609, 'description_EconomicActivity' => 'Otras actividades de servicios personales n.c.p.'],
        ]);
    }
}
