<?php

namespace Database\Seeders;

use App\Models\EconomicActivityCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EconomicActivityCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        EconomicActivityCategory::insert([

            ['division' => '01', 'groups' => '011', 'description' => 'Agricultura, ganadería, caza y actividades de servicios conexas'],
            ['division' => '01', 'groups' => '012', 'description' => 'Cultivos agrícolas permanentes'],
            ['division' => '01', 'groups' => '013', 'description' => 'Propagación de plantas (actividades de los viveros, excepto viveros forestales)'],
            ['division' => '01', 'groups' => '014', 'description' => 'Ganadería'],
            ['division' => '01', 'groups' => '015', 'description' => 'Explotación mixta (agrícola y pecuaria)'],
            ['division' => '01', 'groups' => '016', 'description' => 'Actividades de apoyo a la agricultura y la ganadería, y actividades posteriores a la cosecha'],
            ['division' => '01', 'groups' => '017', 'description' => 'Caza ordinaria y mediante trampas y actividades de servicios conexas'],
            ['division' => '02', 'groups' => '021', 'description' => 'Silvicultura y extracción de madera'],
            ['division' => '02', 'groups' => '022', 'description' => 'Extracción de madera'],
            ['division' => '02', 'groups' => '023', 'description' => 'Recolección de productos forestales diferentes a la madera'],
            ['division' => '02', 'groups' => '024', 'description' => 'Servicios de apoyo a la silvicultura'],
            ['division' => '03', 'groups' => '031', 'description' => 'Pesca y acuicultura'],
            ['division' => '03', 'groups' => '032', 'description' => 'Acuicultura'],
            ['division' => '05', 'groups' => '051', 'description' => 'Extracción de carbón de piedra y lignito'],
            ['division' => '05', 'groups' => '052', 'description' => 'Extracción de carbón lignito'],
            ['division' => '06', 'groups' => '061', 'description' => 'Extracción de petróleo crudo y gas natural'],
            ['division' => '06', 'groups' => '062', 'description' => 'Extracción de gas natural'],
            ['division' => '07', 'groups' => '071', 'description' => 'Extracción de minerales metalíferos'],
            ['division' => '07', 'groups' => '072', 'description' => 'Extracción de minerales metalíferos no ferrosos'],
            ['division' => '08', 'groups' => '081', 'description' => 'Extracción de otras minas y canteras'],
            ['division' => '08', 'groups' => '082', 'description' => 'Extracción de esmeraldas, piedras preciosas y semipreciosas'],
            ['division' => '08', 'groups' => '089', 'description' => 'Extracción de otros minerales no metálicos n.c.p.'],
            ['division' => '09', 'groups' => '091', 'description' => 'Actividades de servicios de apoyo para la explotación de minas'],
            ['division' => '09', 'groups' => '099', 'description' => 'Actividades de apoyo para otras actividades de explotación de minas y canteras'],
            ['division' => '10', 'groups' => '101', 'description' => 'Elaboración de productos alimenticios'],
            ['division' => '10', 'groups' => '102', 'description' => 'Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos'],
            ['division' => '10', 'groups' => '103', 'description' => 'Elaboración de aceites y grasas de origen vegetal y animal'],
            ['division' => '10', 'groups' => '104', 'description' => 'Elaboración de productos lácteos'],
            ['division' => '10', 'groups' => '105', 'description' => 'Elaboración de productos de molinería, almidones y productos derivados del almidón'],
            ['division' => '10', 'groups' => '106', 'description' => 'Elaboración de productos de café'],
            ['division' => '10', 'groups' => '107', 'description' => 'Elaboración de azúcar y panela'],
            ['division' => '10', 'groups' => '108', 'description' => 'Elaboración de otros productos alimenticios'],
            ['division' => '10', 'groups' => '109', 'description' => 'Elaboración de alimentos preparados para animales'],
            ['division' => '11', 'groups' => '110', 'description' => 'Elaboración de bebidas'],
            ['division' => '12', 'groups' => '120', 'description' => 'Elaboración de productos de tabaco'],
            ['division' => '13', 'groups' => '131', 'description' => 'Fabricación de productos textiles'],
            ['division' => '13', 'groups' => '139', 'description' => 'Fabricación de otros productos textiles'],
            ['division' => '14', 'groups' => '141', 'description' => 'Confección de prendas de vestir'],
            ['division' => '14', 'groups' => '142', 'description' => 'Fabricación de artículos de piel'],
            ['division' => '14', 'groups' => '143', 'description' => 'Fabricación de artículos de punto y ganchillo'],
            ['division' => '15', 'groups' => '151', 'description' => 'Curtido y recurtido de cueros; fabricación de artículos de viaje, bolsos de mano y artículos similares'],
            ['division' => '15', 'groups' => '152', 'description' => 'Fabricación de calzado'],
            ['division' => '16', 'groups' => '161', 'description' => 'Transformación de la madera y fabricación de productos de madera y de corcho'],
            ['division' => '16', 'groups' => '162', 'description' => 'Fabricación de hojas de madera para enchapado'],
            ['division' => '16', 'groups' => '163', 'description' => 'Fabricación de partes y piezas de madera'],
            ['division' => '16', 'groups' => '164', 'description' => 'Fabricación de recipientes de madera'],
            ['division' => '16', 'groups' => '169', 'description' => 'Fabricación de otros productos de madera'],
            ['division' => '17', 'groups' => '170', 'description' => 'Fabricación de papel, cartón y productos de papel y cartón'],
            ['division' => '18', 'groups' => '181', 'description' => 'Actividades de impresión y de producción de copias a partir de grabaciones originales'],
            ['division' => '18', 'groups' => '182', 'description' => 'Producción de copias a partir de grabaciones originales'],
            ['division' => '19', 'groups' => '191', 'description' => 'Coquización, fabricación de productos de la refinación del petróleo'],
            ['division' => '19', 'groups' => '192', 'description' => 'Fabricación de productos de la refinación del petróleo'],
            ['division' => '20', 'groups' => '201', 'description' => 'Fabricación de sustancias y productos químicos'],
            ['division' => '20', 'groups' => '202', 'description' => 'Fabricación de otros productos químicos'],
            ['division' => '20', 'groups' => '203', 'description' => 'Fabricación de fibras sintéticas y artificiales'],
            ['division' => '21', 'groups' => '210', 'description' => 'Fabricación de productos farmacéuticos'],
            ['division' => '22', 'groups' => '221', 'description' => 'Fabricación de productos de caucho y de plástico'],
            ['division' => '22', 'groups' => '222', 'description' => 'Fabricación de productos de plástico'],
            ['division' => '23', 'groups' => '231', 'description' => 'Fabricación de otros productos minerales no metálicos'],
            ['division' => '23', 'groups' => '239', 'description' => 'Fabricación de productos minerales no metálicos n.c.p.'],
            ['division' => '24', 'groups' => '241', 'description' => 'Fabricación de productos metalúrgicos básicos'],
            ['division' => '24', 'groups' => '242', 'description' => 'Industrias básicas de metales preciosos y de metales no ferrosos'],
            ['division' => '24', 'groups' => '243', 'description' => 'Fundición de metales'],
            ['division' => '25', 'groups' => '251', 'description' => 'Fabricación de productos elaborados de metal'],
            ['division' => '25', 'groups' => '252', 'description' => 'Fabricación de armas y municiones'],
            ['division' => '25', 'groups' => '259', 'description' => 'Fabricación de otros productos elaborados de metal'],
            ['division' => '26', 'groups' => '261', 'description' => 'Fabricación de productos informáticos, electrónicos y ópticos'],
            ['division' => '26', 'groups' => '262', 'description' => 'Fabricación de computadoras y de equipo periférico'],
            ['division' => '26', 'groups' => '263', 'description' => 'Fabricación de equipos de comunicación'],
            ['division' => '26', 'groups' => '264', 'description' => 'Fabricación de aparatos electrónicos de consumo'],
            ['division' => '26', 'groups' => '265', 'description' => 'Fabricación de equipo de medición, prueba, navegación y control'],
            ['division' => '26', 'groups' => '266', 'description' => 'Fabricación de equipo de irradiación y equipo electrónico de uso médico'],
            ['division' => '26', 'groups' => '267', 'description' => 'Fabricación de instrumentos ópticos y equipo fotográfico'],
            ['division' => '26', 'groups' => '268', 'description' => 'Fabricación de medios magnéticos y ópticos para almacenamiento de datos'],
            ['division' => '27', 'groups' => '271', 'description' => 'Fabricación de aparatos y equipo eléctrico'],
            ['division' => '27', 'groups' => '272', 'description' => 'Fabricación de pilas, baterías y acumuladores eléctricos'],
            ['division' => '27', 'groups' => '273', 'description' => 'Fabricación de hilos y cables aislados y sus dispositivos'],
            ['division' => '27', 'groups' => '274', 'description' => 'Fabricación de equipos eléctricos de iluminación'],
            ['division' => '27', 'groups' => '275', 'description' => 'Fabricación de aparatos de uso doméstico'],
            ['division' => '27', 'groups' => '279', 'description' => 'Fabricación de otros tipos de equipo eléctrico n.c.p.'],
            ['division' => '28', 'groups' => '281', 'description' => 'Fabricación de maquinaria y equipo n.c.p.'],
            ['division' => '28', 'groups' => '282', 'description' => 'Fabricación de maquinaria y equipo de uso especial'],
            ['division' => '29', 'groups' => '291', 'description' => 'Fabricación de vehículos automotores, remolques y semirremolques'],
            ['division' => '29', 'groups' => '292', 'description' => 'Fabricación de carrocerías para vehículos automotores'],
            ['division' => '29', 'groups' => '293', 'description' => 'Fabricación de partes, piezas y accesorios para vehículos automotores'],
            ['division' => '30', 'groups' => '301', 'description' => 'Fabricación de otros tipos de equipo de transporte'],
            ['division' => '30', 'groups' => '302', 'description' => 'Fabricación de locomotoras y de material rodante para ferrocarriles'],
            ['division' => '30', 'groups' => '303', 'description' => 'Fabricación de aeronaves, naves espaciales y de maquinaria conexa'],
            ['division' => '30', 'groups' => '304', 'description' => 'Fabricación de vehículos militares de combate'],
            ['division' => '30', 'groups' => '309', 'description' => 'Fabricación de otros tipos de equipo de transporte n.c.p.'],
            ['division' => '31', 'groups' => '311', 'description' => 'Fabricación de muebles, colchones y somieres'],
            ['division' => '31', 'groups' => '312', 'description' => 'Fabricación de colchones y somieres'],
            ['division' => '32', 'groups' => '321', 'description' => 'Otras industrias manufactureras'],
            ['division' => '32', 'groups' => '322', 'description' => 'Fabricación de instrumentos musicales'],
            ['division' => '32', 'groups' => '323', 'description' => 'Fabricación de artículos y equipo para la práctica del deporte'],
            ['division' => '32', 'groups' => '324', 'description' => 'Fabricación de juegos, juguetes y rompecabezas'],
            ['division' => '32', 'groups' => '325', 'description' => 'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos'],
            ['division' => '32', 'groups' => '329', 'description' => 'Otras industrias manufactureras n.c.p.'],
            ['division' => '33', 'groups' => '331', 'description' => 'Instalación, mantenimiento y reparación especializado de maquinaria y equipo'],
            ['division' => '33', 'groups' => '332', 'description' => 'Instalación especializada de maquinaria y equipo industrial'],
            ['division' => '35', 'groups' => '351', 'description' => 'Suministro de electricidad, gas, vapor y aire acondicionado'],
            ['division' => '35', 'groups' => '352', 'description' => 'Producción de gas; distribución de combustibles gaseosos por tuberías'],
            ['division' => '35', 'groups' => '353', 'description' => 'Suministro de vapor y aire acondicionado'],
            ['division' => '36', 'groups' => '360', 'description' => 'Captación, tratamiento y distribución de agua'],
            ['division' => '37', 'groups' => '370', 'description' => 'Evacuación y tratamiento de aguas residuales'],
            ['division' => '38', 'groups' => '381', 'description' => 'Recolección, tratamiento y disposición de desechos, recuperación de materiales'],
            ['division' => '38', 'groups' => '382', 'description' => 'Tratamiento y disposición de desechos'],
            ['division' => '38', 'groups' => '383', 'description' => 'Recuperación de materiales'],
            ['division' => '39', 'groups' => '390', 'description' => 'Actividades de saneamiento ambiental y otros servicios de gestión de desechos'],
            ['division' => '41', 'groups' => '411', 'description' => 'Construcción de edificios'],
            ['division' => '42', 'groups' => '421', 'description' => 'Obras de ingeniería civil'],
            ['division' => '42', 'groups' => '422', 'description' => 'Construcción de proyectos de servicio público'],
            ['division' => '42', 'groups' => '429', 'description' => 'Construcción de otras obras de ingeniería civil'],
            ['division' => '43', 'groups' => '431', 'description' => 'Actividades especializadas para la construcción de edificios y obras de ingeniería civil'],
            ['division' => '43', 'groups' => '432', 'description' => 'Instalaciones eléctricas, de fontanería y otras instalaciones especializadas'],
            ['division' => '43', 'groups' => '433', 'description' => 'Terminación y acabado de edificios y obras de ingeniería civil'],
            ['division' => '43', 'groups' => '439', 'description' => 'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil'],
            ['division' => '45', 'groups' => '451', 'description' => 'Comercio, mantenimiento y reparación de vehículos automotores y motocicletas'],
            ['division' => '45', 'groups' => '452', 'description' => 'Mantenimiento y reparación de vehículos automotores'],
            ['division' => '45', 'groups' => '453', 'description' => 'Comercio de partes, piezas y accesorios para vehículos automotores'],
            ['division' => '45', 'groups' => '454', 'description' => 'Comercio, mantenimiento y reparación de motocicletas y de sus partes'],
            ['division' => '46', 'groups' => '461', 'description' => 'Comercio al por mayor y en comisión o por contrata'],
            ['division' => '46', 'groups' => '462', 'description' => 'Comercio al por mayor de materias primas agropecuarias; animales vivos'],
            ['division' => '46', 'groups' => '463', 'description' => 'Comercio al por mayor de alimentos, bebidas y tabaco'],
            ['division' => '46', 'groups' => '464', 'description' => 'Comercio al por mayor de artículos y enseres domésticos'],
            ['division' => '46', 'groups' => '465', 'description' => 'Comercio al por mayor de maquinaria y equipo'],
            ['division' => '46', 'groups' => '466', 'description' => 'Comercio al por mayor especializado de otros productos'],
            ['division' => '46', 'groups' => '469', 'description' => 'Comercio al por mayor no especializado'],
            ['division' => '47', 'groups' => '471', 'description' => 'Comercio al por menor en establecimientos no especializados'],
            ['division' => '47', 'groups' => '472', 'description' => 'Comercio al por menor de alimentos, bebidas y tabaco, en establecimientos especializados'],
            ['division' => '47', 'groups' => '473', 'description' => 'Comercio al por menor de combustible, lubricantes, aditivos y productos de limpieza para automotores'],
            ['division' => '47', 'groups' => '474', 'description' => 'Comercio al por menor de equipos de informática y de comunicaciones'],
            ['division' => '47', 'groups' => '475', 'description' => 'Comercio al por menor de otros enseres domésticos en establecimientos especializados'],
            ['division' => '47', 'groups' => '476', 'description' => 'Comercio al por menor de artículos culturales y de entretenimiento'],
            ['division' => '47', 'groups' => '477', 'description' => 'Comercio al por menor de otros productos en establecimientos especializados'],
            ['division' => '47', 'groups' => '478', 'description' => 'Comercio al por menor en puestos de venta móviles'],
            ['division' => '47', 'groups' => '479', 'description' => 'Comercio al por menor no realizado en establecimientos, puestos de venta o mercados'],
            ['division' => '49', 'groups' => '491', 'description' => 'Transporte terrestre; transporte por tuberías'],
            ['division' => '49', 'groups' => '492', 'description' => 'Transporte terrestre público automotor'],
            ['division' => '49', 'groups' => '493', 'description' => 'Transporte por tuberías'],
            ['division' => '50', 'groups' => '501', 'description' => 'Transporte acuático'],
            ['division' => '50', 'groups' => '502', 'description' => 'Transporte fluvial'],
            ['division' => '51', 'groups' => '511', 'description' => 'Transporte aéreo'],
            ['division' => '51', 'groups' => '512', 'description' => 'Transporte aéreo de carga'],
            ['division' => '52', 'groups' => '521', 'description' => 'Almacenamiento y actividades complementarias al transporte'],
            ['division' => '52', 'groups' => '522', 'description' => 'Actividades de las estaciones, vías y servicios complementarios para el transporte'],
            ['division' => '53', 'groups' => '531', 'description' => 'Correo y servicios de mensajería'],
            ['division' => '53', 'groups' => '532', 'description' => 'Actividades de mensajería'],
            ['division' => '55', 'groups' => '551', 'description' => 'Alojamiento'],
            ['division' => '55', 'groups' => '552', 'description' => 'Actividades de zonas de camping y parques para vehículos recreacionales'],
            ['division' => '55', 'groups' => '553', 'description' => 'Servicio por horas'],
            ['division' => '55', 'groups' => '559', 'description' => 'Otros tipos de alojamiento n.c.p.'],
            ['division' => '56', 'groups' => '561', 'description' => 'Actividades de servicios de comidas y bebidas'],
            ['division' => '56', 'groups' => '562', 'description' => 'Actividades de catering para eventos y otros servicios de comidas'],
            ['division' => '56', 'groups' => '563', 'description' => 'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento'],
            ['division' => '58', 'groups' => '581', 'description' => 'Actividades de edición'],
            ['division' => '58', 'groups' => '582', 'description' => 'Edición de programas de informática (software)'],
            ['division' => '59', 'groups' => '591', 'description' => 'Actividades cinematográficas, de video y producción de programas de televisión'],
            ['division' => '59', 'groups' => '592', 'description' => 'Actividades de grabación de sonido y edición de música'],
            ['division' => '60', 'groups' => '601', 'description' => 'Actividades de programación, transmisión y/o difusión'],
            ['division' => '60', 'groups' => '602', 'description' => 'Actividades de programación y transmisión de televisión'],
            ['division' => '61', 'groups' => '611', 'description' => 'Telecomunicaciones'],
            ['division' => '61', 'groups' => '612', 'description' => 'Actividades de telecomunicaciones inalámbricas'],
            ['division' => '61', 'groups' => '613', 'description' => 'Actividades de telecomunicación satelital'],
            ['division' => '61', 'groups' => '619', 'description' => 'Otras actividades de telecomunicaciones'],
            ['division' => '62', 'groups' => '620', 'description' => 'Desarrollo de sistemas informáticos, consultoría informática y actividades relacionadas'],
            ['division' => '63', 'groups' => '631', 'description' => 'Actividades de servicios de información'],
            ['division' => '63', 'groups' => '639', 'description' => 'Otras actividades de servicio de información'],
            ['division' => '64', 'groups' => '641', 'description' => 'Actividades de servicios financieros, excepto las de seguros y de pensiones'],
            ['division' => '64', 'groups' => '642', 'description' => 'Otros tipos de intermediación monetaria'],
            ['division' => '64', 'groups' => '643', 'description' => 'Fideicomisos, fondos y entidades financieras similares'],
            ['division' => '64', 'groups' => '649', 'description' => 'Otras actividades de servicio financiero, excepto las de seguros y pensiones'],
            ['division' => '65', 'groups' => '651', 'description' => 'Seguros (incluso el reaseguro), seguros sociales y fondos de pensiones'],
            ['division' => '65', 'groups' => '652', 'description' => 'Servicios de seguros sociales de salud y riesgos profesionales'],
            ['division' => '65', 'groups' => '653', 'description' => 'Servicios de seguros sociales de pensiones'],
            ['division' => '66', 'groups' => '661', 'description' => 'Actividades auxiliares de las actividades de servicios financieros'],
            ['division' => '66', 'groups' => '662', 'description' => 'Actividades de servicios auxiliares de los servicios de seguros y pensiones'],
            ['division' => '66', 'groups' => '663', 'description' => 'Actividades de administración de fondos'],
            ['division' => '68', 'groups' => '681', 'description' => 'Actividades inmobiliarias'],
            ['division' => '68', 'groups' => '682', 'description' => 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata'],
            ['division' => '69', 'groups' => '691', 'description' => 'Actividades jurídicas y de contabilidad'],
            ['division' => '69', 'groups' => '692', 'description' => 'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria'],
            ['division' => '70', 'groups' => '701', 'description' => 'Actividades de administración empresarial; actividades de consultoría de gestión'],
            ['division' => '70', 'groups' => '702', 'description' => 'Actividades de consultaría de gestión'],
            ['division' => '71', 'groups' => '711', 'description' => 'Actividades de arquitectura e ingeniería; ensayos y análisis técnicos'],
            ['division' => '71', 'groups' => '712', 'description' => 'Ensayos y análisis técnicos'],
            ['division' => '72', 'groups' => '721', 'description' => 'Investigación científica y desarrollo'],
            ['division' => '72', 'groups' => '722', 'description' => 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades'],
            ['division' => '73', 'groups' => '731', 'description' => 'Publicidad y estudios de mercado'],
            ['division' => '73', 'groups' => '732', 'description' => 'Estudios de mercado y realización de encuestas de opinión pública'],
            ['division' => '74', 'groups' => '741', 'description' => 'Otras actividades profesionales, científicas y técnicas'],
            ['division' => '74', 'groups' => '742', 'description' => 'Actividades de fotografía'],
            ['division' => '74', 'groups' => '749', 'description' => 'Otras actividades profesionales, científicas y técnicas n.c.p.'],
            ['division' => '75', 'groups' => '750', 'description' => 'Actividades veterinarias'],
            ['division' => '77', 'groups' => '771', 'description' => 'Actividades de alquiler y arrendamiento'],
            ['division' => '77', 'groups' => '772', 'description' => 'Alquiler y arrendamiento de efectos personales y enseres domésticos'],
            ['division' => '77', 'groups' => '773', 'description' => 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.'],
            ['division' => '77', 'groups' => '774', 'description' => 'Arrendamiento de propiedad intelectual y productos similares'],
            ['division' => '78', 'groups' => '781', 'description' => 'Actividades de empleo'],
            ['division' => '78', 'groups' => '782', 'description' => 'Actividades de agencias de empleo temporal'],
            ['division' => '78', 'groups' => '783', 'description' => 'Otras actividades de suministro de recurso humano'],
            ['division' => '79', 'groups' => '791', 'description' => 'Actividades de las agencias de viajes, operadores turísticos, servicios de reserva y actividades relacionadas'],
            ['division' => '79', 'groups' => '799', 'description' => 'Otros servicios de reserva y actividades relacionadas'],
            ['division' => '80', 'groups' => '801', 'description' => 'Actividades de seguridad e investigación privada'],
            ['division' => '80', 'groups' => '802', 'description' => 'Actividades de servicios de sistemas de seguridad'],
            ['division' => '80', 'groups' => '803', 'description' => 'Actividades de detectives e investigadores privados'],
            ['division' => '81', 'groups' => '811', 'description' => 'Actividades de servicios a edificios y paisajismo'],
            ['division' => '81', 'groups' => '812', 'description' => 'Actividades de limpieza'],
            ['division' => '81', 'groups' => '813', 'description' => 'Actividades de paisajismo y servicios de mantenimiento conexos'],
            ['division' => '82', 'groups' => '821', 'description' => 'Actividades administrativas y de apoyo de oficina y otras actividades de apoyo a las empresas'],
            ['division' => '82', 'groups' => '822', 'description' => 'Actividades de centros de llamadas (Call center)'],
            ['division' => '82', 'groups' => '823', 'description' => 'Organización de convenciones y eventos comerciales'],
            ['division' => '82', 'groups' => '829', 'description' => 'Actividades de servicios de apoyo a las empresas n.c.p.'],
            ['division' => '84', 'groups' => '841', 'description' => 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria'],
            ['division' => '84', 'groups' => '842', 'description' => 'Prestación de servicios a la comunidad en general'],
            ['division' => '84', 'groups' => '843', 'description' => 'Actividades de planes de seguridad social de afiliación obligatoria'],
            ['division' => '85', 'groups' => '851', 'description' => 'Educación'],
            ['division' => '85', 'groups' => '852', 'description' => 'Educación secundaria y de formación laboral'],
            ['division' => '85', 'groups' => '853', 'description' => 'Establecimientos que combinan diferentes niveles de educación'],
            ['division' => '85', 'groups' => '854', 'description' => 'Educación superior'],
            ['division' => '85', 'groups' => '855', 'description' => 'Otros tipos de educación'],
            ['division' => '85', 'groups' => '856', 'description' => 'Actividades de apoyo a la educación'],
            ['division' => '86', 'groups' => '861', 'description' => 'Actividades de atención de la salud humana'],
            ['division' => '86', 'groups' => '862', 'description' => 'Actividades de práctica médica y odontológica, sin internación'],
            ['division' => '86', 'groups' => '869', 'description' => 'Otras actividades de atención relacionadas con la salud humana'],
            ['division' => '87', 'groups' => '871', 'description' => 'Actividades de atención residencial medicalizada'],
            ['division' => '87', 'groups' => '872', 'description' => 'Actividades de atención residencial, para el cuidado de pacientes con retardo mental'],
            ['division' => '87', 'groups' => '873', 'description' => 'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas'],
            ['division' => '87', 'groups' => '879', 'description' => 'Otras actividades de atención en instituciones con alojamiento'],
            ['division' => '88', 'groups' => '881', 'description' => 'Actividades de asistencia social sin alojamiento'],
            ['division' => '88', 'groups' => '889', 'description' => 'Otras actividades de asistencia social sin alojamiento'],
            ['division' => '90', 'groups' => '900', 'description' => 'Actividades creativas, artísticas y de entretenimiento'],
            ['division' => '91', 'groups' => '910', 'description' => 'Actividades de bibliotecas, archivos, museos y otras actividades culturales'],
            ['division' => '92', 'groups' => '920', 'description' => 'Actividades de juegos de azar y apuestas'],
            ['division' => '93', 'groups' => '931', 'description' => 'Actividades deportivas y actividades recreativas y de esparcimiento'],
            ['division' => '93', 'groups' => '932', 'description' => 'Otras actividades recreativas y de esparcimiento'],
            ['division' => '94', 'groups' => '941', 'description' => 'Actividades de asociaciones'],
            ['division' => '94', 'groups' => '942', 'description' => 'Actividades de sindicatos de empleados'],
            ['division' => '94', 'groups' => '949', 'description' => 'Actividades de otras asociaciones'],
            ['division' => '95', 'groups' => '951', 'description' => 'Mantenimiento y reparación de computadores, efectos personales y enseres domésticos'],
            ['division' => '95', 'groups' => '952', 'description' => 'Mantenimiento y reparación de efectos personales y enseres domésticos'],
            ['division' => '96', 'groups' => '960', 'description' => 'Otras actividades de servicios personales'],
            ['division' => '97', 'groups' => '970', 'description' => 'Actividades de los hogares individuales como empleadores de personal doméstico'],
            ['division' => '98', 'groups' => '981', 'description' => 'Actividades no diferenciadas de los hogares individuales como productores de bienes y servicios para uso propio'],
            ['division' => '98', 'groups' => '982', 'description' => 'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio'],
            ['division' => '99', 'groups' => '990', 'description' => 'Actividades de organizaciones y entidades extraterritoriales']

        ]);
    }
}
