<?php

namespace Database\Seeders;

use App\Models\Entity;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Masterminds\HTML5\Entities;

class EntitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     */

    private function uniqueNit(int $digits = 8): string
    {
        static $used = [];

        do {
            $nit = (string) random_int(
                10 ** ($digits - 1),
                (10 ** $digits) - 1
            );
        } while (in_array($nit, $used));

        $used[] = $nit;

        return $nit;
    }
    public function run(): void
    {


        $entities = [
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'ALIANSALUD',
                'commercial_reason_supplier' => 'ALIANSALUD',
                'supplier_web_page' => 'www.aliansalud.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'ALIANSALUD',
                'supplier_email' => 'aliansalud@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'AMBUQ',
                'commercial_reason_supplier' => 'AMBUQ',
                'supplier_web_page' => 'www.ambuq.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'AMBUQ',
                'supplier_email' => 'ambuq@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'ASMET SALUD',
                'commercial_reason_supplier' => 'ASMET SALUD',
                'supplier_web_page' => 'www.asmetsalud.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'ASMET SALUD',
                'supplier_email' => 'asmetsalud@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'CAFE SALUD',
                'commercial_reason_supplier' => 'CAFE SALUD',
                'supplier_web_page' => 'www.cafesalud.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'CAFE SALUD',
                'supplier_email' => 'cafesalud@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'CAPITAL SALUD',
                'commercial_reason_supplier' => 'CAPITAL SALUD',
                'supplier_web_page' => 'www.capitalsalud.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'CAPITAL SALUD',
                'supplier_email' => 'capitalsalud@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'COMPARTA',
                'commercial_reason_supplier' => 'COMPARTA',
                'supplier_web_page' => 'www.comparta.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'COMPARTA',
                'supplier_email' => 'comparta@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'COMPENSAR',
                'commercial_reason_supplier' => 'COMPENSAR',
                'supplier_web_page' => 'www.compensar.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'COMPENSAR',
                'supplier_email' => 'compensar@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'COOMEVA',
                'commercial_reason_supplier' => 'COOMEVA',
                'supplier_web_page' => 'www.coomeva.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'COOMEVA',
                'supplier_email' => 'coomeva@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'COOSALUD',
                'commercial_reason_supplier' => 'COOSALUD',
                'supplier_web_page' => 'www.coosalud.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'COOSALUD',
                'supplier_email' => 'coosalud@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'CRUZ BLANCA',
                'commercial_reason_supplier' => 'CRUZ BLANCA',
                'supplier_web_page' => 'www.cruzblanca.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'CRUZ BLANCA',
                'supplier_email' => 'cruzblanca@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'EMSSANAR',
                'commercial_reason_supplier' => 'EMSSANAR',
                'supplier_web_page' => 'www.emssanar.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'EMSSANAR',
                'supplier_email' => 'emssanar@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'FAMISANAR',
                'commercial_reason_supplier' => 'FAMISANAR',
                'supplier_web_page' => 'www.famisanar.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'FAMISANAR',
                'supplier_email' => 'famisanar@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'MEDIMAS',
                'commercial_reason_supplier' => 'MEDIMAS',
                'supplier_web_page' => 'www.medimas.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'MEDIMAS',
                'supplier_email' => 'medimas@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'MUTUAL SER',
                'commercial_reason_supplier' => 'MUTUAL SER',
                'supplier_web_page' => 'www.mutualser.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'MUTUAL SER',
                'supplier_email' => 'mutualser@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'NUEVA EPS',
                'commercial_reason_supplier' => 'NUEVA EPS',
                'supplier_web_page' => 'www.nuevaeps.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'NUEVA EPS',
                'supplier_email' => 'nuevaeps@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'SALUD TOTAL',
                'commercial_reason_supplier' => 'SALUD TOTAL',
                'supplier_web_page' => 'www.saludtotal.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'SALUD TOTAL',
                'supplier_email' => 'saludtotal@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'SALUDVIDA',
                'commercial_reason_supplier' => 'SALUDVIDA',
                'supplier_web_page' => 'www.saludvida.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'SALUDVIDA',
                'supplier_email' => 'saludvida@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'SANITAS',
                'commercial_reason_supplier' => 'SANITAS',
                'supplier_web_page' => 'www.sanitas.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'SANITAS',
                'supplier_email' => 'sanitas@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'SAVIA SALUD',
                'commercial_reason_supplier' => 'SAVIA SALUD',
                'supplier_web_page' => 'www.saviasalud.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'SAVIA SALUD',
                'supplier_email' => 'saviasalud@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'SERVICIO OCCIDENTAL DE SALUD S.O.S',
                'commercial_reason_supplier' => 'SERVICIO OCCIDENTAL DE SALUD S.O.S',
                'supplier_web_page' => 'www.sos.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'SERVICIO OCCIDENTAL DE SALUD S.O.S',
                'supplier_email' => 'sos@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'SURA',
                'commercial_reason_supplier' => 'SURA',
                'supplier_web_page' => 'www.sura.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'SURA',
                'supplier_email' => 'sura@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],


            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'SURA',
                'commercial_reason_supplier' => 'SURA',
                'supplier_web_page' => 'www.sura.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'SURA',
                'supplier_email' => 'sura@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['H'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '2',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'ARL Sura',
                'commercial_reason_supplier' => 'ARL Sura',
                'supplier_web_page' => 'www.arlsura.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'ARL Sura',
                'supplier_email' => 'arlsura@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Aseguradora de Vida Colseguros',
                'commercial_reason_supplier' => 'Aseguradora de Vida Colseguros',
                'supplier_web_page' => 'www.colseguros.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Aseguradora de Vida Colseguros',
                'supplier_email' => 'colseguros@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'BBVA Seguros de Vida',
                'commercial_reason_supplier' => 'BBVA Seguros de Vida',
                'supplier_web_page' => 'www.bbva.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'BBVA Seguros de Vida',
                'supplier_email' => 'bbvaseguros@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Colmena S.A. Seguros',
                'commercial_reason_supplier' => 'Colmena S.A. Seguros',
                'supplier_web_page' => 'www.colmena.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Colmena S.A. Seguros',
                'supplier_email' => 'colmena@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Colpatria Seguros S.A',
                'commercial_reason_supplier' => 'Colpatria Seguros S.A',
                'supplier_web_page' => 'www.colpatria.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Colpatria Seguros S.A',
                'supplier_email' => 'colpatria@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Compañia Agricola de Seguros de Vida',
                'commercial_reason_supplier' => 'Compañia Agricola de Seguros de Vida',
                'supplier_web_page' => 'www.agricola.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Compañia Agricola de Seguros de Vida',
                'supplier_email' => 'agricola@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Compañia Central de Seguros',
                'commercial_reason_supplier' => 'Compañia Central de Seguros',
                'supplier_web_page' => 'www.centralseguros.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Compañia Central de Seguros',
                'supplier_email' => 'centralseguros@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Compañia de Seguros de Vida Aurora S.A.',
                'commercial_reason_supplier' => 'Compañia de Seguros de Vida Aurora S.A.',
                'supplier_web_page' => 'www.aurora.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Compañia de Seguros de Vida Aurora S.A.',
                'supplier_email' => 'aurora@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'La Equidad Seguros',
                'commercial_reason_supplier' => 'La Equidad Seguros',
                'supplier_web_page' => 'www.laequidadseguros.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'La Equidad Seguros',
                'supplier_email' => 'laequidad@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'La Previsora Vida S.A.',
                'commercial_reason_supplier' => 'La Previsora Vida S.A.',
                'supplier_web_page' => 'www.previsora.gov.co',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'La Previsora Vida S.A.',
                'supplier_email' => 'previsora@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Liberty Seguros S.A.',
                'commercial_reason_supplier' => 'Liberty Seguros S.A.',
                'supplier_web_page' => 'www.libertyseguros.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Liberty Seguros S.A.',
                'supplier_email' => 'liberty@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Mapfre Colombia Vida Seguros S.A.',
                'commercial_reason_supplier' => 'Mapfre Colombia Vida Seguros S.A.',
                'supplier_web_page' => 'www.mapfre.com.co',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Mapfre Colombia Vida Seguros S.A.',
                'supplier_email' => 'mapfre@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Positiva Compañia de Seguros',
                'commercial_reason_supplier' => 'Positiva Compañia de Seguros',
                'supplier_web_page' => 'www.positiva.gov.co',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Positiva Compañia de Seguros',
                'supplier_email' => 'positiva@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Seguros Bolivar S.A.',
                'commercial_reason_supplier' => 'Seguros Bolivar S.A.',
                'supplier_web_page' => 'www.segurosbolivar.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Seguros Bolivar S.A.',
                'supplier_email' => 'bolivar@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Seguros de Vida ALFA S.A.',
                'commercial_reason_supplier' => 'Seguros de Vida ALFA S.A.',
                'supplier_web_page' => 'www.alfa.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Seguros de Vida ALFA S.A.',
                'supplier_email' => 'alfa@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Seguros de Vida del Estado',
                'commercial_reason_supplier' => 'Seguros de Vida del Estado',
                'supplier_web_page' => 'www.vidadelestado.gov.co',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Seguros de Vida del Estado',
                'supplier_email' => 'vidadelestado@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['A'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Caja Colombiana de Subsidio Familiar COLSUBSIDIO',
                'commercial_reason_supplier' => 'Caja Colombiana de Subsidio Familiar COLSUBSIDIO',
                'supplier_web_page' => 'www.comfamiliarcamacol.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Caja Colombiana de Subsidio Familiar COLSUBSIDIO',
                'supplier_email' => 'camacol@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['C'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Caja de Compensación Familiar AFIDRO',
                'commercial_reason_supplier' => 'Caja de Compensación Familiar AFIDRO',
                'supplier_web_page' => 'www.comfamiliarcamacol.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Caja de Compensación Familiar AFIDRO',
                'supplier_email' => 'camacol@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['C'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Caja de Compensación Familiar ASFAMILIAS',
                'commercial_reason_supplier' => 'Caja de Compensación Familiar ASFAMILIAS',
                'supplier_web_page' => 'www.comfamiliarcamacol.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Caja de Compensación Familiar ASFAMILIAS',
                'supplier_email' => 'camacol@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['C'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Caja Santandereana de Subsidio Familiar CAJASAN',
                'commercial_reason_supplier' => 'Caja Santandereana de Subsidio Familiar CAJASAN',
                'supplier_web_page' => 'www.comfamiliarcamacol.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Caja Santandereana de Subsidio Familiar CAJASAN',
                'supplier_email' => 'camacol@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['C'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Caja Colombiana de Subsidio Familiar COLSUBSIDIO',
                'commercial_reason_supplier' => 'Caja Colombiana de Subsidio Familiar COLSUBSIDIO',
                'supplier_web_page' => 'www.comfamiliarcamacol.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Caja Colombiana de Subsidio Familiar COLSUBSIDIO',
                'supplier_email' => 'camacol@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['C'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Caja de Compensación Familiar AFIDRO',
                'commercial_reason_supplier' => 'Caja de Compensación Familiar AFIDRO',
                'supplier_web_page' => 'www.comfamiliarcamacol.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Caja de Compensación Familiar AFIDRO',
                'supplier_email' => 'camacol@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['C'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Caja de Compensación Familiar ASFAMILIAS',
                'commercial_reason_supplier' => 'Caja de Compensación Familiar ASFAMILIAS',
                'supplier_web_page' => 'www.comfamiliarcamacol.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Caja de Compensación Familiar ASFAMILIAS',
                'supplier_email' => 'camacol@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['C'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Caja de Compensación Familiar CAFAM',
                'commercial_reason_supplier' => 'Caja de Compensación Familiar CAFAM',
                'supplier_web_page' => 'www.comfamiliarcamacol.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Caja de Compensación Familiar CAFAM',
                'supplier_email' => 'camacol@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['C'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Caja de Compensación Familiar CAJACOPI ATLANTICO',
                'commercial_reason_supplier' => 'Caja de Compensación Familiar CAJACOPI ATLANTICO',
                'supplier_web_page' => 'www.comfamiliarcamacol.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Caja de Compensación Familiar CAJACOPI ATLANTICO',
                'supplier_email' => 'camacol@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['C'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],

            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Caja Santandereana de Subsidio Familiar CAJASAN',
                'commercial_reason_supplier' => 'Caja Santandereana de Subsidio Familiar CAJASAN',
                'supplier_web_page' => 'www.comfamiliarcamacol.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Caja Santandereana de Subsidio Familiar CAJASAN',
                'supplier_email' => 'camacol@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['C'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Askandia S.A.',
                'commercial_reason_supplier' => 'Askandia S.A.',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Askandia S.A.',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Cesantías de Colombia S.A.',
                'commercial_reason_supplier' => 'Cesantías de Colombia S.A.',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Cesantías de Colombia S.A.',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Colfondos',
                'commercial_reason_supplier' => 'Colfondos',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Colfondos',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Colmena',
                'commercial_reason_supplier' => 'Colmena',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Colmena',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Colpatria',
                'commercial_reason_supplier' => 'Colpatria',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Colpatria',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Colpensiones',
                'commercial_reason_supplier' => 'Colpensiones',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Colpensiones',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Davivir S.A.',
                'commercial_reason_supplier' => 'Davivir S.A.',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Davivir S.A.',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Dinners S.A.',
                'commercial_reason_supplier' => 'Dinners S.A.',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Dinners S.A.',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Fondo Nacional del Ahorro',
                'commercial_reason_supplier' => 'Fondo Nacional del Ahorro',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Fondo Nacional del Ahorro',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Granfondo S.A.',
                'commercial_reason_supplier' => 'Granfondo S.A.',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Granfondo S.A.',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Invermañana',
                'commercial_reason_supplier' => 'Invermañana',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Invermañana',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Invertir',
                'commercial_reason_supplier' => 'Invertir',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Invertir',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Old Mutual',
                'commercial_reason_supplier' => 'Old Mutual',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Old Mutual',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Porvenir S.A.',
                'commercial_reason_supplier' => 'Porvenir S.A.',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Porvenir S.A.',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Protección S.A.',
                'commercial_reason_supplier' => 'Protección S.A.',
                'supplier_web_page' => 'www.pension.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Protección S.A.',
                'supplier_email' => 'pension@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['P'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Askandia S.A.',
                'commercial_reason_supplier' => 'Askandia S.A.',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Askandia S.A.',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Cesantías de Colombia S.A.',
                'commercial_reason_supplier' => 'Cesantías de Colombia S.A.',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Cesantías de Colombia S.A.',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Colfondos',
                'commercial_reason_supplier' => 'Colfondos',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Colfondos',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Colmena',
                'commercial_reason_supplier' => 'Colmena',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Colmena',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Colpatria',
                'commercial_reason_supplier' => 'Colpatria',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Colpatria',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Collayoffses',
                'commercial_reason_supplier' => 'Collayoffses',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Collayoffses',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Davivir S.A.',
                'commercial_reason_supplier' => 'Davivir S.A.',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Davivir S.A.',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Dinners S.A.',
                'commercial_reason_supplier' => 'Dinners S.A.',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Dinners S.A.',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Fondo Nacional del Ahorro',
                'commercial_reason_supplier' => 'Fondo Nacional del Ahorro',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Fondo Nacional del Ahorro',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Granfondo S.A.',
                'commercial_reason_supplier' => 'Granfondo S.A.',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Granfondo S.A.',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Invermañana',
                'commercial_reason_supplier' => 'Invermañana',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Invermañana',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Invertir',
                'commercial_reason_supplier' => 'Invertir',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Invertir',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Old Mutual',
                'commercial_reason_supplier' => 'Old Mutual',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Old Mutual',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Porvenir S.A.',
                'commercial_reason_supplier' => 'Porvenir S.A.',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Porvenir S.A.',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],
            [
                'identification' => 4,
                'nit' => $this->uniqueNit(),
                'company_name_provider' => 'Protección S.A.',
                'commercial_reason_supplier' => 'Protección S.A.',
                'supplier_web_page' => 'www.cesantias.com',
                'economic_activity' => 162,
                'products_and_services' => 7,
                'supplier_description' => 'Protección S.A.',
                'supplier_email' => 'cesantias@gmail.com',
                'supplier_phone' => 6063319414,
                'supplier_mobile' => 3218745624,
                'supplier_address' => 'Diagonal 27 A carrera 60 #45',
                'type_entity' => ['L'],
                'company_id' => 2,
                'code_company' => '001',
                'branch_id' => '01',
                'visibility' => 1,
            ],


        ];


        foreach ($entities as $entity) {
            Entity::create($entity);
        }
    }
}
