<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\VehicleBrand;

class VehicleBrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        VehicleBrand::insert([


            ['code_brand_vehicle' => '479', 'brand_vehicle' => 'A.J.S'],
            ['code_brand_vehicle' => '138', 'brand_vehicle' => 'ABARTH'],
            ['code_brand_vehicle' => '751', 'brand_vehicle' => 'AC'],
            ['code_brand_vehicle' => '413', 'brand_vehicle' => 'ACB'],
            ['code_brand_vehicle' => '480', 'brand_vehicle' => 'ACCESS'],
            ['code_brand_vehicle' => '310', 'brand_vehicle' => 'ACCURA'],
            ['code_brand_vehicle' => '379', 'brand_vehicle' => 'ACCURO'],
            ['code_brand_vehicle' => '481', 'brand_vehicle' => 'ACE'],
            ['code_brand_vehicle' => '482', 'brand_vehicle' => 'ACE MOTOR'],
            ['code_brand_vehicle' => '483', 'brand_vehicle' => 'ACM-ZHONG'],
            ['code_brand_vehicle' => '484', 'brand_vehicle' => 'ADDO'],
            ['code_brand_vehicle' => '1021', 'brand_vehicle' => 'ADVANCE'],
            ['code_brand_vehicle' => '928', 'brand_vehicle' => 'AEOLUS'],
            ['code_brand_vehicle' => '752', 'brand_vehicle' => 'AG'],
            ['code_brand_vehicle' => '232', 'brand_vehicle' => 'AGRALE'],
            ['code_brand_vehicle' => '458', 'brand_vehicle' => 'AKITA'],
            ['code_brand_vehicle' => '277', 'brand_vehicle' => 'AKT'],
            ['code_brand_vehicle' => '201', 'brand_vehicle' => 'ALEKO'],
            ['code_brand_vehicle' => '1061', 'brand_vehicle' => 'ALFA'],
            ['code_brand_vehicle' => '27', 'brand_vehicle' => 'ALFA ROMEO'],
            ['code_brand_vehicle' => '753', 'brand_vehicle' => 'ALFARO'],
            ['code_brand_vehicle' => '920', 'brand_vehicle' => 'ALL STATE'],
            ['code_brand_vehicle' => '485', 'brand_vehicle' => 'ALLAD'],
            ['code_brand_vehicle' => '921', 'brand_vehicle' => 'ALLARD'],
            ['code_brand_vehicle' => '486', 'brand_vehicle' => 'ALLIS CHALMERS'],
            ['code_brand_vehicle' => '487', 'brand_vehicle' => 'ALPS'],
            ['code_brand_vehicle' => '754', 'brand_vehicle' => 'ALVIS'],
            ['code_brand_vehicle' => '298', 'brand_vehicle' => 'AMC'],
            ['code_brand_vehicle' => '202', 'brand_vehicle' => 'AMERICAN MOTOR'],
            ['code_brand_vehicle' => '488', 'brand_vehicle' => 'AMM'],
            ['code_brand_vehicle' => '755', 'brand_vehicle' => 'AMPHICAR'],
            ['code_brand_vehicle' => '756', 'brand_vehicle' => 'AMPLE'],
            ['code_brand_vehicle' => '489', 'brand_vehicle' => 'AMW'],
            ['code_brand_vehicle' => '490', 'brand_vehicle' => 'AP PIAGGIO'],
            ['code_brand_vehicle' => '491', 'brand_vehicle' => 'APELCO GEN-MTO'],
            ['code_brand_vehicle' => '757', 'brand_vehicle' => 'APOLLO'],
            ['code_brand_vehicle' => '360', 'brand_vehicle' => 'APRILIA'],
            ['code_brand_vehicle' => '758', 'brand_vehicle' => 'ARABELLA'],
            ['code_brand_vehicle' => '970', 'brand_vehicle' => 'ARCTIC CAT'],
            ['code_brand_vehicle' => '343', 'brand_vehicle' => 'ARGO'],
            ['code_brand_vehicle' => '331', 'brand_vehicle' => 'ARIEL'],
            ['code_brand_vehicle' => '46', 'brand_vehicle' => 'ARO'],
            ['code_brand_vehicle' => '995', 'brand_vehicle' => 'ASA'],
            ['code_brand_vehicle' => '1062', 'brand_vehicle' => 'ASIA HERO'],
            ['code_brand_vehicle' => '63', 'brand_vehicle' => 'ASIA MOTOR'],
            ['code_brand_vehicle' => '759', 'brand_vehicle' => 'ASPT'],
            ['code_brand_vehicle' => '142', 'brand_vehicle' => 'ASTON MARTIN'],
            ['code_brand_vehicle' => '492', 'brand_vehicle' => 'ASTRA'],
            ['code_brand_vehicle' => '436', 'brand_vehicle' => 'ATM'],
            ['code_brand_vehicle' => '332', 'brand_vehicle' => 'ATV'],
            ['code_brand_vehicle' => '139', 'brand_vehicle' => 'AUDI'],
            ['code_brand_vehicle' => '318', 'brand_vehicle' => 'AUPACO'],
            ['code_brand_vehicle' => '73', 'brand_vehicle' => 'AUSTIN'],
            ['code_brand_vehicle' => '61', 'brand_vehicle' => 'AUTECO'],
            ['code_brand_vehicle' => '958', 'brand_vehicle' => 'AUTECO BAJAJ'],
            ['code_brand_vehicle' => '959', 'brand_vehicle' => 'AUTECO KYMCO'],
            ['code_brand_vehicle' => '981', 'brand_vehicle' => 'AUTECO VICTORY'],
            ['code_brand_vehicle' => '929', 'brand_vehicle' => 'AUTO BIANCHI'],
            ['code_brand_vehicle' => '143', 'brand_vehicle' => 'AUTO UNION'],
            ['code_brand_vehicle' => '74', 'brand_vehicle' => 'AUTOCAR'],
            ['code_brand_vehicle' => '356', 'brand_vehicle' => 'AUTOCAR WHITE'],
            ['code_brand_vehicle' => '760', 'brand_vehicle' => 'AUTOKRAFT'],
            ['code_brand_vehicle' => '986', 'brand_vehicle' => 'AVA MOTORS'],
            ['code_brand_vehicle' => '373', 'brand_vehicle' => 'AVANTI'],
            ['code_brand_vehicle' => '144', 'brand_vehicle' => 'AVIA'],
            ['code_brand_vehicle' => '1057', 'brand_vehicle' => 'AWS'],
            ['code_brand_vehicle' => '1007', 'brand_vehicle' => 'AWS - ALIEN WORK SHOP'],
            ['code_brand_vehicle' => '292', 'brand_vehicle' => 'AYCO'],
            ['code_brand_vehicle' => '761', 'brand_vehicle' => 'AYCO ZONGSHEN'],
            ['code_brand_vehicle' => '246', 'brand_vehicle' => 'B.S.A'],
            ['code_brand_vehicle' => '253', 'brand_vehicle' => 'BABETA'],
            ['code_brand_vehicle' => '493', 'brand_vehicle' => 'BACCIO'],
            ['code_brand_vehicle' => '762', 'brand_vehicle' => 'BAIKANCAR'],
            ['code_brand_vehicle' => '228', 'brand_vehicle' => 'BAJAJ'],
            ['code_brand_vehicle' => '763', 'brand_vehicle' => 'BAKER'],
            ['code_brand_vehicle' => '764', 'brand_vehicle' => 'BANTAM'],
            ['code_brand_vehicle' => '494', 'brand_vehicle' => 'BAODIAO'],
            ['code_brand_vehicle' => '495', 'brand_vehicle' => 'BARBER GREENE'],
            ['code_brand_vehicle' => '989', 'brand_vehicle' => 'BARHOG/DADYW'],
            ['code_brand_vehicle' => '156', 'brand_vehicle' => 'BARREIROS'],
            ['code_brand_vehicle' => '496', 'brand_vehicle' => 'BASHAN'],
            ['code_brand_vehicle' => '497', 'brand_vehicle' => 'BAUKEMA'],
            ['code_brand_vehicle' => '498', 'brand_vehicle' => 'BAW'],
            ['code_brand_vehicle' => '930', 'brand_vehicle' => 'BAW ZHAN QI'],
            ['code_brand_vehicle' => '153', 'brand_vehicle' => 'BEDFORD'],
            ['code_brand_vehicle' => '205', 'brand_vehicle' => 'BEIJING'],
            ['code_brand_vehicle' => '230', 'brand_vehicle' => 'BEISUTE'],
            ['code_brand_vehicle' => '104', 'brand_vehicle' => 'BELARUS'],
            ['code_brand_vehicle' => '712', 'brand_vehicle' => 'BELL'],
            ['code_brand_vehicle' => '765', 'brand_vehicle' => 'BENELLI'],
            ['code_brand_vehicle' => '1041', 'brand_vehicle' => 'BENLING'],
            ['code_brand_vehicle' => '150', 'brand_vehicle' => 'BENTLEY'],
            ['code_brand_vehicle' => '1053', 'brand_vehicle' => 'BERA'],
            ['code_brand_vehicle' => '154', 'brand_vehicle' => 'BERLIET'],
            ['code_brand_vehicle' => '337', 'brand_vehicle' => 'BEST'],
            ['code_brand_vehicle' => '499', 'brand_vehicle' => 'BETA'],
            ['code_brand_vehicle' => '500', 'brand_vehicle' => 'BETTER'],
            ['code_brand_vehicle' => '501', 'brand_vehicle' => 'BIANCHI'],
            ['code_brand_vehicle' => '459', 'brand_vehicle' => 'BIG'],
            ['code_brand_vehicle' => '502', 'brand_vehicle' => 'BIMOTA'],
            ['code_brand_vehicle' => '503', 'brand_vehicle' => 'BLAW KNOX'],
            ['code_brand_vehicle' => '504', 'brand_vehicle' => 'BLUE STONE'],
            ['code_brand_vehicle' => '435', 'brand_vehicle' => 'BMA'],
            ['code_brand_vehicle' => '28', 'brand_vehicle' => 'BMW'],
            ['code_brand_vehicle' => '505', 'brand_vehicle' => 'BOBCAT'],
            ['code_brand_vehicle' => '255', 'brand_vehicle' => 'BOCXOD'],
            ['code_brand_vehicle' => '506', 'brand_vehicle' => 'BODYWORK'],
            ['code_brand_vehicle' => '956', 'brand_vehicle' => 'BOMAG'],
            ['code_brand_vehicle' => '240', 'brand_vehicle' => 'BOMBARDIER'],
            ['code_brand_vehicle' => '507', 'brand_vehicle' => 'BONSER'],
            ['code_brand_vehicle' => '149', 'brand_vehicle' => 'BORG WARD'],
            ['code_brand_vehicle' => '367', 'brand_vehicle' => 'BORGO'],
            ['code_brand_vehicle' => '766', 'brand_vehicle' => 'BOSA BOSHIE NIKE'],
            ['code_brand_vehicle' => '985', 'brand_vehicle' => 'BOUE'],
            ['code_brand_vehicle' => '423', 'brand_vehicle' => 'BOURGET'],
            ['code_brand_vehicle' => '508', 'brand_vehicle' => 'BOUSER'],
            ['code_brand_vehicle' => '767', 'brand_vehicle' => 'BRAND'],
            ['code_brand_vehicle' => '509', 'brand_vehicle' => 'BRIDGE'],
            ['code_brand_vehicle' => '768', 'brand_vehicle' => 'BRISA'],
            ['code_brand_vehicle' => '390', 'brand_vehicle' => 'BRITISH'],
            ['code_brand_vehicle' => '148', 'brand_vehicle' => 'BROCK WAY'],
            ['code_brand_vehicle' => '22', 'brand_vehicle' => 'BRONCO'],
            ['code_brand_vehicle' => '510', 'brand_vehicle' => 'BRONTO'],
            ['code_brand_vehicle' => '407', 'brand_vehicle' => 'BRP/CAN AM'],
            ['code_brand_vehicle' => '511', 'brand_vehicle' => 'BUCYRUS'],
            ['code_brand_vehicle' => '364', 'brand_vehicle' => 'BUELL'],
            ['code_brand_vehicle' => '512', 'brand_vehicle' => 'BUGENI'],
            ['code_brand_vehicle' => '709', 'brand_vehicle' => 'BUGGY'],
            ['code_brand_vehicle' => '19', 'brand_vehicle' => 'BUICK'],
            ['code_brand_vehicle' => '254', 'brand_vehicle' => 'BULTACO'],
            ['code_brand_vehicle' => '151', 'brand_vehicle' => 'BUSSING'],
            ['code_brand_vehicle' => '393', 'brand_vehicle' => 'BUYANG'],
            ['code_brand_vehicle' => '313', 'brand_vehicle' => 'BYD'],
            ['code_brand_vehicle' => '1015', 'brand_vehicle' => 'BYVIN'],
            ['code_brand_vehicle' => '769', 'brand_vehicle' => 'C.C.C.'],
            ['code_brand_vehicle' => '20', 'brand_vehicle' => 'CADILLAC'],
            ['code_brand_vehicle' => '65', 'brand_vehicle' => 'CAGIVA'],
            ['code_brand_vehicle' => '770', 'brand_vehicle' => 'CAMC'],
            ['code_brand_vehicle' => '513', 'brand_vehicle' => 'CAMECO'],
            ['code_brand_vehicle' => '515', 'brand_vehicle' => 'CAPACITY'],
            ['code_brand_vehicle' => '256', 'brand_vehicle' => 'CARABELLA'],
            ['code_brand_vehicle' => '708', 'brand_vehicle' => 'CARBONER'],
            ['code_brand_vehicle' => '516', 'brand_vehicle' => 'CARIBE'],
            ['code_brand_vehicle' => '1037', 'brand_vehicle' => 'CARPATI'],
            ['code_brand_vehicle' => '517', 'brand_vehicle' => 'CARTER BROTHERS'],
            ['code_brand_vehicle' => '518', 'brand_vehicle' => 'CASE'],
            ['code_brand_vehicle' => '519', 'brand_vehicle' => 'CATERPILLAR'],
            ['code_brand_vehicle' => '520', 'brand_vehicle' => 'CATFLYER'],
            ['code_brand_vehicle' => '727', 'brand_vehicle' => 'CCITTA REBEL'],
            ['code_brand_vehicle' => '771', 'brand_vehicle' => 'CENTAURS'],
            ['code_brand_vehicle' => '748', 'brand_vehicle' => 'CEZET'],
            ['code_brand_vehicle' => '975', 'brand_vehicle' => 'CFMOTO'],
            ['code_brand_vehicle' => '521', 'brand_vehicle' => 'CHAMPION'],
            ['code_brand_vehicle' => '288', 'brand_vehicle' => 'CHANA'],
            ['code_brand_vehicle' => '281', 'brand_vehicle' => 'CHANGAN'],
            ['code_brand_vehicle' => '431', 'brand_vehicle' => 'CHANGFENG'],
            ['code_brand_vehicle' => '302', 'brand_vehicle' => 'CHANGHE'],
            ['code_brand_vehicle' => '296', 'brand_vehicle' => 'CHANGJIANG'],
            ['code_brand_vehicle' => '522', 'brand_vehicle' => 'CHANGLIN'],
            ['code_brand_vehicle' => '523', 'brand_vehicle' => 'CHARLY'],
            ['code_brand_vehicle' => '524', 'brand_vehicle' => 'CHARMING'],
            ['code_brand_vehicle' => '146', 'brand_vehicle' => 'CHECKER'],
            ['code_brand_vehicle' => '289', 'brand_vehicle' => 'CHERY'],
            ['code_brand_vehicle' => '1', 'brand_vehicle' => 'CHEVROLET'],
            ['code_brand_vehicle' => '772', 'brand_vehicle' => 'CHINA MOTORCYCLES'],
            ['code_brand_vehicle' => '525', 'brand_vehicle' => 'CHINSU'],
            ['code_brand_vehicle' => '773', 'brand_vehicle' => 'CHITUMA'],
            ['code_brand_vehicle' => '342', 'brand_vehicle' => 'CHONGQING'],
            ['code_brand_vehicle' => '526', 'brand_vehicle' => 'CHONGQING ZONGSHEN'],
            ['code_brand_vehicle' => '527', 'brand_vehicle' => 'CHONGQUING YUAN'],
            ['code_brand_vehicle' => '53', 'brand_vehicle' => 'CHRYSLER'],
            ['code_brand_vehicle' => '528', 'brand_vehicle' => 'CICLONE USA'],
            ['code_brand_vehicle' => '41', 'brand_vehicle' => 'CITROEN'],
            ['code_brand_vehicle' => '923', 'brand_vehicle' => 'CIXI KONCEO'],
            ['code_brand_vehicle' => '529', 'brand_vehicle' => 'CLARCK'],
            ['code_brand_vehicle' => '774', 'brand_vehicle' => 'CLAUSSON'],
            ['code_brand_vehicle' => '1039', 'brand_vehicle' => 'CLC MOTOR'],
            ['code_brand_vehicle' => '530', 'brand_vehicle' => 'CLUB CAR'],
            ['code_brand_vehicle' => '346', 'brand_vehicle' => 'CMC'],
            ['code_brand_vehicle' => '376', 'brand_vehicle' => 'CNENLON'],
            ['code_brand_vehicle' => '391', 'brand_vehicle' => 'COBRA'],
            ['code_brand_vehicle' => '222', 'brand_vehicle' => 'COLMOVE'],
            ['code_brand_vehicle' => '531', 'brand_vehicle' => 'COLOMBIANA DE CHASISES'],
            ['code_brand_vehicle' => '775', 'brand_vehicle' => 'COLT LANCER'],
            ['code_brand_vehicle' => '532', 'brand_vehicle' => 'COMANDO'],
            ['code_brand_vehicle' => '533', 'brand_vehicle' => 'COMET'],
            ['code_brand_vehicle' => '158', 'brand_vehicle' => 'COMMER'],
            ['code_brand_vehicle' => '534', 'brand_vehicle' => 'CONCORD'],
            ['code_brand_vehicle' => '776', 'brand_vehicle' => 'CONSUL'],
            ['code_brand_vehicle' => '118', 'brand_vehicle' => 'CORCEL'],
            ['code_brand_vehicle' => '312', 'brand_vehicle' => 'CPI'],
            ['code_brand_vehicle' => '777', 'brand_vehicle' => 'CROSLEY'],
            ['code_brand_vehicle' => '535', 'brand_vehicle' => 'CROWN'],
            ['code_brand_vehicle' => '778', 'brand_vehicle' => 'CRUISERN'],
            ['code_brand_vehicle' => '536', 'brand_vehicle' => 'CSEPEL-CUMMINS'],
            ['code_brand_vehicle' => '392', 'brand_vehicle' => 'CUSHMA'],
            ['code_brand_vehicle' => '537', 'brand_vehicle' => 'CUSTOM CHROME'],
            ['code_brand_vehicle' => '746', 'brand_vehicle' => 'CZ'],
            ['code_brand_vehicle' => '1032', 'brand_vehicle' => 'D LONG'],
            ['code_brand_vehicle' => '779', 'brand_vehicle' => 'DACC'],
            ['code_brand_vehicle' => '34', 'brand_vehicle' => 'DACIA'],
            ['code_brand_vehicle' => '1047', 'brand_vehicle' => 'DADI'],
            ['code_brand_vehicle' => '223', 'brand_vehicle' => 'DAELIM'],
            ['code_brand_vehicle' => '2', 'brand_vehicle' => 'DAEWOO'],
            ['code_brand_vehicle' => '780', 'brand_vehicle' => 'DAF'],
            ['code_brand_vehicle' => '460', 'brand_vehicle' => 'DAIFO'],
            ['code_brand_vehicle' => '42', 'brand_vehicle' => 'DAIHATSU'],
            ['code_brand_vehicle' => '781', 'brand_vehicle' => 'DAIMLER BENZ'],
            ['code_brand_vehicle' => '747', 'brand_vehicle' => 'DANUVIA'],
            ['code_brand_vehicle' => '782', 'brand_vehicle' => 'DASHA'],
            ['code_brand_vehicle' => '18', 'brand_vehicle' => 'DATSUN'],
            ['code_brand_vehicle' => '538', 'brand_vehicle' => 'DAVID BROWN'],
            ['code_brand_vehicle' => '242', 'brand_vehicle' => 'DAYANG'],
            ['code_brand_vehicle' => '539', 'brand_vehicle' => 'DAYUN'],
            ['code_brand_vehicle' => '971', 'brand_vehicle' => 'DCEC'],
            ['code_brand_vehicle' => '783', 'brand_vehicle' => 'DE LA HAYE'],
            ['code_brand_vehicle' => '728', 'brand_vehicle' => 'DELKRON'],
            ['code_brand_vehicle' => '85', 'brand_vehicle' => 'DELTA'],
            ['code_brand_vehicle' => '784', 'brand_vehicle' => 'DEMAG'],
            ['code_brand_vehicle' => '206', 'brand_vehicle' => 'DERBY'],
            ['code_brand_vehicle' => '75', 'brand_vehicle' => 'DESOTO'],
            ['code_brand_vehicle' => '729', 'brand_vehicle' => 'DESTA'],
            ['code_brand_vehicle' => '1027', 'brand_vehicle' => 'DETROIT'],
            ['code_brand_vehicle' => '1025', 'brand_vehicle' => 'DFA'],
            ['code_brand_vehicle' => '1134', 'brand_vehicle' => 'DFAC DONG FENG'],
            ['code_brand_vehicle' => '419', 'brand_vehicle' => 'DFM'],
            ['code_brand_vehicle' => '1050', 'brand_vehicle' => 'DFSK'],
            ['code_brand_vehicle' => '540', 'brand_vehicle' => 'DIAMOND'],
            ['code_brand_vehicle' => '541', 'brand_vehicle' => 'DIECI'],
            ['code_brand_vehicle' => '83', 'brand_vehicle' => 'DINA'],
            ['code_brand_vehicle' => '542', 'brand_vehicle' => 'DINAPAC'],
            ['code_brand_vehicle' => '279', 'brand_vehicle' => 'DINLI'],
            ['code_brand_vehicle' => '785', 'brand_vehicle' => 'DIVICO'],
            ['code_brand_vehicle' => '163', 'brand_vehicle' => 'DKW'],
            ['code_brand_vehicle' => '10', 'brand_vehicle' => 'DODGE'],
            ['code_brand_vehicle' => '543', 'brand_vehicle' => 'DOMINGUEZ'],
            ['code_brand_vehicle' => '448', 'brand_vehicle' => 'DONG FENG'],
            ['code_brand_vehicle' => '544', 'brand_vehicle' => 'DRESSER'],
            ['code_brand_vehicle' => '960', 'brand_vehicle' => 'DRESSER HAULPAK'],
            ['code_brand_vehicle' => '786', 'brand_vehicle' => 'DTV'],
            ['code_brand_vehicle' => '234', 'brand_vehicle' => 'DUCATI'],
            ['code_brand_vehicle' => '314', 'brand_vehicle' => 'DUKAR'],
            ['code_brand_vehicle' => '545', 'brand_vehicle' => 'DUST'],
            ['code_brand_vehicle' => '546', 'brand_vehicle' => 'DYNACOLT'],
            ['code_brand_vehicle' => '547', 'brand_vehicle' => 'E.D. ETNYRE'],
            ['code_brand_vehicle' => '548', 'brand_vehicle' => 'EAGLE'],
            ['code_brand_vehicle' => '549', 'brand_vehicle' => 'EAGLE AMC'],
            ['code_brand_vehicle' => '461', 'brand_vehicle' => 'EAGLE CARGO'],
            ['code_brand_vehicle' => '550', 'brand_vehicle' => 'EASTMAN'],
            ['code_brand_vehicle' => '121', 'brand_vehicle' => 'EBRO'],
            ['code_brand_vehicle' => '551', 'brand_vehicle' => 'EBTELECTRIC'],
            ['code_brand_vehicle' => '787', 'brand_vehicle' => 'ECO CITI'],
            ['code_brand_vehicle' => '165', 'brand_vehicle' => 'EDSEL'],
            ['code_brand_vehicle' => '451', 'brand_vehicle' => 'EKA MOTORS'],
            ['code_brand_vehicle' => '788', 'brand_vehicle' => 'EL SOL'],
            ['code_brand_vehicle' => '552', 'brand_vehicle' => 'ELECTRIC STAR ATV ENERGY'],
            ['code_brand_vehicle' => '789', 'brand_vehicle' => 'ELEPHANT POWER'],
            ['code_brand_vehicle' => '553', 'brand_vehicle' => 'ELGIN'],
            ['code_brand_vehicle' => '790', 'brand_vehicle' => 'EM'],
            ['code_brand_vehicle' => '554', 'brand_vehicle' => 'ENCAVA'],
            ['code_brand_vehicle' => '555', 'brand_vehicle' => 'ENERGY'],
            ['code_brand_vehicle' => '1017', 'brand_vehicle' => 'ENERGY MOTION'],
            ['code_brand_vehicle' => '1026', 'brand_vehicle' => 'E-ONE'],
            ['code_brand_vehicle' => '791', 'brand_vehicle' => 'EP'],
            ['code_brand_vehicle' => '556', 'brand_vehicle' => 'ERNEST GRUBER'],
            ['code_brand_vehicle' => '1049', 'brand_vehicle' => 'ESCORPIO'],
            ['code_brand_vehicle' => '996', 'brand_vehicle' => 'ESSEX'],
            ['code_brand_vehicle' => '792', 'brand_vehicle' => 'E-TON'],
            ['code_brand_vehicle' => '1023', 'brand_vehicle' => 'ETX'],
            ['code_brand_vehicle' => '557', 'brand_vehicle' => 'EUCLID'],
            ['code_brand_vehicle' => '558', 'brand_vehicle' => 'EVO'],
            ['code_brand_vehicle' => '559', 'brand_vehicle' => 'EXCELSIOR'],
            ['code_brand_vehicle' => '560', 'brand_vehicle' => 'EXPRESS'],
            ['code_brand_vehicle' => '793', 'brand_vehicle' => 'EZGO'],
            ['code_brand_vehicle' => '561', 'brand_vehicle' => 'EZLIFE'],
            ['code_brand_vehicle' => '794', 'brand_vehicle' => 'F.N'],
            ['code_brand_vehicle' => '200', 'brand_vehicle' => 'F.S.O.'],
            ['code_brand_vehicle' => '562', 'brand_vehicle' => 'FAILING'],
            ['code_brand_vehicle' => '563', 'brand_vehicle' => 'FAMY'],
            ['code_brand_vehicle' => '795', 'brand_vehicle' => 'FANTIC'],
            ['code_brand_vehicle' => '114', 'brand_vehicle' => 'FARGO'],
            ['code_brand_vehicle' => '796', 'brand_vehicle' => 'FARSPEED'],
            ['code_brand_vehicle' => '1069', 'brand_vehicle' => 'FASTER'],
            ['code_brand_vehicle' => '422', 'brand_vehicle' => 'FASTER 301 CHOIPERS'],
            ['code_brand_vehicle' => '171', 'brand_vehicle' => 'FAUN'],
            ['code_brand_vehicle' => '453', 'brand_vehicle' => 'FAW'],
            ['code_brand_vehicle' => '564', 'brand_vehicle' => 'FEDERAL'],
            ['code_brand_vehicle' => '566', 'brand_vehicle' => 'FENCHI'],
            ['code_brand_vehicle' => '1073', 'brand_vehicle' => 'FENIX'],
            ['code_brand_vehicle' => '29', 'brand_vehicle' => 'FERRARI'],
            ['code_brand_vehicle' => '3', 'brand_vehicle' => 'FIAT'],
            ['code_brand_vehicle' => '567', 'brand_vehicle' => 'FIAT ALLIS'],
            ['code_brand_vehicle' => '797', 'brand_vehicle' => 'FIBRAVAN'],
            ['code_brand_vehicle' => '568', 'brand_vehicle' => 'FIORI'],
            ['code_brand_vehicle' => '348', 'brand_vehicle' => 'FIRENZE'],
            ['code_brand_vehicle' => '966', 'brand_vehicle' => 'FIVER'],
            ['code_brand_vehicle' => '798', 'brand_vehicle' => 'FLEXIBLE'],
            ['code_brand_vehicle' => '931', 'brand_vehicle' => 'FODEN'],
            ['code_brand_vehicle' => '569', 'brand_vehicle' => 'FONA'],
            ['code_brand_vehicle' => '54', 'brand_vehicle' => 'FORD'],
            ['code_brand_vehicle' => '167', 'brand_vehicle' => 'FORDSON'],
            ['code_brand_vehicle' => '570', 'brand_vehicle' => 'FORMULA'],
            ['code_brand_vehicle' => '375', 'brand_vehicle' => 'FOTON'],
            ['code_brand_vehicle' => '799', 'brand_vehicle' => 'FRAZER'],
            ['code_brand_vehicle' => '169', 'brand_vehicle' => 'FREIGHTLINER'],
            ['code_brand_vehicle' => '405', 'brand_vehicle' => 'FRIBEST'],
            ['code_brand_vehicle' => '462', 'brand_vehicle' => 'FUDEPAI'],
            ['code_brand_vehicle' => '800', 'brand_vehicle' => 'FULDAMOBIL'],
            ['code_brand_vehicle' => '713', 'brand_vehicle' => 'FURUKAWA'],
            ['code_brand_vehicle' => '338', 'brand_vehicle' => 'FUTONG'],
            ['code_brand_vehicle' => '571', 'brand_vehicle' => 'FUTURE'],
            ['code_brand_vehicle' => '444', 'brand_vehicle' => 'FUXIANDA'],
            ['code_brand_vehicle' => '977', 'brand_vehicle' => 'FUXIN'],
            ['code_brand_vehicle' => '572', 'brand_vehicle' => 'FWD'],
            ['code_brand_vehicle' => '573', 'brand_vehicle' => 'FYM'],
            ['code_brand_vehicle' => '362', 'brand_vehicle' => 'GALARDI'],
            ['code_brand_vehicle' => '1013', 'brand_vehicle' => 'GALAXI'],
            ['code_brand_vehicle' => '574', 'brand_vehicle' => 'GALION'],
            ['code_brand_vehicle' => '1072', 'brand_vehicle' => 'GAME'],
            ['code_brand_vehicle' => '280', 'brand_vehicle' => 'GAS GAS'],
            ['code_brand_vehicle' => '44', 'brand_vehicle' => 'GAZ'],
            ['code_brand_vehicle' => '575', 'brand_vehicle' => 'GAZELLE'],
            ['code_brand_vehicle' => '1075', 'brand_vehicle' => 'GBMCO'],
            ['code_brand_vehicle' => '287', 'brand_vehicle' => 'GEELY'],
            ['code_brand_vehicle' => '576', 'brand_vehicle' => 'GENERAL'],
            ['code_brand_vehicle' => '350', 'brand_vehicle' => 'GENESIS'],
            ['code_brand_vehicle' => '84', 'brand_vehicle' => 'GEO'],
            ['code_brand_vehicle' => '801', 'brand_vehicle' => 'GERLING'],
            ['code_brand_vehicle' => '577', 'brand_vehicle' => 'GHA-2'],
            ['code_brand_vehicle' => '251', 'brand_vehicle' => 'GILERA'],
            ['code_brand_vehicle' => '91', 'brand_vehicle' => 'GMC'],
            ['code_brand_vehicle' => '749', 'brand_vehicle' => 'GO KART'],
            ['code_brand_vehicle' => '802', 'brand_vehicle' => 'GOGOMOVIL'],
            ['code_brand_vehicle' => '578', 'brand_vehicle' => 'GOLDEN DRAGON'],
            ['code_brand_vehicle' => '306', 'brand_vehicle' => 'GOMOTOR'],
            ['code_brand_vehicle' => '463', 'brand_vehicle' => 'GONOW'],
            ['code_brand_vehicle' => '803', 'brand_vehicle' => 'GRAHAN PAUGE'],
            ['code_brand_vehicle' => '580', 'brand_vehicle' => 'GRAM'],
            ['code_brand_vehicle' => '804', 'brand_vehicle' => 'GRANE CARRIER'],
            ['code_brand_vehicle' => '349', 'brand_vehicle' => 'GREAT WALL'],
            ['code_brand_vehicle' => '999', 'brand_vehicle' => 'GREENWHEEL'],
            ['code_brand_vehicle' => '805', 'brand_vehicle' => 'GREMLIN'],
            ['code_brand_vehicle' => '581', 'brand_vehicle' => 'GROVE'],
            ['code_brand_vehicle' => '806', 'brand_vehicle' => 'GRUBER'],
            ['code_brand_vehicle' => '1052', 'brand_vehicle' => 'GSMOON'],
            ['code_brand_vehicle' => '394', 'brand_vehicle' => 'GURGEL'],
            ['code_brand_vehicle' => '464', 'brand_vehicle' => 'GUZZI'],
            ['code_brand_vehicle' => '1076', 'brand_vehicle' => 'GVMCO'],
            ['code_brand_vehicle' => '445', 'brand_vehicle' => 'GWM'],
            ['code_brand_vehicle' => '283', 'brand_vehicle' => 'HAFEI'],
            ['code_brand_vehicle' => '402', 'brand_vehicle' => 'HAILI'],
            ['code_brand_vehicle' => '1001', 'brand_vehicle' => 'HAIMA'],
            ['code_brand_vehicle' => '807', 'brand_vehicle' => 'HALLA'],
            ['code_brand_vehicle' => '329', 'brand_vehicle' => 'HALLEY'],
            ['code_brand_vehicle' => '414', 'brand_vehicle' => 'HAMMER HEAD'],
            ['code_brand_vehicle' => '1044', 'brand_vehicle' => 'HANLING'],
            ['code_brand_vehicle' => '924', 'brand_vehicle' => 'HAOJIANG'],
            ['code_brand_vehicle' => '385', 'brand_vehicle' => 'HAOJIN'],
            ['code_brand_vehicle' => '808', 'brand_vehicle' => 'HAOJUE'],
            ['code_brand_vehicle' => '427', 'brand_vehicle' => 'HAOMEN'],
            ['code_brand_vehicle' => '1034', 'brand_vehicle' => 'HAORI'],
            ['code_brand_vehicle' => '583', 'brand_vehicle' => 'HARDLAND'],
            ['code_brand_vehicle' => '60', 'brand_vehicle' => 'HARLEY DAVIDSON'],
            ['code_brand_vehicle' => '584', 'brand_vehicle' => 'HARMON'],
            ['code_brand_vehicle' => '585', 'brand_vehicle' => 'HELI'],
            ['code_brand_vehicle' => '207', 'brand_vehicle' => 'HENRY J'],
            ['code_brand_vehicle' => '979', 'brand_vehicle' => 'HENSIM'],
            ['code_brand_vehicle' => '72', 'brand_vehicle' => 'HERO'],
            ['code_brand_vehicle' => '586', 'brand_vehicle' => 'HERRAGRO'],
            ['code_brand_vehicle' => '809', 'brand_vehicle' => 'HESTIA'],
            ['code_brand_vehicle' => '973', 'brand_vehicle' => 'HIGER'],
            ['code_brand_vehicle' => '587', 'brand_vehicle' => 'HILIGHT'],
            ['code_brand_vehicle' => '176', 'brand_vehicle' => 'HILLMAN'],
            ['code_brand_vehicle' => '76', 'brand_vehicle' => 'HINO'],
            ['code_brand_vehicle' => '588', 'brand_vehicle' => 'HISTER'],
            ['code_brand_vehicle' => '1004', 'brand_vehicle' => 'HISUN TIGER'],
            ['code_brand_vehicle' => '589', 'brand_vehicle' => 'HITACHI'],
            ['code_brand_vehicle' => '175', 'brand_vehicle' => 'HOHOLDEN'],
            ['code_brand_vehicle' => '21', 'brand_vehicle' => 'HONDA'],
            ['code_brand_vehicle' => '922', 'brand_vehicle' => 'HONGXING NOBLE'],
            ['code_brand_vehicle' => '311', 'brand_vehicle' => 'HONLEI'],
            ['code_brand_vehicle' => '1058', 'brand_vehicle' => 'HONOR'],
            ['code_brand_vehicle' => '964', 'brand_vehicle' => 'HOREX'],
            ['code_brand_vehicle' => '744', 'brand_vehicle' => 'HORNET'],
            ['code_brand_vehicle' => '810', 'brand_vehicle' => 'HOSIN SOPORTER'],
            ['code_brand_vehicle' => '1018', 'brand_vehicle' => 'HPOWER'],
            ['code_brand_vehicle' => '112', 'brand_vehicle' => 'HUALI'],
            ['code_brand_vehicle' => '983', 'brand_vehicle' => 'HUALIN'],
            ['code_brand_vehicle' => '1046', 'brand_vehicle' => 'HUANGHAI'],
            ['code_brand_vehicle' => '811', 'brand_vehicle' => 'HUAWIN'],
            ['code_brand_vehicle' => '590', 'brand_vehicle' => 'HUBER'],
            ['code_brand_vehicle' => '178', 'brand_vehicle' => 'HUDSON'],
            ['code_brand_vehicle' => '395', 'brand_vehicle' => 'HUMBERT'],
            ['code_brand_vehicle' => '226', 'brand_vehicle' => 'HUMMER'],
            ['code_brand_vehicle' => '591', 'brand_vehicle' => 'HUMMER ZONGSHEN'],
            ['code_brand_vehicle' => '1029', 'brand_vehicle' => 'HUNTER'],
            ['code_brand_vehicle' => '344', 'brand_vehicle' => 'HUONNIAO'],
            ['code_brand_vehicle' => '812', 'brand_vehicle' => 'HUPMOBILE'],
            ['code_brand_vehicle' => '813', 'brand_vehicle' => 'HUSABERG'],
            ['code_brand_vehicle' => '89', 'brand_vehicle' => 'HUSQVARNA'],
            ['code_brand_vehicle' => '425', 'brand_vehicle' => 'HY MOTOR'],
            ['code_brand_vehicle' => '86', 'brand_vehicle' => 'HYOSUNG'],
            ['code_brand_vehicle' => '592', 'brand_vehicle' => 'HYSTER'],
            ['code_brand_vehicle' => '208', 'brand_vehicle' => 'HYUNDAI'],
            ['code_brand_vehicle' => '814', 'brand_vehicle' => 'I.M.V'],
            ['code_brand_vehicle' => '179', 'brand_vehicle' => 'IFA'],
            ['code_brand_vehicle' => '932', 'brand_vehicle' => 'IFG'],
            ['code_brand_vehicle' => '815', 'brand_vehicle' => 'IKARUS'],
            ['code_brand_vehicle' => '593', 'brand_vehicle' => 'INCALCU'],
            ['code_brand_vehicle' => '250', 'brand_vehicle' => 'INDIAN'],
            ['code_brand_vehicle' => '594', 'brand_vehicle' => 'INDIAN CHIEF'],
            ['code_brand_vehicle' => '1074', 'brand_vehicle' => 'INDUSTRY'],
            ['code_brand_vehicle' => '241', 'brand_vehicle' => 'INFINITI'],
            ['code_brand_vehicle' => '595', 'brand_vehicle' => 'INGERSOLL RAND'],
            ['code_brand_vehicle' => '62', 'brand_vehicle' => 'INTERNATIONAL'],
            ['code_brand_vehicle' => '596', 'brand_vehicle' => 'INVICTUS MOTORS'],
            ['code_brand_vehicle' => '465', 'brand_vehicle' => 'IOTA'],
            ['code_brand_vehicle' => '714', 'brand_vehicle' => 'ISEKI'],
            ['code_brand_vehicle' => '994', 'brand_vehicle' => 'ISHIMOTO'],
            ['code_brand_vehicle' => '816', 'brand_vehicle' => 'ISLO'],
            ['code_brand_vehicle' => '181', 'brand_vehicle' => 'ISO'],
            ['code_brand_vehicle' => '49', 'brand_vehicle' => 'ISUZU'],
            ['code_brand_vehicle' => '457', 'brand_vehicle' => 'ITALIKA'],
            ['code_brand_vehicle' => '248', 'brand_vehicle' => 'ITALJET'],
            ['code_brand_vehicle' => '68', 'brand_vehicle' => 'IVECO'],
            ['code_brand_vehicle' => '366', 'brand_vehicle' => 'JAC'],
            ['code_brand_vehicle' => '597', 'brand_vehicle' => 'JACKEL'],
            ['code_brand_vehicle' => '33', 'brand_vehicle' => 'JAGUAR'],
            ['code_brand_vehicle' => '598', 'brand_vehicle' => 'JAINSHE'],
            ['code_brand_vehicle' => '1059', 'brand_vehicle' => 'JAUNCE'],
            ['code_brand_vehicle' => '599', 'brand_vehicle' => 'JAVELINI'],
            ['code_brand_vehicle' => '209', 'brand_vehicle' => 'JAWA'],
            ['code_brand_vehicle' => '1024', 'brand_vehicle' => 'JBC'],
            ['code_brand_vehicle' => '386', 'brand_vehicle' => 'JBWCO'],
            ['code_brand_vehicle' => '600', 'brand_vehicle' => 'JCB'],
            ['code_brand_vehicle' => '50', 'brand_vehicle' => 'JEEP'],
            ['code_brand_vehicle' => '297', 'brand_vehicle' => 'JET UKM'],
            ['code_brand_vehicle' => '291', 'brand_vehicle' => 'JEZHANG'],
            ['code_brand_vehicle' => '601', 'brand_vehicle' => 'JHON DEERE'],
            ['code_brand_vehicle' => '602', 'brand_vehicle' => 'JHONSTON'],
            ['code_brand_vehicle' => '1022', 'brand_vehicle' => 'JIAJUE'],
            ['code_brand_vehicle' => '108', 'brand_vehicle' => 'JIALING'],
            ['code_brand_vehicle' => '466', 'brand_vehicle' => 'JIANG'],
            ['code_brand_vehicle' => '603', 'brand_vehicle' => 'JIANG CHANGHE'],
            ['code_brand_vehicle' => '604', 'brand_vehicle' => 'JIANGLING'],
            ['code_brand_vehicle' => '605', 'brand_vehicle' => 'JIANGNAN GLOW'],
            ['code_brand_vehicle' => '320', 'brand_vehicle' => 'JIANGSU'],
            ['code_brand_vehicle' => '606', 'brand_vehicle' => 'JIANGSU KINROAD XINTIAN'],
            ['code_brand_vehicle' => '1008', 'brand_vehicle' => 'JIANGSU SINSKI'],
            ['code_brand_vehicle' => '607', 'brand_vehicle' => 'JIANGXI CAMPELL CO.'],
            ['code_brand_vehicle' => '224', 'brand_vehicle' => 'JIANSHE'],
            ['code_brand_vehicle' => '1016', 'brand_vehicle' => 'JIASHITE'],
            ['code_brand_vehicle' => '817', 'brand_vehicle' => 'JIN JIAN'],
            ['code_brand_vehicle' => '467', 'brand_vehicle' => 'JIN JIN'],
            ['code_brand_vehicle' => '309', 'brand_vehicle' => 'JINAN'],
            ['code_brand_vehicle' => '730', 'brand_vehicle' => 'JINBEI'],
            ['code_brand_vehicle' => '123', 'brand_vehicle' => 'JINCHENG'],
            ['code_brand_vehicle' => '439', 'brand_vehicle' => 'JINFENG'],
            ['code_brand_vehicle' => '608', 'brand_vehicle' => 'JINGLONG'],
            ['code_brand_vehicle' => '731', 'brand_vehicle' => 'JINGPIN'],
            ['code_brand_vehicle' => '933', 'brand_vehicle' => 'JINLING'],
            ['code_brand_vehicle' => '609', 'brand_vehicle' => 'JIRY SISU'],
            ['code_brand_vehicle' => '1020', 'brand_vehicle' => 'JLC'],
            ['code_brand_vehicle' => '388', 'brand_vehicle' => 'JMC'],
            ['code_brand_vehicle' => '335', 'brand_vehicle' => 'JMSTAR'],
            ['code_brand_vehicle' => '365', 'brand_vehicle' => 'JONWAY'],
            ['code_brand_vehicle' => '372', 'brand_vehicle' => 'JOYNER'],
            ['code_brand_vehicle' => '818', 'brand_vehicle' => 'JUMBO DE LLANTAS'],
            ['code_brand_vehicle' => '1066', 'brand_vehicle' => 'JUNCHI'],
            ['code_brand_vehicle' => '324', 'brand_vehicle' => 'JUNESUN'],
            ['code_brand_vehicle' => '819', 'brand_vehicle' => 'JUNGHEINRICH'],
            ['code_brand_vehicle' => '732', 'brand_vehicle' => 'KAELBLE'],
            ['code_brand_vehicle' => '611', 'brand_vehicle' => 'KAISER'],
            ['code_brand_vehicle' => '612', 'brand_vehicle' => 'KALMAR'],
            ['code_brand_vehicle' => '119', 'brand_vehicle' => 'KAMAZ'],
            ['code_brand_vehicle' => '820', 'brand_vehicle' => 'KANABIS'],
            ['code_brand_vehicle' => '443', 'brand_vehicle' => 'KANCHAO'],
            ['code_brand_vehicle' => '434', 'brand_vehicle' => 'KANDI'],
            ['code_brand_vehicle' => '821', 'brand_vehicle' => 'KARPETAN'],
            ['code_brand_vehicle' => '715', 'brand_vehicle' => 'KATO'],
            ['code_brand_vehicle' => '57', 'brand_vehicle' => 'KAWASAKI'],
            ['code_brand_vehicle' => '317', 'brand_vehicle' => 'KAYAK'],
            ['code_brand_vehicle' => '304', 'brand_vehicle' => 'KAZUKI'],
            ['code_brand_vehicle' => '613', 'brand_vehicle' => 'KAZUMA'],
            ['code_brand_vehicle' => '353', 'brand_vehicle' => 'KEEWAY'],
            ['code_brand_vehicle' => '67', 'brand_vehicle' => 'KENWORTH'],
            ['code_brand_vehicle' => '997', 'brand_vehicle' => 'KHOOBRA'],
            ['code_brand_vehicle' => '5', 'brand_vehicle' => 'KIA'],
            ['code_brand_vehicle' => '184', 'brand_vehicle' => 'KIAMASTER'],
            ['code_brand_vehicle' => '239', 'brand_vehicle' => 'KINETIC'],
            ['code_brand_vehicle' => '614', 'brand_vehicle' => 'KING LINFT'],
            ['code_brand_vehicle' => '1048', 'brand_vehicle' => 'KING LONG'],
            ['code_brand_vehicle' => '433', 'brand_vehicle' => 'KINGLONG HIGER'],
            ['code_brand_vehicle' => '295', 'brand_vehicle' => 'KINLON'],
            ['code_brand_vehicle' => '327', 'brand_vehicle' => 'KINROAD'],
            ['code_brand_vehicle' => '357', 'brand_vehicle' => 'KINROAD XINTIAN'],
            ['code_brand_vehicle' => '616', 'brand_vehicle' => 'KITOMI'],
            ['code_brand_vehicle' => '1028', 'brand_vehicle' => 'KMO'],
            ['code_brand_vehicle' => '716', 'brand_vehicle' => 'KOBELCO'],
            ['code_brand_vehicle' => '822', 'brand_vehicle' => 'KOMAR'],
            ['code_brand_vehicle' => '617', 'brand_vehicle' => 'KOMATSU'],
            ['code_brand_vehicle' => '618', 'brand_vehicle' => 'KONCEO'],
            ['code_brand_vehicle' => '823', 'brand_vehicle' => 'KONTIO SISO'],
            ['code_brand_vehicle' => '276', 'brand_vehicle' => 'KOREMOTO'],
            ['code_brand_vehicle' => '619', 'brand_vehicle' => 'KRAZ'],
            ['code_brand_vehicle' => '824', 'brand_vehicle' => 'KROSON SOPORTES'],
            ['code_brand_vehicle' => '620', 'brand_vehicle' => 'KRUPP'],
            ['code_brand_vehicle' => '227', 'brand_vehicle' => 'KTM'],
            ['code_brand_vehicle' => '97', 'brand_vehicle' => 'KUBOTA'],
            ['code_brand_vehicle' => '322', 'brand_vehicle' => 'KYMCO'],
            ['code_brand_vehicle' => '468', 'brand_vehicle' => 'KYNLON'],
            ['code_brand_vehicle' => '345', 'brand_vehicle' => 'KYOTO'],
            ['code_brand_vehicle' => '825', 'brand_vehicle' => 'L.A.I'],
            ['code_brand_vehicle' => '733', 'brand_vehicle' => 'L.R.'],
            ['code_brand_vehicle' => '396', 'brand_vehicle' => 'LA SALLE'],
            ['code_brand_vehicle' => '35', 'brand_vehicle' => 'LADA'],
            ['code_brand_vehicle' => '185', 'brand_vehicle' => 'LAMBORGHINI'],
            ['code_brand_vehicle' => '69', 'brand_vehicle' => 'LAMBRETA'],
            ['code_brand_vehicle' => '14', 'brand_vehicle' => 'LANCIA'],
            ['code_brand_vehicle' => '51', 'brand_vehicle' => 'LAND ROVER'],
            ['code_brand_vehicle' => '1056', 'brand_vehicle' => 'LANGQING'],
            ['code_brand_vehicle' => '717', 'brand_vehicle' => 'LEE BOY'],
            ['code_brand_vehicle' => '826', 'brand_vehicle' => 'LEE SCUSTÃ“N COACHES'],
            ['code_brand_vehicle' => '210', 'brand_vehicle' => 'LEXUS'],
            ['code_brand_vehicle' => '827', 'brand_vehicle' => 'LEY LAND'],
            ['code_brand_vehicle' => '828', 'brand_vehicle' => 'LIANMEI MOTOR'],
            ['code_brand_vehicle' => '829', 'brand_vehicle' => 'LIBA MOTOR'],
            ['code_brand_vehicle' => '965', 'brand_vehicle' => 'LIEBHERR'],
            ['code_brand_vehicle' => '275', 'brand_vehicle' => 'LIFAN'],
            ['code_brand_vehicle' => '734', 'brand_vehicle' => 'LIMA'],
            ['code_brand_vehicle' => '621', 'brand_vehicle' => 'LINCOLN'],
            ['code_brand_vehicle' => '830', 'brand_vehicle' => 'LINDE'],
            ['code_brand_vehicle' => '831', 'brand_vehicle' => 'LINGBEN'],
            ['code_brand_vehicle' => '1009', 'brand_vehicle' => 'LINGKEN'],
            ['code_brand_vehicle' => '284', 'brand_vehicle' => 'LINHAI'],
            ['code_brand_vehicle' => '718', 'brand_vehicle' => 'LINK BELT'],
            ['code_brand_vehicle' => '622', 'brand_vehicle' => 'LITTLE GIANT'],
            ['code_brand_vehicle' => '623', 'brand_vehicle' => 'LIUGONG'],
            ['code_brand_vehicle' => '934', 'brand_vehicle' => 'LLOYD'],
            ['code_brand_vehicle' => '271', 'brand_vehicle' => 'LML'],
            ['code_brand_vehicle' => '624', 'brand_vehicle' => 'LMX'],
            ['code_brand_vehicle' => '303', 'brand_vehicle' => 'LONCIN'],
            ['code_brand_vehicle' => '625', 'brand_vehicle' => 'LORAIN'],
            ['code_brand_vehicle' => '188', 'brand_vehicle' => 'LOTUS'],
            ['code_brand_vehicle' => '1031', 'brand_vehicle' => 'LOVOL'],
            ['code_brand_vehicle' => '935', 'brand_vehicle' => 'LUAZ'],
            ['code_brand_vehicle' => '1038', 'brand_vehicle' => 'LUCKY LION'],
            ['code_brand_vehicle' => '832', 'brand_vehicle' => 'M.G.U'],
            ['code_brand_vehicle' => '64', 'brand_vehicle' => 'MACK'],
            ['code_brand_vehicle' => '626', 'brand_vehicle' => 'MADVAC'],
            ['code_brand_vehicle' => '191', 'brand_vehicle' => 'MAGIRUS DEUTZ'],
            ['code_brand_vehicle' => '252', 'brand_vehicle' => 'MAHINDRA'],
            ['code_brand_vehicle' => '1040', 'brand_vehicle' => 'MAHINDRA DURO'],
            ['code_brand_vehicle' => '969', 'brand_vehicle' => 'MALAGUTI'],
            ['code_brand_vehicle' => '190', 'brand_vehicle' => 'MAN'],
            ['code_brand_vehicle' => '627', 'brand_vehicle' => 'MANCO'],
            ['code_brand_vehicle' => '991', 'brand_vehicle' => 'MANZINI'],
            ['code_brand_vehicle' => '833', 'brand_vehicle' => 'MARCHETTI'],
            ['code_brand_vehicle' => '719', 'brand_vehicle' => 'MARINI'],
            ['code_brand_vehicle' => '628', 'brand_vehicle' => 'MARMON'],
            ['code_brand_vehicle' => '834', 'brand_vehicle' => 'MARQUASS'],
            ['code_brand_vehicle' => '629', 'brand_vehicle' => 'MARUTI'],
            ['code_brand_vehicle' => '750', 'brand_vehicle' => 'MASERATI'],
            ['code_brand_vehicle' => '630', 'brand_vehicle' => 'MASEY FERGUSON'],
            ['code_brand_vehicle' => '835', 'brand_vehicle' => 'MASTER CRAFT'],
            ['code_brand_vehicle' => '720', 'brand_vehicle' => 'MATBRO'],
            ['code_brand_vehicle' => '631', 'brand_vehicle' => 'MATCHELSS'],
            ['code_brand_vehicle' => '285', 'brand_vehicle' => 'MAX MOTOR'],
            ['code_brand_vehicle' => '836', 'brand_vehicle' => 'MAXWELL'],
            ['code_brand_vehicle' => '837', 'brand_vehicle' => 'MAYFLOWER'],
            ['code_brand_vehicle' => '961', 'brand_vehicle' => 'MAZ'],
            ['code_brand_vehicle' => '838', 'brand_vehicle' => 'MAZAKI'],
            ['code_brand_vehicle' => '6', 'brand_vehicle' => 'MAZDA'],
            ['code_brand_vehicle' => '633', 'brand_vehicle' => 'MC CORMICK'],
            ['code_brand_vehicle' => '319', 'brand_vehicle' => 'MC MOTOR'],
            ['code_brand_vehicle' => '437', 'brand_vehicle' => 'MD BIKES'],
            ['code_brand_vehicle' => '30', 'brand_vehicle' => 'MERCEDES BENZ'],
            ['code_brand_vehicle' => '47', 'brand_vehicle' => 'MERCURY'],
            ['code_brand_vehicle' => '634', 'brand_vehicle' => 'MERLO'],
            ['code_brand_vehicle' => '635', 'brand_vehicle' => 'META'],
            ['code_brand_vehicle' => '235', 'brand_vehicle' => 'MG'],
            ['code_brand_vehicle' => '839', 'brand_vehicle' => 'MG MIDGET'],
            ['code_brand_vehicle' => '636', 'brand_vehicle' => 'MGB'],
            ['code_brand_vehicle' => '1070', 'brand_vehicle' => 'MIKILON'],
            ['code_brand_vehicle' => '637', 'brand_vehicle' => 'MINI'],
            ['code_brand_vehicle' => '300', 'brand_vehicle' => 'MINI POCKET BIKE'],
            ['code_brand_vehicle' => '212', 'brand_vehicle' => 'MINICORD'],
            ['code_brand_vehicle' => '71', 'brand_vehicle' => 'MINSK'],
            ['code_brand_vehicle' => '23', 'brand_vehicle' => 'MITSUBISHI'],
            ['code_brand_vehicle' => '993', 'brand_vehicle' => 'MITSUBISHI FUSO'],
            ['code_brand_vehicle' => '840', 'brand_vehicle' => 'MNHCK'],
            ['code_brand_vehicle' => '735', 'brand_vehicle' => 'MOBILIFT'],
            ['code_brand_vehicle' => '841', 'brand_vehicle' => 'MOBYLESTTE'],
            ['code_brand_vehicle' => '1068', 'brand_vehicle' => 'MOFFETT'],
            ['code_brand_vehicle' => '842', 'brand_vehicle' => 'MONIKA'],
            ['code_brand_vehicle' => '113', 'brand_vehicle' => 'MONTESA'],
            ['code_brand_vehicle' => '328', 'brand_vehicle' => 'MORGAN'],
            ['code_brand_vehicle' => '127', 'brand_vehicle' => 'MORRIS'],
            ['code_brand_vehicle' => '192', 'brand_vehicle' => 'MOSKOVICH'],
            ['code_brand_vehicle' => '469', 'brand_vehicle' => 'MOTO MORINI'],
            ['code_brand_vehicle' => '638', 'brand_vehicle' => 'MOTOBECAME'],
            ['code_brand_vehicle' => '843', 'brand_vehicle' => 'MOTOCARRIER'],
            ['code_brand_vehicle' => '257', 'brand_vehicle' => 'MOTOGUZZI'],
            ['code_brand_vehicle' => '990', 'brand_vehicle' => 'MOTOKART'],
            ['code_brand_vehicle' => '358', 'brand_vehicle' => 'MOTOR UNO'],
            ['code_brand_vehicle' => '962', 'brand_vehicle' => 'MOXI'],
            ['code_brand_vehicle' => '421', 'brand_vehicle' => 'MTK'],
            ['code_brand_vehicle' => '844', 'brand_vehicle' => 'MUDAN'],
            ['code_brand_vehicle' => '845', 'brand_vehicle' => 'MUHCK'],
            ['code_brand_vehicle' => '195', 'brand_vehicle' => 'MURAVEY'],
            ['code_brand_vehicle' => '639', 'brand_vehicle' => 'MV AGUSTA'],
            ['code_brand_vehicle' => '323', 'brand_vehicle' => 'MZ'],
            ['code_brand_vehicle' => '846', 'brand_vehicle' => 'N.S.U'],
            ['code_brand_vehicle' => '125', 'brand_vehicle' => 'NASH'],
            ['code_brand_vehicle' => '196', 'brand_vehicle' => 'NECKAR'],
            ['code_brand_vehicle' => '847', 'brand_vehicle' => 'NEUTRAL'],
            ['code_brand_vehicle' => '406', 'brand_vehicle' => 'NEW ERA'],
            ['code_brand_vehicle' => '640', 'brand_vehicle' => 'NEW HOLLAN'],
            ['code_brand_vehicle' => '848', 'brand_vehicle' => 'NEW HYSTER'],
            ['code_brand_vehicle' => '641', 'brand_vehicle' => 'NEW KING'],
            ['code_brand_vehicle' => '470', 'brand_vehicle' => 'NIKITA'],
            ['code_brand_vehicle' => '642', 'brand_vehicle' => 'NIMBUS'],
            ['code_brand_vehicle' => '15', 'brand_vehicle' => 'NISSAN'],
            ['code_brand_vehicle' => '401', 'brand_vehicle' => 'NITRO'],
            ['code_brand_vehicle' => '643', 'brand_vehicle' => 'NON PLUS ULTRA'],
            ['code_brand_vehicle' => '247', 'brand_vehicle' => 'NORTON'],
            ['code_brand_vehicle' => '644', 'brand_vehicle' => 'NUFFIELD'],
            ['code_brand_vehicle' => '849', 'brand_vehicle' => 'NYK'],
            ['code_brand_vehicle' => '645', 'brand_vehicle' => 'OAKLAND'],
            ['code_brand_vehicle' => '282', 'brand_vehicle' => 'OKLAN'],
            ['code_brand_vehicle' => '13', 'brand_vehicle' => 'OLDSMOBILE'],
            ['code_brand_vehicle' => '1051', 'brand_vehicle' => 'OLIYA'],
            ['code_brand_vehicle' => '36', 'brand_vehicle' => 'OLTCIT'],
            ['code_brand_vehicle' => '48', 'brand_vehicle' => 'OPEL'],
            ['code_brand_vehicle' => '850', 'brand_vehicle' => 'ORANGE COUNTY CHOPPERS'],
            ['code_brand_vehicle' => '851', 'brand_vehicle' => 'ORION'],
            ['code_brand_vehicle' => '452', 'brand_vehicle' => 'OROMOTO'],
            ['code_brand_vehicle' => '646', 'brand_vehicle' => 'OSHKOSH'],
            ['code_brand_vehicle' => '736', 'brand_vehicle' => 'OSSA'],
            ['code_brand_vehicle' => '1042', 'brand_vehicle' => 'OULING'],
            ['code_brand_vehicle' => '647', 'brand_vehicle' => 'P Y H'],
            ['code_brand_vehicle' => '258', 'brand_vehicle' => 'PACER'],
            ['code_brand_vehicle' => '1014', 'brand_vehicle' => 'PACIFIC'],
            ['code_brand_vehicle' => '198', 'brand_vehicle' => 'PACKARD'],
            ['code_brand_vehicle' => '936', 'brand_vehicle' => 'PANDA CHUNZOHN'],
            ['code_brand_vehicle' => '260', 'brand_vehicle' => 'PANHARD'],
            ['code_brand_vehicle' => '259', 'brand_vehicle' => 'PANNONIA'],
            ['code_brand_vehicle' => '440', 'brand_vehicle' => 'PANTERA'],
            ['code_brand_vehicle' => '722', 'brand_vehicle' => 'PANZER'],
            ['code_brand_vehicle' => '648', 'brand_vehicle' => 'PARCE'],
            ['code_brand_vehicle' => '316', 'brand_vehicle' => 'PASAGGIO'],
            ['code_brand_vehicle' => '852', 'brand_vehicle' => 'PASSO'],
            ['code_brand_vehicle' => '937', 'brand_vehicle' => 'PAZ'],
            ['code_brand_vehicle' => '213', 'brand_vehicle' => 'PEGASSO'],
            ['code_brand_vehicle' => '963', 'brand_vehicle' => 'PERLINI'],
            ['code_brand_vehicle' => '233', 'brand_vehicle' => 'PETERBILT'],
            ['code_brand_vehicle' => '649', 'brand_vehicle' => 'PETTIBONE'],
            ['code_brand_vehicle' => '16', 'brand_vehicle' => 'PEUGEOT'],
            ['code_brand_vehicle' => '853', 'brand_vehicle' => 'PEXMA'],
            ['code_brand_vehicle' => '737', 'brand_vehicle' => 'PHW'],
            ['code_brand_vehicle' => '221', 'brand_vehicle' => 'PIAGGIO'],
            ['code_brand_vehicle' => '650', 'brand_vehicle' => 'PIAGGIO ZONGSHEN'],
            ['code_brand_vehicle' => '397', 'brand_vehicle' => 'PIERCE ARROW'],
            ['code_brand_vehicle' => '724', 'brand_vehicle' => 'PINZ GAUER'],
            ['code_brand_vehicle' => '293', 'brand_vehicle' => 'PIONEER'],
            ['code_brand_vehicle' => '725', 'brand_vehicle' => 'PIQUERSA'],
            ['code_brand_vehicle' => '854', 'brand_vehicle' => 'PLANETA'],
            ['code_brand_vehicle' => '12', 'brand_vehicle' => 'PLYMOUTH'],
            ['code_brand_vehicle' => '651', 'brand_vehicle' => 'POCLAIN'],
            ['code_brand_vehicle' => '417', 'brand_vehicle' => 'POLARIS'],
            ['code_brand_vehicle' => '351', 'brand_vehicle' => 'POLARIS ATV'],
            ['code_brand_vehicle' => '1064', 'brand_vehicle' => 'POLARSUN'],
            ['code_brand_vehicle' => '229', 'brand_vehicle' => 'POLONEZ'],
            ['code_brand_vehicle' => '24', 'brand_vehicle' => 'PONTIAC'],
            ['code_brand_vehicle' => '214', 'brand_vehicle' => 'PORSCHE'],
            ['code_brand_vehicle' => '855', 'brand_vehicle' => 'POWER WAGON'],
            ['code_brand_vehicle' => '652', 'brand_vehicle' => 'POWERMAX'],
            ['code_brand_vehicle' => '925', 'brand_vehicle' => 'PRATOO Y FORNE'],
            ['code_brand_vehicle' => '856', 'brand_vehicle' => 'PREFECT'],
            ['code_brand_vehicle' => '238', 'brand_vehicle' => 'PRINCE'],
            ['code_brand_vehicle' => '120', 'brand_vehicle' => 'PUCH'],
            ['code_brand_vehicle' => '398', 'brand_vehicle' => 'PUMA'],
            ['code_brand_vehicle' => '653', 'brand_vehicle' => 'QIANJIANG'],
            ['code_brand_vehicle' => '286', 'brand_vehicle' => 'QINGQI'],
            ['code_brand_vehicle' => '384', 'brand_vehicle' => 'QJ'],
            ['code_brand_vehicle' => '130', 'brand_vehicle' => 'QJIANG'],
            ['code_brand_vehicle' => '857', 'brand_vehicle' => 'RABBIT'],
            ['code_brand_vehicle' => '236', 'brand_vehicle' => 'RAF'],
            ['code_brand_vehicle' => '128', 'brand_vehicle' => 'RAMBLER'],
            ['code_brand_vehicle' => '654', 'brand_vehicle' => 'RAMIREZ'],
            ['code_brand_vehicle' => '655', 'brand_vehicle' => 'RANGE ROVER'],
            ['code_brand_vehicle' => '325', 'brand_vehicle' => 'REAR'],
            ['code_brand_vehicle' => '471', 'brand_vehicle' => 'REBELLIN'],
            ['code_brand_vehicle' => '926', 'brand_vehicle' => 'REGAL RAPTOR'],
            ['code_brand_vehicle' => '8', 'brand_vehicle' => 'RENAULT'],
            ['code_brand_vehicle' => '361', 'brand_vehicle' => 'RENNO'],
            ['code_brand_vehicle' => '215', 'brand_vehicle' => 'REO'],
            ['code_brand_vehicle' => '858', 'brand_vehicle' => 'REVA'],
            ['code_brand_vehicle' => '656', 'brand_vehicle' => 'REVTECH'],
            ['code_brand_vehicle' => '424', 'brand_vehicle' => 'REX MOTO'],
            ['code_brand_vehicle' => '711', 'brand_vehicle' => 'RHINO'],
            ['code_brand_vehicle' => '446', 'brand_vehicle' => 'RIDER'],
            ['code_brand_vehicle' => '657', 'brand_vehicle' => 'RLX'],
            ['code_brand_vehicle' => '204', 'brand_vehicle' => 'ROA'],
            ['code_brand_vehicle' => '658', 'brand_vehicle' => 'ROBUR'],
            ['code_brand_vehicle' => '938', 'brand_vehicle' => 'ROCAR'],
            ['code_brand_vehicle' => '378', 'brand_vehicle' => 'ROKETA'],
            ['code_brand_vehicle' => '32', 'brand_vehicle' => 'ROLLS ROYCE'],
            ['code_brand_vehicle' => '939', 'brand_vehicle' => 'ROMAN'],
            ['code_brand_vehicle' => '261', 'brand_vehicle' => 'RONART'],
            ['code_brand_vehicle' => '659', 'brand_vehicle' => 'ROSCO'],
            ['code_brand_vehicle' => '859', 'brand_vehicle' => 'ROSENBAUER'],
            ['code_brand_vehicle' => '447', 'brand_vehicle' => 'ROSSETTI'],
            ['code_brand_vehicle' => '115', 'brand_vehicle' => 'ROVER'],
            ['code_brand_vehicle' => '371', 'brand_vehicle' => 'ROYAL ENFIELD'],
            ['code_brand_vehicle' => '860', 'brand_vehicle' => 'SAAB'],
            ['code_brand_vehicle' => '321', 'brand_vehicle' => 'SACHS BIKES'],
            ['code_brand_vehicle' => '403', 'brand_vehicle' => 'SAEHAN'],
            ['code_brand_vehicle' => '278', 'brand_vehicle' => 'SAIC CHERY'],
            ['code_brand_vehicle' => '294', 'brand_vehicle' => 'SAIC WULING'],
            ['code_brand_vehicle' => '660', 'brand_vehicle' => 'SAME'],
            ['code_brand_vehicle' => '262', 'brand_vehicle' => 'SAMSUNG'],
            ['code_brand_vehicle' => '861', 'brand_vehicle' => 'SANDI'],
            ['code_brand_vehicle' => '661', 'brand_vehicle' => 'SANFENG'],
            ['code_brand_vehicle' => '263', 'brand_vehicle' => 'SANGLAS'],
            ['code_brand_vehicle' => '862', 'brand_vehicle' => 'SANGLIN'],
            ['code_brand_vehicle' => '980', 'brand_vehicle' => 'SANLEE'],
            ['code_brand_vehicle' => '957', 'brand_vehicle' => 'SANY'],
            ['code_brand_vehicle' => '374', 'brand_vehicle' => 'SANYA'],
            ['code_brand_vehicle' => '1071', 'brand_vehicle' => 'SANYOU'],
            ['code_brand_vehicle' => '399', 'brand_vehicle' => 'SATURN'],
            ['code_brand_vehicle' => '863', 'brand_vehicle' => 'SAURER'],
            ['code_brand_vehicle' => '663', 'brand_vehicle' => 'SAURON'],
            ['code_brand_vehicle' => '266', 'brand_vehicle' => 'SAVA'],
            ['code_brand_vehicle' => '864', 'brand_vehicle' => 'SCAMMELL'],
            ['code_brand_vehicle' => '216', 'brand_vehicle' => 'SCANIA'],
            ['code_brand_vehicle' => '418', 'brand_vehicle' => 'SCOOTER'],
            ['code_brand_vehicle' => '940', 'brand_vehicle' => 'SCOUTY'],
            ['code_brand_vehicle' => '865', 'brand_vehicle' => 'SEAGRAVE'],
            ['code_brand_vehicle' => '136', 'brand_vehicle' => 'SEAT'],
            ['code_brand_vehicle' => '1067', 'brand_vehicle' => 'SELVAXTREMA'],
            ['code_brand_vehicle' => '1055', 'brand_vehicle' => 'SENKE'],
            ['code_brand_vehicle' => '866', 'brand_vehicle' => 'SERVAL'],
            ['code_brand_vehicle' => '984', 'brand_vehicle' => 'SHACMAN'],
            ['code_brand_vehicle' => '664', 'brand_vehicle' => 'SHANGHAI'],
            ['code_brand_vehicle' => '867', 'brand_vehicle' => 'SHANGLI'],
            ['code_brand_vehicle' => '868', 'brand_vehicle' => 'SHANYANG'],
            ['code_brand_vehicle' => '1035', 'brand_vehicle' => 'SHELBY'],
            ['code_brand_vehicle' => '290', 'brand_vehicle' => 'SHENGQIBAO'],
            ['code_brand_vehicle' => '869', 'brand_vehicle' => 'SHERPA'],
            ['code_brand_vehicle' => '472', 'brand_vehicle' => 'SHIJIAZHUANG'],
            ['code_brand_vehicle' => '665', 'brand_vehicle' => 'SHINERAY'],
            ['code_brand_vehicle' => '380', 'brand_vehicle' => 'SHINERAY MOTOS'],
            ['code_brand_vehicle' => '870', 'brand_vehicle' => 'SHUANGHUAN'],
            ['code_brand_vehicle' => '871', 'brand_vehicle' => 'SHUANGSHI'],
            ['code_brand_vehicle' => '299', 'brand_vehicle' => 'SIGMA'],
            ['code_brand_vehicle' => '11', 'brand_vehicle' => 'SIMCA'],
            ['code_brand_vehicle' => '0', 'brand_vehicle' => 'SIN MARCA'],
            ['code_brand_vehicle' => '265', 'brand_vehicle' => 'SINGER'],
            ['code_brand_vehicle' => '1063', 'brand_vehicle' => 'SINOTRUK'],
            ['code_brand_vehicle' => '666', 'brand_vehicle' => 'SINOTRUK HOWO'],
            ['code_brand_vehicle' => '135', 'brand_vehicle' => 'SISU'],
            ['code_brand_vehicle' => '941', 'brand_vehicle' => 'SKANIA VABIF'],
            ['code_brand_vehicle' => '667', 'brand_vehicle' => 'SKINGO'],
            ['code_brand_vehicle' => '40', 'brand_vehicle' => 'SKODA'],
            ['code_brand_vehicle' => '341', 'brand_vehicle' => 'SKOOT MOTORCYCLES'],
            ['code_brand_vehicle' => '315', 'brand_vehicle' => 'SKYGO'],
            ['code_brand_vehicle' => '668', 'brand_vehicle' => 'SKYMAX'],
            ['code_brand_vehicle' => '872', 'brand_vehicle' => 'SKYTEAM'],
            ['code_brand_vehicle' => '988', 'brand_vehicle' => 'SM'],
            ['code_brand_vehicle' => '1002', 'brand_vehicle' => 'SMA'],
            ['code_brand_vehicle' => '273', 'brand_vehicle' => 'SMART'],
            ['code_brand_vehicle' => '669', 'brand_vehicle' => 'SMC'],
            ['code_brand_vehicle' => '873', 'brand_vehicle' => 'SOLARI'],
            ['code_brand_vehicle' => '387', 'brand_vehicle' => 'SONGSHENG'],
            ['code_brand_vehicle' => '874', 'brand_vehicle' => 'SONIKA'],
            ['code_brand_vehicle' => '875', 'brand_vehicle' => 'SONZINI'],
            ['code_brand_vehicle' => '876', 'brand_vehicle' => 'SOYAT'],
            ['code_brand_vehicle' => '877', 'brand_vehicle' => 'SP@ZZIO'],
            ['code_brand_vehicle' => '237', 'brand_vehicle' => 'SPARTAN'],
            ['code_brand_vehicle' => '454', 'brand_vehicle' => 'SQ RACING'],
            ['code_brand_vehicle' => '878', 'brand_vehicle' => 'SRFHUAIGE'],
            ['code_brand_vehicle' => '942', 'brand_vehicle' => 'SSANGYANG'],
            ['code_brand_vehicle' => '217', 'brand_vehicle' => 'SSANGYONG'],
            ['code_brand_vehicle' => '879', 'brand_vehicle' => 'SST'],
            ['code_brand_vehicle' => '943', 'brand_vehicle' => 'STAR'],
            ['code_brand_vehicle' => '738', 'brand_vehicle' => 'STAVOSTROJ'],
            ['code_brand_vehicle' => '880', 'brand_vehicle' => 'STEINBOCK'],
            ['code_brand_vehicle' => '954', 'brand_vehicle' => 'STERLING'],
            ['code_brand_vehicle' => '670', 'brand_vehicle' => 'STEYR DAIMLER PUCH'],
            ['code_brand_vehicle' => '881', 'brand_vehicle' => 'STIRES VM'],
            ['code_brand_vehicle' => '218', 'brand_vehicle' => 'STUDEBAKER'],
            ['code_brand_vehicle' => '944', 'brand_vehicle' => 'STUTZ'],
            ['code_brand_vehicle' => '17', 'brand_vehicle' => 'SUBARU'],
            ['code_brand_vehicle' => '671', 'brand_vehicle' => 'SUKIDA'],
            ['code_brand_vehicle' => '430', 'brand_vehicle' => 'SUKYAMA'],
            ['code_brand_vehicle' => '672', 'brand_vehicle' => 'SUM'],
            ['code_brand_vehicle' => '987', 'brand_vehicle' => 'SUMA'],
            ['code_brand_vehicle' => '264', 'brand_vehicle' => 'SUMBEAM'],
            ['code_brand_vehicle' => '882', 'brand_vehicle' => 'SUMO'],
            ['code_brand_vehicle' => '355', 'brand_vehicle' => 'SUMOTO'],
            ['code_brand_vehicle' => '883', 'brand_vehicle' => 'SUNASA QINGQI'],
            ['code_brand_vehicle' => '673', 'brand_vehicle' => 'SUNDIRO'],
            ['code_brand_vehicle' => '884', 'brand_vehicle' => 'SUPERMOTO'],
            ['code_brand_vehicle' => '52', 'brand_vehicle' => 'SUZUKI'],
            ['code_brand_vehicle' => '370', 'brand_vehicle' => 'SYM'],
            ['code_brand_vehicle' => '945', 'brand_vehicle' => 'T.J.C.'],
            ['code_brand_vehicle' => '726', 'brand_vehicle' => 'TADANO'],
            ['code_brand_vehicle' => '885', 'brand_vehicle' => 'TALBOT'],
            ['code_brand_vehicle' => '473', 'brand_vehicle' => 'TALON'],
            ['code_brand_vehicle' => '101', 'brand_vehicle' => 'TAM'],
            ['code_brand_vehicle' => '946', 'brand_vehicle' => 'TANDEM'],
            ['code_brand_vehicle' => '886', 'brand_vehicle' => 'TANTA'],
            ['code_brand_vehicle' => '1012', 'brand_vehicle' => 'TAO TAO'],
            ['code_brand_vehicle' => '272', 'brand_vehicle' => 'TATA'],
            ['code_brand_vehicle' => '887', 'brand_vehicle' => 'TATRA'],
            ['code_brand_vehicle' => '37', 'brand_vehicle' => 'TAVRIA'],
            ['code_brand_vehicle' => '1033', 'brand_vehicle' => 'TAYLOR DUNN'],
            ['code_brand_vehicle' => '674', 'brand_vehicle' => 'TCM'],
            ['code_brand_vehicle' => '739', 'brand_vehicle' => 'TCUMSON'],
            ['code_brand_vehicle' => '982', 'brand_vehicle' => 'TEAM RYDER'],
            ['code_brand_vehicle' => '474', 'brand_vehicle' => 'TELCOLINE'],
            ['code_brand_vehicle' => '976', 'brand_vehicle' => 'TEMPEST'],
            ['code_brand_vehicle' => '888', 'brand_vehicle' => 'TEMPO'],
            ['code_brand_vehicle' => '740', 'brand_vehicle' => 'TENNAN'],
            ['code_brand_vehicle' => '675', 'brand_vehicle' => 'TEREX'],
            ['code_brand_vehicle' => '441', 'brand_vehicle' => 'TERRA JET'],
            ['code_brand_vehicle' => '889', 'brand_vehicle' => 'TGA-200-G'],
            ['code_brand_vehicle' => '268', 'brand_vehicle' => 'THAMES'],
            ['code_brand_vehicle' => '955', 'brand_vehicle' => 'THOMAS'],
            ['code_brand_vehicle' => '1030', 'brand_vehicle' => 'THOMAS BUILT BUSES'],
            ['code_brand_vehicle' => '676', 'brand_vehicle' => 'THUNDER CYCLE DESIGN'],
            ['code_brand_vehicle' => '308', 'brand_vehicle' => 'TITANIA'],
            ['code_brand_vehicle' => '449', 'brand_vehicle' => 'TIXXON'],
            ['code_brand_vehicle' => '890', 'brand_vehicle' => 'TMD'],
            ['code_brand_vehicle' => '383', 'brand_vehicle' => 'TMEC'],
            ['code_brand_vehicle' => '677', 'brand_vehicle' => 'TONARO'],
            ['code_brand_vehicle' => '947', 'brand_vehicle' => 'TONGBAO'],
            ['code_brand_vehicle' => '404', 'brand_vehicle' => 'TONGKO'],
            ['code_brand_vehicle' => '891', 'brand_vehicle' => 'TONGYU'],
            ['code_brand_vehicle' => '1000', 'brand_vehicle' => 'TORNADO'],
            ['code_brand_vehicle' => '972', 'brand_vehicle' => 'TOURING'],
            ['code_brand_vehicle' => '741', 'brand_vehicle' => 'TOWMOTOR'],
            ['code_brand_vehicle' => '892', 'brand_vehicle' => 'TOYOPET'],
            ['code_brand_vehicle' => '25', 'brand_vehicle' => 'TOYOTA'],
            ['code_brand_vehicle' => '267', 'brand_vehicle' => 'TRABANT'],
            ['code_brand_vehicle' => '1006', 'brand_vehicle' => 'TRACTOCASA'],
            ['code_brand_vehicle' => '948', 'brand_vehicle' => 'TRADER'],
            ['code_brand_vehicle' => '219', 'brand_vehicle' => 'TRIUMPH'],
            ['code_brand_vehicle' => '678', 'brand_vehicle' => 'TRIWIL'],
            ['code_brand_vehicle' => '893', 'brand_vehicle' => 'TULA'],
            ['code_brand_vehicle' => '426', 'brand_vehicle' => 'TVS'],
            ['code_brand_vehicle' => '475', 'brand_vehicle' => 'TX MOTORS'],
            ['code_brand_vehicle' => '363', 'brand_vehicle' => 'TYCO'],
            ['code_brand_vehicle' => '369', 'brand_vehicle' => 'U.S.W.MOTORS'],
            ['code_brand_vehicle' => '45', 'brand_vehicle' => 'UAZ'],
            ['code_brand_vehicle' => '1065', 'brand_vehicle' => 'UD TRUCKS'],
            ['code_brand_vehicle' => '894', 'brand_vehicle' => 'UFO'],
            ['code_brand_vehicle' => '330', 'brand_vehicle' => 'UKM'],
            ['code_brand_vehicle' => '949', 'brand_vehicle' => 'UNDERBONE'],
            ['code_brand_vehicle' => '679', 'brand_vehicle' => 'UNIMOG'],
            ['code_brand_vehicle' => '340', 'brand_vehicle' => 'UNISON'],
            ['code_brand_vehicle' => '381', 'brand_vehicle' => 'UNITED MOTORS'],
            ['code_brand_vehicle' => '680', 'brand_vehicle' => 'UNIVERSAL'],
            ['code_brand_vehicle' => '347', 'brand_vehicle' => 'URAL'],
            ['code_brand_vehicle' => '681', 'brand_vehicle' => 'USA MOTORS'],
            ['code_brand_vehicle' => '359', 'brand_vehicle' => 'USW'],
            ['code_brand_vehicle' => '895', 'brand_vehicle' => 'VALIANT'],
            ['code_brand_vehicle' => '896', 'brand_vehicle' => 'VALKYRIE'],
            ['code_brand_vehicle' => '682', 'brand_vehicle' => 'VALMET'],
            ['code_brand_vehicle' => '683', 'brand_vehicle' => 'VALTRA'],
            ['code_brand_vehicle' => '897', 'brand_vehicle' => 'VANGUARD'],
            ['code_brand_vehicle' => '274', 'brand_vehicle' => 'VARZI'],
            ['code_brand_vehicle' => '244', 'brand_vehicle' => 'VAUSHALL'],
            ['code_brand_vehicle' => '950', 'brand_vehicle' => 'VEDETTE'],
            ['code_brand_vehicle' => '382', 'brand_vehicle' => 'VENOM MOTORS'],
            ['code_brand_vehicle' => '410', 'brand_vehicle' => 'VENTIE'],
            ['code_brand_vehicle' => '305', 'brand_vehicle' => 'VENTO'],
            ['code_brand_vehicle' => '742', 'brand_vehicle' => 'VERKHOVINA'],
            ['code_brand_vehicle' => '389', 'brand_vehicle' => 'VERUCCI'],
            ['code_brand_vehicle' => '245', 'brand_vehicle' => 'VESPA'],
            ['code_brand_vehicle' => '95', 'brand_vehicle' => 'VIASA'],
            ['code_brand_vehicle' => '301', 'brand_vehicle' => 'VICTORY'],
            ['code_brand_vehicle' => '684', 'brand_vehicle' => 'VISAIL'],
            ['code_brand_vehicle' => '1036', 'brand_vehicle' => 'VMOTO'],
            ['code_brand_vehicle' => '685', 'brand_vehicle' => 'VOGELE'],
            ['code_brand_vehicle' => '898', 'brand_vehicle' => 'VOGUE'],
            ['code_brand_vehicle' => '1003', 'brand_vehicle' => 'VOLDA'],
            ['code_brand_vehicle' => '39', 'brand_vehicle' => 'VOLGA'],
            ['code_brand_vehicle' => '9', 'brand_vehicle' => 'VOLKSWAGEN'],
            ['code_brand_vehicle' => '26', 'brand_vehicle' => 'VOLVO'],
            ['code_brand_vehicle' => '899', 'brand_vehicle' => 'VONROAD'],
            ['code_brand_vehicle' => '951', 'brand_vehicle' => 'VOSHUD'],
            ['code_brand_vehicle' => '743', 'brand_vehicle' => 'VOSJOB'],
            ['code_brand_vehicle' => '269', 'brand_vehicle' => 'VOSJOD'],
            ['code_brand_vehicle' => '249', 'brand_vehicle' => 'VOSKHOD'],
            ['code_brand_vehicle' => '900', 'brand_vehicle' => 'WAGONNER'],
            ['code_brand_vehicle' => '901', 'brand_vehicle' => 'WAJAX'],
            ['code_brand_vehicle' => '326', 'brand_vehicle' => 'WALTER'],
            ['code_brand_vehicle' => '1011', 'brand_vehicle' => 'WANCH'],
            ['code_brand_vehicle' => '968', 'brand_vehicle' => 'WANHU'],
            ['code_brand_vehicle' => '334', 'brand_vehicle' => 'WANXIN'],
            ['code_brand_vehicle' => '126', 'brand_vehicle' => 'WARTBURG'],
            ['code_brand_vehicle' => '220', 'brand_vehicle' => 'WARZAMA'],
            ['code_brand_vehicle' => '686', 'brand_vehicle' => 'WARZAWA'],
            ['code_brand_vehicle' => '442', 'brand_vehicle' => 'WCR'],
            ['code_brand_vehicle' => '408', 'brand_vehicle' => 'WEST'],
            ['code_brand_vehicle' => '927', 'brand_vehicle' => 'WEST WARRIOR'],
            ['code_brand_vehicle' => '687', 'brand_vehicle' => 'WESTERN STAR'],
            ['code_brand_vehicle' => '270', 'brand_vehicle' => 'WHITE'],
            ['code_brand_vehicle' => '129', 'brand_vehicle' => 'WILLCO'],
            ['code_brand_vehicle' => '66', 'brand_vehicle' => 'WILLYS'],
            ['code_brand_vehicle' => '902', 'brand_vehicle' => 'WINCHEMG'],
            ['code_brand_vehicle' => '688', 'brand_vehicle' => 'WKT'],
            ['code_brand_vehicle' => '903', 'brand_vehicle' => 'WLLHELMSHAVEN'],
            ['code_brand_vehicle' => '333', 'brand_vehicle' => 'WONJAN'],
            ['code_brand_vehicle' => '904', 'brand_vehicle' => 'WORD LA FRANCE'],
            ['code_brand_vehicle' => '476', 'brand_vehicle' => 'WORKMAN'],
            ['code_brand_vehicle' => '905', 'brand_vehicle' => 'WORLDSTAR'],
            ['code_brand_vehicle' => '906', 'brand_vehicle' => 'WSK'],
            ['code_brand_vehicle' => '400', 'brand_vehicle' => 'WULING'],
            ['code_brand_vehicle' => '438', 'brand_vehicle' => 'WUYANG'],
            ['code_brand_vehicle' => '477', 'brand_vehicle' => 'WUZHENG'],
            ['code_brand_vehicle' => '689', 'brand_vehicle' => 'XCMG'],
            ['code_brand_vehicle' => '1054', 'brand_vehicle' => 'XGJAO'],
            ['code_brand_vehicle' => '307', 'brand_vehicle' => 'XIALI'],
            ['code_brand_vehicle' => '231', 'brand_vehicle' => 'XINGFU'],
            ['code_brand_vehicle' => '907', 'brand_vehicle' => 'XINGLING'],
            ['code_brand_vehicle' => '432', 'brand_vehicle' => 'XINGUE'],
            ['code_brand_vehicle' => '409', 'brand_vehicle' => 'XINGYUE'],
            ['code_brand_vehicle' => '478', 'brand_vehicle' => 'XINKAI'],
            ['code_brand_vehicle' => '908', 'brand_vehicle' => 'XINLING'],
            ['code_brand_vehicle' => '909', 'brand_vehicle' => 'XINTIAN KINROAD'],
            ['code_brand_vehicle' => '352', 'brand_vehicle' => 'XISPA'],
            ['code_brand_vehicle' => '411', 'brand_vehicle' => 'XL XINLING'],
            ['code_brand_vehicle' => '978', 'brand_vehicle' => 'XRP SAIN'],
            ['code_brand_vehicle' => '910', 'brand_vehicle' => 'XSG ING QIJITUA'],
            ['code_brand_vehicle' => '1019', 'brand_vehicle' => 'YADEA'],
            ['code_brand_vehicle' => '998', 'brand_vehicle' => 'YAKEY'],
            ['code_brand_vehicle' => '420', 'brand_vehicle' => 'YAKIMA'],
            ['code_brand_vehicle' => '690', 'brand_vehicle' => 'YALE'],
            ['code_brand_vehicle' => '56', 'brand_vehicle' => 'YAMAHA'],
            ['code_brand_vehicle' => '691', 'brand_vehicle' => 'YAMASAKY'],
            ['code_brand_vehicle' => '377', 'brand_vehicle' => 'YAMATI'],
            ['code_brand_vehicle' => '1043', 'brand_vehicle' => 'YAXING'],
            ['code_brand_vehicle' => '1010', 'brand_vehicle' => 'YGM'],
            ['code_brand_vehicle' => '692', 'brand_vehicle' => 'YIBEN'],
            ['code_brand_vehicle' => '456', 'brand_vehicle' => 'YIBEN-YBFALCON'],
            ['code_brand_vehicle' => '339', 'brand_vehicle' => 'YINGANG'],
            ['code_brand_vehicle' => '952', 'brand_vehicle' => 'YITAKI'],
            ['code_brand_vehicle' => '911', 'brand_vehicle' => 'YLM'],
            ['code_brand_vehicle' => '992', 'brand_vehicle' => 'YONGKANG EASY VEHICLE'],
            ['code_brand_vehicle' => '693', 'brand_vehicle' => 'YONKANG XINGYUE'],
            ['code_brand_vehicle' => '412', 'brand_vehicle' => 'YUAN'],
            ['code_brand_vehicle' => '694', 'brand_vehicle' => 'YUANDA'],
            ['code_brand_vehicle' => '695', 'brand_vehicle' => 'YUEJIN'],
            ['code_brand_vehicle' => '225', 'brand_vehicle' => 'YUGO'],
            ['code_brand_vehicle' => '696', 'brand_vehicle' => 'YUMBO'],
            ['code_brand_vehicle' => '967', 'brand_vehicle' => 'YUTONG'],
            ['code_brand_vehicle' => '455', 'brand_vehicle' => 'ZAHAV'],
            ['code_brand_vehicle' => '110', 'brand_vehicle' => 'ZASTAVA'],
            ['code_brand_vehicle' => '912', 'brand_vehicle' => 'ZENA'],
            ['code_brand_vehicle' => '697', 'brand_vehicle' => 'ZEPHYR'],
            ['code_brand_vehicle' => '698', 'brand_vehicle' => 'ZETOR'],
            ['code_brand_vehicle' => '913', 'brand_vehicle' => 'ZHAN'],
            ['code_brand_vehicle' => '354', 'brand_vehicle' => 'ZHEJIANG'],
            ['code_brand_vehicle' => '699', 'brand_vehicle' => 'ZHEJIANG HANGCHA'],
            ['code_brand_vehicle' => '428', 'brand_vehicle' => 'ZHEJIANG LINGTIAN'],
            ['code_brand_vehicle' => '415', 'brand_vehicle' => 'ZHEJIANG QIANJIANG'],
            ['code_brand_vehicle' => '700', 'brand_vehicle' => 'ZHENG LI'],
            ['code_brand_vehicle' => '953', 'brand_vehicle' => 'ZHONGHUA'],
            ['code_brand_vehicle' => '914', 'brand_vehicle' => 'ZHONGNENG'],
            ['code_brand_vehicle' => '368', 'brand_vehicle' => 'ZHONGXING'],
            ['code_brand_vehicle' => '915', 'brand_vehicle' => 'ZHONGYU'],
            ['code_brand_vehicle' => '416', 'brand_vehicle' => 'ZHUJIANG'],
            ['code_brand_vehicle' => '701', 'brand_vehicle' => 'ZID'],
            ['code_brand_vehicle' => '702', 'brand_vehicle' => 'ZIGMA'],
            ['code_brand_vehicle' => '1060', 'brand_vehicle' => 'ZILI MOTORS'],
            ['code_brand_vehicle' => '703', 'brand_vehicle' => 'ZIP STAR'],
            ['code_brand_vehicle' => '916', 'brand_vehicle' => 'ZIU'],
            ['code_brand_vehicle' => '1045', 'brand_vehicle' => 'ZNA'],
            ['code_brand_vehicle' => '450', 'brand_vehicle' => 'ZNEN'],
            ['code_brand_vehicle' => '704', 'brand_vehicle' => 'ZODIAC'],
            ['code_brand_vehicle' => '336', 'brand_vehicle' => 'ZONGSHEN'],
            ['code_brand_vehicle' => '429', 'brand_vehicle' => 'ZOTYE'],
            ['code_brand_vehicle' => '917', 'brand_vehicle' => 'ZQ MOTORS'],
            ['code_brand_vehicle' => '918', 'brand_vehicle' => 'ZUK'],
            ['code_brand_vehicle' => '919', 'brand_vehicle' => 'ZUK NYSA'],
            ['code_brand_vehicle' => '243', 'brand_vehicle' => 'ZUMY'],
            ['code_brand_vehicle' => '745', 'brand_vehicle' => 'ZUNDAPP'],
            ['code_brand_vehicle' => '705', 'brand_vehicle' => 'ZUNK'],


        ]);
    }
}
